latticexyz/mud

packages/network/src/workers/CacheStore.spec.ts
packages/network/src/workers/CacheStore.ts
packages/network/src/workers/SyncWorker.spec.ts
packages/network/src/workers/syncUtils.spec.ts
packages/network/src/workers/syncUtils.ts
packages/utils/src/hash.ts

Previously we were padding entity ids to a 256 bit string by default to align padded and non-padded
entity id strings. This caused issues in components referencing other entity ids and caused
unnecessary memory usage  for storing 0s. This change aligns entity ids by removing all padding by
default.

fix(network): align hex entity id formatting

---

packages/network/src/workers/SyncWorker.spec.ts
packages/network/src/workers/SyncWorker.ts
packages/network/src/workers/constants.ts
packages/network/src/workers/index.ts
packages/std-client/src/utils.ts

Add a loading state component with id keccak("component.LoadingState") to the sync worker that is
used to broadcast the current loading state to the main thread. This can be used to build a loading
screen in the client by adding a new network layer component with "contractId"
kecccak("component.LoadingState").
BREAKING CHANGE: The loading state component is attached to the entity with id 0x060D (GodID). The
std-client package previously exported a different mudwar specific GodID, which has been replaced
with the 0x060D GodID exported by the network package.

feat(network): add loading state component update stream to SyncWorker

---

packages/network/src/workers/CacheStore.ts
packages/network/src/workers/SyncWorker.spec.ts
packages/network/src/workers/SyncWorker.ts
packages/network/src/workers/syncUtils.ts

- fix a bug during initial sync: previously we were loading three states during the initial sync (cache state, gap state, live state) and then merged them to get the full initial state. This approach led to an issue when one of the states included a **ComponentValueRemoved** event targeting a value in another state (eg cache state has a component value, gap state applies an event to remove this value, but because the gap state doesn't have the value, the removal event is not actually applied when merging the states). To prevent this issue, this PR changes the initial sync logic to load **events** of the "gap state" and "live state" and apply them to the cache state, such that removal events are considered.
- store cache to indexdb on every block instead of every time interval to avoid …

fix(network): initial sync

---

packages/recs/src/Component.ts
packages/recs/src/Indexer.ts
packages/recs/src/constants.ts
packages/recs/src/types.ts
packages/std-client/src/components/ActionComponent.ts
packages/std-client/src/systems/ActionSystem/createActionSystem.ts
packages/std-client/src/systems/ActionSystem/types.ts

- This PR adds support for custom types in components that don't fit the existing `Types` definitions. This custom type has full typescript support, but on the downside can't be read in javascript, so for example automatic decoders/encoders couldn't be inferred from it.
- First use case of this is the `Action` component defined in the `ActionSystem`, which now allows consumers to define a custom `metadata` type to add more information to actions that might be relevant for rendering.

feat(recs): add support for custom type in component

---

packages/network/src/createDecoder.ts
packages/network/src/createSyncWorker.ts
packages/network/src/types.ts
packages/network/src/workers/SyncWorker.ts
packages/solecs/src/LibTypes.sol
packages/std-contracts/src/components/FunctionComponent.sol

- add `ADDRESS` and `BYTES4` schema types
- add `FunctionComponent` to store a contract address and function selector
- add `staticcallFunctionSelector` util to simplify calling function stored in `FunctionComponent`
- remove unused generic type from `SyncWorkerConfig`

feat(std-contracts): add FunctionComponent

---

packages/network/src/workers/syncUtils.ts

Fixes the issue where events of type `ComponentValueRemoved` were not correctly decoded when coming from the stream service

fix: check event type instead of just value before decoding

---

packages/services/cmd/ecs-relay/main.go
packages/services/go.mod
packages/services/go.sum
packages/services/pkg/eth/client.go
packages/services/pkg/grpc/relay.go
packages/services/pkg/grpc/server.go
packages/services/pkg/relay/core.go

- Toggle to switch on / off service-side signature verification before relay
- Rate limiting of `/Push` msg relay endpoint per client
- Only allow authenticated clients with balance > 0 to relay via `/Push`

feat: flag for sig verification, rate limiting of push, and check for balance when relaying

---

packages/solecs/src/Indexer.sol

comments are uniformly capitalized in code base; this comment is not capitalized

docs: fix typo

---

packages/network/src/workers/SyncWorker.spec.ts
packages/network/src/workers/SyncWorker.ts

- catch errors in event stream from stream service and fall back to rpc in case of an error

feat(network): fall back to rpc if stream service errors

---

packages/recs/src/types.ts
packages/solecs/src/Component.sol
packages/solecs/src/World.sol
packages/solecs/src/interfaces/IWorld.sol
packages/std-client/src/components/ActionComponent.ts
packages/std-client/src/systems/ActionSystem/createActionSystem.ts

- fix(solecs): only allow components to register their own updates (before it was possible for anyone to call `registerComponentValueSet`)
- feat(std-client): add support for multiple overrides per component per action

fix(solecs): only allow components to register their own updates, feat(std-client): add support for multiple overrides per component per action

---

packages/services/pkg/snapshot/snapshot.go

When hex encoding the value in the 'ownedBy` component we can't rely on casing and should checksum then compare in order to prune for specific address

fix(snapshot): checksum address / value when pruning snapshot

---

packages/network/package.json
packages/network/src/createSyncWorker.ts
packages/network/src/workers/SyncWorker.spec.ts
packages/network/src/workers/SyncWorker.ts
packages/std-client/package.json
packages/std-client/src/setup/setupMUDNetwork.ts
yarn.lock

On very high load we were "losing state entries/events" somewhere on the way from the sync worker to the main thread. This PR adds an "ack" event sent from the main thread to the sync worker when the main thread is done processing state updates from the sync worker to avoid blocking the main thread with too many state updates at once. This has the positive side effect that we don't have to throttle event processing on the main thread with a fixed number anymore, but events are always processed at the maximum speed the main thread is capable of.

feat(network): send ack between main thread and sync worker

---

packages/solecs/src/MapSet.sol

Remove forge console import from solecs MapSet contract.
The console is not used and there is no reason to keep debugging import in this file.

chore(solecs): remove console import from MapSet

---

packages/network/src/createSystemExecutor.ts
packages/std-client/src/setup/setupMUDNetwork.ts

Before systems not included in the complied systems types were ignored by the client. This made it hard to dynamically call systems in the client that were deployed after the main client was deployed.
This PR changes the client logic to create an ethers `Contract` object for every system added to the world systems registry. If no id preimage is available on the client, the contract can be called via it's hashed id.
Example:
If system is known in advance, it's can be called via its id preimage and types:
```
systems["system.Move"].executeTyped(coord);
```
If a system is not known in advance, it can still be called via its hashed id (untyped):
```
untypedSystems[keccak256("system.Move")].executeTyped(coord);
```

feat(network): allow calling systems by hashed id

---

packages/network/src/createSystemExecutor.ts
packages/std-client/src/setup/setupMUDNetwork.ts

- expose `registerSystem` function to register new system contracts in the client after the client has been deployed (ie in plugins)

feat(network): expose method to register new system contracts on the client

---

packages/std-contracts/src/systems/UpgradableSystem.sol

Use openzeppelin delegate call implementation in assembly for UpgradableSystem

fix(std-contracts): use assembly for delegation in UpgradableSystem

---

packages/ecs-browser/package.json
packages/ecs-browser/src/Browser.tsx
packages/ecs-browser/src/PrototypeCreator/PrototypeCreator.tsx
packages/ecs-browser/src/QueryBuilder/PositionFilterButton.tsx
packages/ecs-browser/src/QueryBuilder/QueryBuilder.tsx
packages/ecs-browser/src/shared.ts

Removing the shared files from phaserx with locally shared functions inside of the ecs-browser
package inside of shared.ts
fix #231

refactor(ecs-browser): removing phaserx deps from ecs-browser

---

packages/solecs/src/MapSet.sol
packages/solecs/src/Set.sol

Fixes a critical security bug in solecs (restricting write access to internal MapSet and Set contracts to the owner of those contracts)

fix(solecs): restrict write access to Set and MapSet to owner

---

packages/phaserx/src/createCamera.ts
packages/phaserx/src/types.ts

We don't need to require a `phaserSelector`, since we already have access to the `canvas` element, which is a more accurate representation of game boundaries anyway.
Also adds a comment so we remember why we're disabling default gesture events.

refactor: remove need for specifying phaserSelector in createCamera

---

packages/phaserx/package.json
packages/std-client/package.json
yarn.lock

Lots of rendering improvements by Phaser leaning more on WebGL: https://github.com/photonstorm/phaser/releases

build: bump phaser to latest beta (3.60.0-beta.14)

---

packages/phaserx/src/createCamera.ts

recalculate world view on phaser resize (otherwise calling game.scale.resize() may not load in chunks that were previously out of view)

fix: recalculate world view on phaser resize

---

packages/solecs/src/interfaces/IPayableSystem.sol
packages/solecs/src/interfaces/ISystem.sol
packages/solecs/src/systems/RegisterSystem.sol
packages/std-contracts/src/systems/BulkSetStateSystem.sol
packages/std-contracts/src/systems/ComponentDevSystem.sol

This is changed as Typechain-exported Contracts do not like the variable name arguments as its a
reserved keyword in strict-mode Classes

style(solecs): rename arguments to args

---

packages/solecs/src/test/utils.t.sol
packages/solecs/src/utils.sol

- Add a util to make splitting up bitpacked data easier
- Context: we currently use abi.encode in default components to encode/decode structs to store them in components, but abi.encode pads every struct entry to 32 bytes, wasting a lot of gas on storage, so we should change it to tighter bitpacking

feat(solecs): add util to split up bitpacked data

---

_includes/head.html

Retype overrode custom styling when navigating to a new page; this PR adds `!important` flags to custom css to make sure it has higher precedence than default retype styling.

docs: enforce custom retype styling

---

.github/workflows/docs.yml
.github/workflows/test.yml
package.json
packages/cli/src/contracts/LibDeploy.ejs
packages/cli/src/contracts/LibDeploy.sol
packages/solecs/src/interfaces/IWorld.sol
packages/std-contracts/src/test/MudTest.t.sol

* This PR replaces `World` and `Component` in deploy/test files with `IWorld` and `IComponent` to allow alternative World/Component implementations

fix: use interfaces in LibDeploy

---

.github/workflows/docs.yml
packages/cli/src/commands/trace.ts

The `cast run` call in `mud trace` was not using the `rpc` argument. It was defaulting to localhost:8545, which breaks for production chains.
This pr fixes that problem.

fix(cli): mud trace bug for non-local networks

---

packages/solecs/src/interfaces/IComponent.sol

this is helpful when writing Libraries that need world access but only receive `IUint256Component components` as an argument

feat(solecs): add world to IComponent definition

---

packages/std-client/src/setup/setupMUDNetwork.ts
packages/std-client/src/setup/types.ts

Without this, your console will see a bunch of logs like this:

fix: add LoadingState component from SyncWorker

---

packages/cli/src/commands/devnode.ts

Lattice/MUD testnet runs with 100m gas limit, so this bumps the local devnode testnet to match so we can do a little more work when e.g. initializing a world
We should also make this configurable via CLI!
Open question around what we want our default to be, or put another way, what chains we want MUD dev to be compatible with and their respective gas limits. Since we haven't done a ton of gas golfing, I assume we prob won't be doing much with MUD on mainnet for now?

feat: bump devnode gas limit to 100m

---

packages/network/package.json
packages/network/src/debug.ts
packages/network/src/workers/CacheStore.ts
packages/network/src/workers/Sync.worker.ts
packages/network/src/workers/SyncWorker.ts
packages/network/src/workers/debug.ts
packages/network/src/workers/syncUtils.ts
yarn.lock

Worker logs are really noisy and get in the way of my own app's logs, so this PR moves them into the `debug` library, which namespaces them and makes them opt-in (with the "Verbose" log level and namespace logging toggled with e.g. `localStorage.debug = mud.*`)
I'll plan to move more things to this in the future.

refactor: move worker logs to debug

---

packages/recs/src/Component.ts

Before this change, creating new entities with overrides on the client (for optimistic rendering) resulted in ~no visible changes.

fix: new entities should be included in overrides

---

packages/cli/src/commands/codegen-libdeploy.ts
packages/cli/src/utils/codegen.ts
packages/cli/src/utils/deploy.ts

Running the dev scripts would delete/overwrite the `LibDeploy.sol` file, which kept later parts of the hot reloading from continuing (e.g. couldn't find deleted file). This may only be visible with linked MUD deps, didn't test with a regular npm install.

fix(cli): reset LibDeploy.sol using original/cached contents

---

packages/std-contracts/src/test/MudTest.t.sol

* add `virtual` keyword to make MudTest's `setUp` overridable

fix(std-contracts): add virtual to MudTest setUp

---

packages/std-client/src/setup/setupMUDNetwork.ts

* before #288 users had to manually define the `LoadingState` component. Since #288 `LoadingState` is created by default in `setupMUDNetwork`, overriding any user-defined `LoadingState` component
* this caused previous clients who had a custom `LoadingState` component and used it for a loading screen to get stuck in that loading screen because their component wasn't updated anymore
* With this PRs components passed in by users get priority over default components (eg if a component with contract id `component.LoadingState` is passed in, it will be used as `LoadingState` component instead of creating a new one)

fix(std-client): allow default components to be passed in to setupMUDNetwork

---

packages/cli/src/commands/deploy-contracts.ts
packages/cli/src/contracts/LibDeployStub.sol
packages/cli/src/utils/build.ts
packages/cli/src/utils/codegen.ts
packages/cli/src/utils/deploy.ts

* add better logs to `deploy` command (forwarding forge errors)
* add manual gas price check (forge was using a way too high gas price when deploying to the lattice testnet, so the balance requirements where way too high)
* fix a bug where LibDeploy would be overridden during deploy and not reset afterwards (missing `await`)

fix(cli): better logs, more resilience, better gas price mgmt

---

packages/cli/src/commands/devnode.ts

This reverts commit a02e44bb9e3c2ee6b8aaea7b080cd35820bf1de1.
I've grown a little afraid of this 100m limit as a default. Someone might build on it assuming they can deploy to a testnet or mainnet, but find that they have to do a bunch of refactoring to stay under the (30m standard) gas limit.
The original motivation for bumping this was the tutorial, but I found a way to simplify the initializing code so it didn't need so much gas.
I'll prob revisit this in the future to make it configurable so folks can break out of the default limit.

Revert "feat: bump devnode gas limit to 100m (#289)"

---

packages/solecs/README.md
packages/solecs/package.json
packages/solecs/remappings.txt
packages/solecs/src/BareComponent.sol
packages/solecs/src/LibQuery.sol
packages/solecs/src/MapSet.sol
packages/solecs/src/Ownable.sol
packages/solecs/src/OwnableWritable.sol
packages/solecs/src/OwnableWritableStorage.sol
packages/solecs/src/PayableSystem.sol
packages/solecs/src/Set.sol
packages/solecs/src/System.sol
packages/solecs/src/World.sol
packages/solecs/src/components/Uint256Component.sol
packages/solecs/src/interfaces/IComponent.sol
packages/solecs/src/interfaces/IERC165.sol
packages/solecs/src/interfaces/IERC173.sol
packages/solecs/src/interfaces/IOwnableWritable.sol
packages/solecs/src/interfaces/IPayableSystem.sol
packages/solecs/src/interfaces/ISystem.sol
packages/solecs/src/interfaces/IWorld.sol
packages/solecs/src/interfaces/Query.sol
packages/solecs/src/systems/RegisterSystem.sol
packages/solecs/tasks/compile.ts
packages/std-contracts/remappings.txt
packages/std-contracts/tasks/compile.ts
yarn.lock

Closes #245
* Use Ownable from @solidstate/contracts to implement IERC173, also use solidstate for IERC165
* Add IOwnableWritable and OwnableWritable on top of IERC173 and Ownable, to generalize authorization which was previously built into components
* Add Subsystem, which is a System, but uses OwnableWritable instead of Ownable
* Fix some import formatting since I was going through the whole package anyways
Edit: removed paragraph about subsystems since they're moved to #268

refactor(solecs): use @solidstate Ownable, add OwnableWritable, fix some import formatting

---

packages/std-contracts/src/components/SystemCallbackBareComponent.sol
packages/std-contracts/src/components/SystemCallbackComponent.sol
packages/std-contracts/src/test/SystemCallbackComponent.t.sol
packages/std-contracts/src/test/TestSystem.sol

FunctionComponent:
- Stores an arbitrary contract's address and a selector to one of its functions.
- You use `staticcallFunctionSelector` with your own arguments to that function.
- If the contract address is a system, an outdated version of it could get called, which could make maintaining a FunctionComponent troublesome.
SystemCallbackComponent:
- Stores a system ID and the arguments for that specific system's execute (note how no address is stored).
- You use `executeSystemCallback` with your own `IWorld` address. You do NOT use your own arguments (although technically you could, but that seems like an antipattern).
- Maintaining a SystemCallbackComponent gets troublesome only if the system's arguments change. Otherwise the system's logic can change seamlessly.
- You do not need to …

feat(std-contracts): add SystemCallbackComponent

---

packages/cli/src/utils/build.ts

i thought this was fixed at some point, but it's still happening for me. lmk if there is a better way to fix this.

fix(cli): do not copy System test ABIs during build 🧱

---

packages/cli/src/commands/deploy.ts

this became very annoying once we switched to using actual gas fees on the testnet. defaults to dev=true.

feat(cli): add deploy option to specify whether dev flag should be appended to client url

---

packages/network/src/createNetwork.ts
packages/network/src/createProvider.ts
packages/network/src/createTxQueue.ts
packages/network/src/types.ts
packages/std-client/src/setup/setupMUDNetwork.ts

Support for external wallets to mud. 
Allows users to pass in `externalProvider` (which is an ethers.js `ExternalProvider`) to the network config and then use the associated signer for txs.

feat(network): add support for external wallets (eg MetaMask)

---

README.md
guides/getting_started.md

`npx mud` doesn't actually work and folks have been discovering this

docs: fix npx command to create new mud project

---

packages/cli/src/utils/deploy.ts

i ran into this issue recently when fetching the gas price from our newly spun up test chain. also have anecdotal evidence that it happened to another MUD developer.

fix(cli): round gas price to nearest integer (it cannot handle decimals)

---

guides/game_development/animations_from_system_calls.md
guides/game_development/index.yml
package.json
retype.yml

- adds command (`yarn docs:dev`) for running docs locally
- changes default port to one that doesn't conflict with MacOS
- small (opinionated) tweaks to system call stream article (mostly changing casing)

docs: system call tweaks, dev improvements

---

packages/cli/src/contracts/LibDeploy.ejs
packages/cli/src/utils/codegen.ts

deploy.json already has "init" for systems.
But systems are contracts. Scripts are best run through libraries.
Example:
An expensive `addItem` function, which adds a game item prototype with all its properties. Say it costs 1mil gas per item. I have an initializer which adds 100 of those. 100mil gas exceeds the limit.
- If the 100 adds are in a system contract, it will revert. And making a bunch of wrapper init systems is a really bad idea.
- If the 100 adds are in a library, `forge script` can at least split it into several transactions. But also the real contract calls (component sets) use only a small portion of all that gas.
(this is a simplified edge case, my real use case is unfinished and more convoluted, but similar enough, e.g. …

feat(cli): add initialization libs to deploy

---

packages/cli/foundry.toml
packages/noise/foundry.toml
packages/solecs/foundry.toml
packages/std-contracts/foundry.toml

pinning solc to 0.8.13 for now to fix failing github action

build: pin solc version to 0.8.13

---

guides/getting_started.md
packages/cli/src/commands/deploy-contracts.ts
packages/cli/src/contracts/LibDeploy.ejs
packages/cli/src/utils/codegen.ts

fix(cli): rename libs to initializers, always use init as func

---

packages/network/src/createBlockNumberStream.ts

Currently network waits for a new block, which means I must use a tickchain locally.
Perhaps it also delays loading for production chains with slowish block times, haven't tested that.
This fix uses the current block number if the rpc returns it before a new block. I may have missed some downstream problems, but it seems like a harmless change

fix(network): use current block number while waiting for new blocks

---

packages/cli/src/commands/deploy-contracts.ts
packages/cli/src/utils/build.ts
packages/cli/src/utils/deploy.ts

Fixes #376
This is just a quick fix and doesn't solve the issue of logs being generally hard to read.
`generateAndDeploy` caught and ignored all errors, whereas it should only ignore them during HMR. (has been bothering me for a while)
`execLog` is also kind of a mess, it'd be best to eventually replace it with `execa` in other places too

fix(cli): exit if generateDeploy fails in deploy-contracts setup

---

packages/store/gas-report.txt
packages/store/src/StoreCore.sol
packages/store/test/StoreCore.t.sol

We were emitting events at the end of `StoreCore`'s `setRecord`, `setField` and `deleteRecord` methods, but an early return if there is no dynamic data prevented the events from being emitted for schemas with only static fields.
Also added some test cases to make sure we're emitting the expected events.

fix(store): emit store events before early return

---

packages/store/gas-report.txt
packages/store/src/Storage.sol
packages/store/src/Utils.sol

Replaced #378
> why are we adding the buffer's length to the buffer's pointer to get the memory pointer?
I no longer use appendUnchecked in Storage. That's a temporary hack so that the new Storage works before I finish the Buffer overhaul

feat(store): add storage optimizations

---

packages/store/gas-report.txt
packages/store/src/StoreCore.sol
packages/store/src/Types.sol
packages/store/test/StoreCore.t.sol

We weren't emitting a `MudStoreSetRecord` event when storing to the schema table, because the schema table doesn't use the usual `setRecord` path of setting data (because that one requires the table to have a schema, so it's a circular dependency). 
Also, we weren't registering the SchemaTable's schema in the SchemaTable. Not too important, but good for completeness.

fix(store): emit MudStoreSetRecord event when registering a new schema, register SchemaTable's schema

---

.github/workflows/docs.yml
.github/workflows/test.yml

We tried the merge queue, but it spins forever because we need `merge_group` events for our required CI steps.

build(ci): enable merge queue

---

packages/react/package.json
packages/react/src/useEntityQuery.test.ts
packages/react/src/useEntityQuery.ts
packages/react/src/utils/useDeepMemo.ts

closes #379
Adds better memoizing to `useEntityQuery` arguments so that you don't have to memoize values passed into it (which is currently causing an ~infinite loop if you're not careful).

refactor(react): improve useEntityQuery usage/rendering

---

packages/cli/src/contracts/LibDeploy.ejs

Followup to #364
only thought of this after starting to use initializers - like with tests, they could use SystemStorage, it just needs to be initialized somewhere

feat(cli): allow initializers to utilize SystemStorage

---

packages/services/package.json
yarn.lock

This is a fix for the root cause of a confusing issue with vite (although since it can be hard to reproduce I'm not completely sure this PR solves it).
It's currently addressed via e.g. exclude/include in https://github.com/latticexyz/mud-template-react/blob/main/packages/client/vite.config.ts , or installing nice-grpc (and maybe other packages) can do the trick
Also it doesn't show up for locally linked mud
The issue seems to stem from a deeper issue with ts-proto itself, see https://github.com/stephenh/ts-proto/issues/147

build(services): add explicit typescript dependencies

---

packages/store/test/Storage.t.sol

Another option would be to hash the fuzzy slot
Also removed keccaks in that assert, they obscure logs and aren't necessary

test(store): avoid fuzzy storage slot clash with test assertion failure flag

---

packages/network/src/createFaucetService.ts

Hopefully fixes the bug created (revealed?) by #328
Seems related to https://github.com/microsoft/TypeScript/issues/42873

fix(network): add explicit return type to createFaucetService

---

packages/store/src/IStore.sol
packages/store/src/StoreCore.sol
packages/store/test/StoreCore.t.sol

Nothing else is prefixed, so renaming these for consistency.

refactor(store): rename events

---

retype.yml

The previous invite link lands in #team and apparently errs for some people. Created a new one (that does not expire) to land in #welcome

chore: update discord invite to land in #welcome instead of #team

---

packages/cli/src/commands/call-system.ts
packages/cli/src/commands/deploy-contracts.ts
packages/cli/src/commands/system-types.ts
packages/cli/src/commands/test.ts
packages/cli/src/commands/trace.ts
packages/cli/src/utils/build.ts
packages/cli/src/utils/constants.ts
packages/cli/src/utils/forgeConfig.ts
packages/cli/src/utils/types.ts

Adds forge config getter; and replaces all hardcoded instances of `src`, `test`, `out` with getDir functions.
I also add some constants for `systems` and `components` dirs to the top of the files where they're used.
`inputDir` is removed from systemTypes because it only allows overriding the hardcoded `src`, which now isn't hardcoded (overriding `systems` directory wouldn't work well, and isn't useful for just 1 command).
`src` and `out` changes are seamless, but `test` changes require users to:
- either add `test = src/test` to `foundry.toml`
- or move their `src/test` to `test`

feat(cli): use forge config for paths to src, test, out

---

packages/create-mud/package.json
yarn.lock

Attempting to `yarn create mud` with the current version fails due to an unbuilt git dependency (fork of create-create-app):
```
success Installed "create-mud@1.35.0" with binaries:
- create-mud
[#############################################################################################################################################] 396/396node:internal/modules/cjs/loader:401
throw err;
^
Error: Cannot find module '/Users/kevin/.config/yarn/global/node_modules/create-mud/node_modules/create-create-app/lib/index.js'. Please verify that the package.json has a valid "main" entry
at tryPackage (node:internal/modules/cjs/loader:393:19)
at Function.Module._findPath (node:internal/modules/cjs/loader:606:18)
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:971:27)
at …
```

fix(create-mud): attempt to fix build/install issues

---

packages/cli/package.json
packages/ecs-browser/package.json
packages/network/package.json
packages/noise/package.json
packages/phaserx/package.json
packages/react/package.json
packages/recs/package.json
packages/std-client/package.json

lerna doesn't seem to be updating mud versions within `peerDependencies` and I noticed a bunch were out of date
also reverts the bad release that changed the `main` here: https://github.com/latticexyz/mud/commit/2e513a481c3588ea85254be6b042ddb6d9c32c5e

fix: package entry points, peer dep versions

---

packages/create-mud/templates/react/packages/client/src/App.tsx
packages/create-mud/templates/react/packages/client/src/index.tsx
packages/network/src/workers/SyncWorker.spec.ts
packages/network/src/workers/SyncWorker.ts
packages/network/src/workers/constants.ts
packages/solecs/src/SingletonID.sol
packages/std-client/src/utils.ts
tutorials/emojimon/step-4.md

refactor(network): rename GodID to SingletonID
feat(solecs): add SingletonID
We currently have an implicit expectation of a "god ID" being present for emitting loading state data, etc. This is also a generally useful pattern for defining global state (e.g. game config).
I don't love the "god ID" name so I am also renaming it to "singleton ID" for clarity.
(I made these changes in the emojimon tutorial already, so porting upstream for cleanliness!)

refactor(network): rename GodID to SingletonID

---

packages/cli/src/commands/create.ts

Deprecates `mud create` cli command in favor of `yarn create mud`. This is a "bridge" commit that deprecates the command but still allows it to run (by using `yarn create mud` under the hood). In a future version, we should remove this command all together. Happy to do this sooner if you think that's warranted.
Also deprecated+archived the template repos:
https://github.com/latticexyz/mud-template-minimal
https://github.com/latticexyz/mud-template-react

feat(cli): deprecate create command

---

packages/cli/src/commands/deploy-contracts.ts

Certain OS/platforms can't open URL automatically, so we should at least log it in the console to make it easier to access.

feat(cli): log client world URL

---

packages/react/src/useEntityQuery.test.ts
packages/react/src/useEntityQuery.ts

I have 2 use-cases for this:
1. Getting values from 2+ components using a custom query (e.g. `HasValue` for one, `Has` for the other)
2. Complex chain of methods that use different components to resolve foreign keys. These methods are reused in different hooks with different nesting depths. The only way I see to do this semi-cleanly is to use non-hook getters that call each other while specifying which components they depend on, and then make it all re-render based on any changes to that array of components
1 can maybe be also solved with a more generalized `getComponentValues`
2 would need some deep foreign key support in recs or something, and even then it may not solve everything

feat(react): option for useEntityQuery to re-render on value changes

---

packages/cli/src/config/index.ts
packages/cli/src/config/loadStoreConfig.ts
packages/cli/src/config/parseStoreConfig.test-d.ts
packages/cli/src/config/parseStoreConfig.ts
packages/cli/src/index.ts
packages/cli/src/render-table/renderTablesFromConfig.ts

Splitting out "parse" from "load" to avoid `path` import issues on client in prep for https://github.com/latticexyz/mud/pull/415

refactor(cli): separate parseStoreConfig from loadStoreConfig

---

packages/store/gas-report.txt
packages/store/src/IStore.sol
packages/store/src/StoreCore.sol
packages/store/src/StoreSwitch.sol
packages/store/src/StoreView.sol
packages/store/test/StoreCore.t.sol
packages/world/src/World.sol
packages/world/src/schemas/AddressArray.sol
packages/world/test/World.t.sol

Intentionally not adding a new event, but the method's logic accounts for it being added in the future with minimal changes to StoreCore and no changes to World etc (so it could be mostly a network PR)
Notably this allows pushing multiple items at once
No validity checks though (same as setField, they should be added in one separate refactor I think)
`_verifiedTableRouteId`, `_expectRouteAccessDenied` and `_initRouteTableKey`: 
I basically want to reduce code repetition in World but I don't want to complicate this PR by refactoring things unrelated to `pushToStore` yet
setItem and pop could happen in the future, but rn I just need push for proper autogen

feat: add pushToField to Store and World

---

packages/world/gas-report.txt
packages/world/src/modules/reversemapping/ReverseMappingHook.sol
packages/world/src/modules/reversemapping/ReverseMappingModule.sol
packages/world/src/modules/reversemapping/constants.sol
packages/world/src/modules/reversemapping/getKeysWithValue.sol
packages/world/src/modules/reversemapping/getTargetTableSelector.sol
packages/world/test/ReverseMappingModule.t.sol

This PR removes the need to install a different ReverseMappingHook for each table the hook is registered by inferring the target table id from the source table id. This also removes the need for users to manually define the target table id in the mud config, and enables a `getKeysWithValue` function that doesn't require users to keep track of mapping between source table and target table (or require us to do a storage access to do the mapping).

feat(world): ReverseMapping: infer target table id from source table id, add getKeysWithValue util

---

packages/cli/src/config/index.ts
packages/cli/src/config/parseStoreConfig.ts
packages/cli/src/config/validation.ts
packages/cli/src/utils/typeUtils.ts

This mostly just improves typehints, in particular the specific field/key with an invalid type is now highlighted, instead of a vague ts error about enums not having correct keys.
The improvements also allow to easily plug in support for static arrays, so that they just work without defining them as user types (this PR does not actually add support for static arrays)

feat(cli): improve store config typehints, prepare for static array support

---

packages/cli/src/index.ts

Removed in #517 but didn't realize we needed this in https://github.com/latticexyz/v2sandbox/pull/7

fix(cli): add back in resolveTableId export for use with mudConfig

---

packages/cli/src/commands/deploy-v2.ts
packages/cli/src/constants.ts
packages/cli/src/index.ts
packages/cli/src/utils/deploy-v2.ts
packages/cli/src/utils/getChainId.ts

- namespace deploy output by chain id
- change the naming schema for deploy output (just `latest.json` and `<timestamp>.json` instead of prefixed)
- remove `rpc` from the deployment json
Corresponding v2sandbox PR: https://github.com/latticexyz/v2sandbox/pull/10

feat(cli): namespace deploy output by chain id

---

packages/cli/src/commands/deploy-v2.ts
packages/cli/src/config/world/parseWorldConfig.ts
packages/cli/src/config/world/userTypes.ts

Just a small usability improvement ("deployment info" seemed like an internal name, not a great external one). Also defaults to `./deploys` since throwing a bunch of JSON in the cwd isn't a very nice thing to do - and containing it in a dir makes it easier to clean up, gitignore, etc.

feat(cli): rename deploymentInfoDirectory to deploysDirectory, default to ./deploys

---

packages/network/src/createSyncWorker.ts
packages/network/src/workers/SyncWorker.ts
packages/std-client/src/setup/setupMUDNetwork.ts

Adds an option to `createSyncWorker` (and `setupMUDNetwork`) to instantiate the "SyncWorker" in the main thread instead of a worker thread.

feat(network): add option to sync in main thread instead of worker

---

packages/store/.gitignore
packages/store/.npmignore
packages/store/package.json
packages/store/tsup.config.js
packages/world/.gitignore
packages/world/.npmignore
packages/world/package.json
packages/world/tsup.config.js
yarn.lock

We're using `@latticexyz/store/mud.config.mjs` and `@latticexyz/store/mud.config.mjs`, but those files didn't exist in the released version of the packages.
This PR adds a build step for `mud.config.mts` and configures the store/world's `package.json` to expose the configs as `@latticexyz/store/mud.config.mjs` / `@latticexyz/world/mud.config.mjs`
I extensively tested locally with `yalc` to verify this approach works and fixes the build issues in https://github.com/latticexyz/v2sandbox/pull/12

build(store/world): release mud.config.mjs from store and world

---

package.json

small change to the command used in the npm canary action to publish canaries at `2.0.0-alpha.x` instead of `1.41.1-alpha.x`

ci: release canaries as premajor

---

.github/workflows/npm.yml

The version number of a canary release comes from git describe, which counts the amount of commits from the last tag.
Without fetch-depth: 0 only a single commit is fetched, for the ref/SHA that triggered the workflow, so the canary version is always 0. See https://github.com/actions/checkout

ci: correctly update canary version number

---

package.json
packages/network/package.json
packages/network/src/createFastTxExecutor.ts
packages/network/src/index.ts

Moving some of the magic of `createTxQueue` into a simpler helper function. Totally optional for consumers, but here are some quick benchmarks for sending tx on the testnet:
With manual gas limit:
Without manual gas limit:
Usually consumers in MUD don't have to await the result but only sending the transaction, so the first of the two numbers is more relevant
Corresponding v2sandbox branch: https://github.com/latticexyz/v2sandbox/pull/20

feat(network): add fastTxExecute util

---

packages/cli/src/commands/deploy-v2.ts
packages/cli/src/commands/index.ts
packages/cli/src/commands/test-v2.ts
packages/cli/src/utils/foundry.ts
packages/std-contracts/src/test/MudV2Test.t.sol

* This PR adds the `mud test-v2` cli command and corresponding `MudV2Test.t.sol` base class
* Without arguments, the command uses the project's mud config to create a deployment on a fresh anvil node, and then executes fork test on that fresh deployment
* With a `--worldAddress` argument, the deployment is skipped and the fork test are executed on the provided world address (and rpc url from the `foundry.toml`)
Corresponding v2sandbox PR: https://github.com/latticexyz/v2sandbox/pull/24

feat(cli): add `mud test-v2` command

---

packages/network/src/v2/mode/syncTablesFromMode.ts

- `decodeAbiParameters` returns an array, but we're interested in the individual value

fix(network): fix mode decoding

---

packages/cli/package.json
packages/cli/src/config/loadConfig.ts
packages/cli/src/mud.ts
packages/cli/src/utils/errors.ts
yarn.lock

* Remove the `ts-node` requirement from the mud cli by loading config files via esbuild

fix(cli): use esbuild to load mud config

---

packages/cli/package.json
packages/cli/src/commands/deprecated/index.ts
packages/cli/src/commands/index.ts
packages/cli/src/mud.ts
packages/cli/src/mud2.ts
packages/cli/tsup.config.js

- windows users are reporting errors when using the CLI that are caused by deprecated v1 commands
- This PR adds a `mud2` cli entry point that omits all v1 commands from the binary
- This should fix the windows issues, and is a transition step towards sunsetting the v1 commands (the next step could be to rename `mud -> mud1` and `mud2 -> mud`)

feat(cli): add mud2 cli entrypoint with only v2 commands

---

packages/world/gas-report.txt
packages/world/src/modules/keyswithvalue/KeysWithValueHook.sol
packages/world/src/modules/keyswithvalue/KeysWithValueModule.sol

- Before `KeysWithValueHook` required tables to have a single key
- With this PR also tables with composite keys are supported, but only the first key will be indexed

feat(world): allow KeysWithValueModule on tables with composite keys

---

packages/cli/contracts/src/tables/Dynamics.sol
packages/cli/contracts/src/tables/Singleton.sol
packages/cli/contracts/src/tables/Statics.sol
packages/cli/contracts/test/Tablegen.t.sol
packages/cli/src/render-solidity/record.ts
packages/store/gas-report.txt
packages/store/src/tables/Mixed.sol
packages/store/src/tables/StoreMetadata.sol

fixes https://github.com/latticexyz/mud/issues/560
replaces #564 
the gist of the issue was: in `getRecord` when dynamic fields are empty, Store trims their 32-byte length word, so the blob is only static data.
`tablegen` didn't account for the trimming, and `Slice`'s sanity check detected the invalid subslice [64:64] on a blob of length 32
(an empty subslice is fine, what's invalid is that the indexes exceed the length)

fix(cli): account for getRecord's trimming

---

packages/world/src/modules/core/CoreModule.sol

- The World didn't have access to the root namespace. This doesn't matter for situations where the World writes to its own storage, but it matters for root systems who want to call other root systems via the World. Since root systems are delegatecalled from the World, `address(this)` in the System is the world address. If these systems try to call a method on the World, it's considered an external call, so access control checks apply, and fail if the World doesn't have access to the root namespace.

fix(world): give World contract access to root namespace

---

packages/cli/git-install.sh
packages/cli/package.json
packages/noise/git-install.sh
packages/noise/package.json
packages/schema-type/git-install.sh
packages/schema-type/package.json
packages/solecs/git-install.sh
packages/solecs/package.json
packages/std-contracts/git-install.sh
packages/std-contracts/package.json
packages/store/git-install.sh
packages/store/package.json
packages/world/git-install.sh
packages/world/package.json

We don't really use this and you can `yarn add [dep@git-url]` easy enough

build: remove git-install helper

---

.gitignore
package.json
yarn.lock

attempting to fix issues around partially-successful releases not being able to run release step again (both in CI and locally, when there are errors like rate limiting, etc.), see https://github.com/lerna/lerna/pull/3513
not sure how to test this yet
prereq for #511 (which adds pnpm support in later versions) so we don't have to change our release pipeline during pnpm migration

build: bump lerna to 6.6.1

---

packages/noise/package.json

keep coming across this when adjusting build stuff and noise package fails but leaves a bunch of `package.json.bk` files around

build(noise): always restore package.json after build

---

packages/cli/src/commands/deploy-v2.ts
packages/cli/src/utils/deploy-v2.ts

* Allow passing a `worldAddress` argument to the `deploy-v2` cli to deploy to an existing World
* Allow passing an explicit `srcDir` argument to the `deploy-v2` cli to override the default foundry config's src dir

feat(cli): allow passing world address and src dir

---

packages/world/gas-report.json
packages/world/src/AccessControl.sol
packages/world/src/World.sol
packages/world/src/modules/core/CoreModule.sol
packages/world/src/modules/registration/RegistrationSystem.sol
packages/world/test/World.t.sol

- Calls that require `AccessControl.requireOwner` (eg. `registerRootFunctionSelector` or `registerSystem`) were failing if called externally by the World itself, because the World is not the owner of any `ROOT_FILE`.
- Similarly calls that require `AccessControl.requireAccess` were failing if called externally by the World for the same reason.
- However, the World can always call these methods internally, so it should also be allowed for the World to call them externally (eg. when the World is delegatecalling a `RootModule` to install it, which then tries to install Systems in the World by calling `registerSystem` _as the World_)
- This makes #575 obsolete (since World has access to every namespace now)

fix(world): allow world to access own functions via external calls

---

packages/cli/src/render-solidity/common.ts
packages/cli/src/render-solidity/tableOptions.ts
packages/cli/src/render-solidity/types.ts
packages/cli/src/render-solidity/worldgen.ts
packages/cli/src/render-ts/recsV1TableOptions.ts
packages/cli/src/render-ts/renderRecsV1Tables.ts
packages/cli/src/render-ts/types.ts
packages/cli/src/utils/deploy-v2.ts
packages/config/src/store/parseStoreConfig.ts
packages/config/src/world/parseWorldConfig.ts
packages/config/src/world/resolveWorldConfig.ts
packages/config/src/world/userTypes.ts
packages/std-client/src/mud-definitions/world/contractComponents.ts
packages/world/gas-report.json
packages/world/mud.config.mts
packages/world/src/AccessControl.sol
packages/world/src/ResourceSelector.sol
packages/world/src/World.sol
packages/world/src/constants.sol
packages/world/src/interfaces/IRegistrationSystem.sol
packages/world/src/interfaces/IWorldCore.sol
packages/world/src/modules/keyswithvalue/KeysWithValueModule.sol
packages/world/src/modules/registration/RegistrationSystem.sol
packages/world/src/modules/utils/getTargetTableSelector.sol
packages/world/src/tables/FunctionSelectors.sol
packages/world/test/AccessControl.t.sol
packages/world/test/KeysWithValueModule.t.sol
packages/world/test/World.t.sol

- Renames `fileSelector` to `name`
- Context: in #462 we switched to an access control mechanism based on "namespaces". Every resource that is registered in the World (tables, systems) is identified via a `bytes32` resource selector, which consists of two parts: a `bytes16` "namespace" and a `bytes16` "fileSelector". This "fileSelector" is just the name of the resource within the namespace, and calling it "fileSelector" was very confusing for people, so in this PR we're changing it to "name".

refactor: rename `fileSelector` to `name`

---

packages/std-client/src/setup/setupMUDNetwork.ts
packages/std-client/src/setup/setupMUDV2Network.ts
packages/std-client/src/setup/types.ts

* `devMode` was used to both set gas price to 0 (to use dev chains with 0 gas) and to disable the cache
* Therefore using the `devMode` flag to disable the cache in a production deployment didn't work, because in this situation the side effect of setting gas price to 0 was unintended.
* This PR deprecates the `devMode` flag and adds a new `disableCache` flag to be used to disable the cache. (We don't remove the `devMode` flag yet to avoid a breaking change in MUD v1, since the config is shared by both v1 and v2 network setup functions)
* To send transactions with gas price 0 during development, the `fastTxExecute` function should be used instead of `txQueue` (it's much leaner and has logic to not set a gas price / priority fee if the chain's base fee is 0)

refactor(std-client): deprecate devMode, add disableCache flag instead

---

packages/create-mud/templates/minimal/packages/contracts/package.json
packages/create-mud/templates/react/packages/contracts/package.json
packages/network/package.json
packages/noise/package.json
packages/solecs/package.json
packages/store/package.json
packages/world/package.json
pnpm-lock.yaml

We no longer need ts-node at runtime like we did before (this was either a cli thing or a config thing), we can remove ts-node from most packages.
That leaves only a couple that actually used it:
- store for codegen, but this was easy to swap with tsx (used elsewhere)
- noise for `test:hardhat` but the command wasn't working or in use anyway, so I just reduced it to what it _should_ be assuming hardhat adds TS support
- we could also just migrate the test cases over to foundry
Helps a bit with #612

build: remove ts-node usages

---

.github/actions/setup/action.yml
package.json
packages/cli/package.json
packages/config/package.json
packages/create-mud/package.json
packages/ecs-browser/package.json
packages/network/package.json
packages/noise/package.json
packages/phaserx/package.json
packages/react/package.json
packages/recs/package.json
packages/schema-type/package.json
packages/services/package.json
packages/solecs/package.json
packages/std-client/package.json
packages/std-contracts/package.json
packages/store/package.json
packages/utils/package.json
packages/world/package.json

Speed up installs by removing `prepare`. For now we'll have to run `pnpm build` before using (this happened implicitly after install with `prepare`).
Pulled out of https://github.com/latticexyz/mud/pull/620 to reduce scope of that PR

build: remove prepare in favor of build script

---

packages/cli/src/commands/set-version.ts

* Adds a `--link` param to the `mud set-version` cli script, which takes a relative path from the current project root to the root directory of a local MUD clone, and replaces all MUD dependencies with locally linked versions. It automatically creates a backup file with the previous (non-linked) MUD versions, which can be restored with the `mud set-version --restore`
Usage (from root of any MUD project)
1. Link to local MUD installation
`mud set-version --link <path/to/mud>`
2. Revert to original non-linked versions:
`mud set-version --restore`

feat(cli): add local linking to mud set-version

---

package.json

Our canary release pipeline assumed the next release would be a major version, so when we did a manual minor release, the alpha counter reset:
In ~30 main commits, this will conflict with previously released alphas.
We'll have probably lots of minor/patch releases until 2.0 (and after), so let's switch canary/alpha releases to use prepatch. It won't exactly follow semver but at least we won't have to fight this issue every manual release.

build: update canary preid

---

packages/create-mud/scripts/copy-templates.sh

Thanks GPT-4 for helping with the original code and fixing this bug.
The script now will 1) output more information so we can debug this easier in the future and 2) exit with a non-zero code if any linked dependencies are found after running the replacement logic.
Fixes #647

fix(create-mud): replace linked deps

---

packages/cli/vite.config.ts
packages/common/vite.config.ts
packages/config/vite.config.ts
packages/store/package.json
packages/store/vite.config.ts
packages/world/package.json
packages/world/vite.config.ts

- vite config changes are about minify from https://github.com/latticexyz/mud/pull/640#discussion_r1172766764 and some minor normalization
- tsx requires to also bundle solidity parser, which ups `common`'s bundle size from ~50kB to ~1000kB. Probably not much of an issue since it's nodeside. Also moved `build:js` back to the end.
- Tried to remove `modules.d.ts` with prettier plugin stuff, but they're still required in the downstream packages unfortunately

refactor: normalize vite configs, use tsx for store/world scripts

---

packages/cli/src/utils/deploy-v2.ts

Previously, function arguments that were structs (as opposed to base solidity types) were not parsed correctly by the Mud v2 deploy script. For example, a struct Coord (int32 x, int32 y) would parse as `tuple` instead of `(int32,int32)`.
This change parses structs (& nested structs) in function args

fix(cli): parse struct function arguments

---

packages/store/gas-report.json
packages/store/src/IStore.sol
packages/store/src/Storage.sol
packages/store/src/StoreCore.sol
packages/store/src/StoreReadWithStubs.sol
packages/store/src/StoreSwitch.sol
packages/store/test/StoreCoreDynamicUpdate.t.sol
packages/world/gas-report.json
packages/world/src/World.sol
packages/world/src/interfaces/IWorldKernel.sol
packages/world/test/World.t.sol
packages/world/test/WorldDynamicUpdate.t.sol

Just changing Store/World API, not tablegen, to avoid conflicts there. Can be another PR a bit later, or wait and update this one.
After the tablegen part this should unblock https://github.com/latticexyz/mud/pull/583 (unless @yonadaaa also needs a partial `getItem` method)

feat(store,world): add popFromField

---

docs/package.json
docs/pnpm-lock.yaml

At some point `"private": true` became `"private": "true"` and whether or not a package is private means that pnpm seems to do different things when installing, running scripts, etc.
When we move back to `true` boolean (rather than `"true"` string), this issue becomes apparent in Vercel (see the failed preview deploy after the first commit in this PR).
To work around this, I've added a blank `pnpm-workspace.yaml` to the `docs` directory so that pnpm treats it as its own workspace (with no sub-packages) and installs work properly again.
I also had to add missing dev deps (since they were inferred from the root originally).
I opted to take this path instead of including this in the root workspace because I encountered issues when trying to figure out the build pipelines, especially for …

docs: fix build

---

.github/workflows/pr.yml

adds linter for PR titles so we can require this workflow step before merging
prerequisite for https://github.com/latticexyz/mud/issues/683
(note that this won't run in this PR with `pull_request_target`, only on PRs from here on out, using `main` as the definition for this workflow, see https://github.com/amannn/action-semantic-pull-request#event-triggers)

ci: add linter for PR title

---

.github/actions/setup/action.yml

~3 mins of CI time is spent setting up `solc` with the previous step
trying to see if just using `forge build` helps here
see https://github.com/foundry-rs/foundry/issues/4736

ci: speed up solc setup

---

README.md

Adding a missing external dependency required to build the `services` package (protobuf) to the root readme

docs: add protobuf instructions to readme

---

.github/workflows/examples.yml
examples/minimal/packages/contracts/types/ethers-contracts/IWorld.ts
examples/minimal/packages/contracts/types/ethers-contracts/factories/IWorld__factory.ts
packages/world/src/World.sol
packages/world/src/interfaces/IWorldKernel.sol
packages/world/test/World.t.sol

Adds an event to world deploy so we don't need to keep track of deploy block number, we can just grab it from the RPC by looking for this event.
see #680

feat(world): emit event on deploy

---

packages/world/gas-report.json
packages/world/src/modules/keyswithvalue/KeysWithValueHook.sol

@holic this will tidy the dev UI by removing redundant records.
We could also take this chance to refactor the internals of `KeysWithValue` to be like `KeysInTable` (ie. no `tableIdArgument`, removing unbounded array filter). But I don't think it is worth the time investment with MUD2 still in flux.

feat(world): delete record for empty keysWithValue array

---

packages/common/src/codegen/utils/contractToInterface.ts
packages/world/ts/library/render-solidity/renderSystemInterface.ts
packages/world/ts/library/render-solidity/types.ts
packages/world/ts/library/render-solidity/worldgen.ts

fixes https://github.com/latticexyz/mud/issues/757
only errors, events are not only an antipattern but wouldn't even work for any non-root system, since those aren't delegatecalled

feat(common,world): include errors in worldgen's system interfaces

---

README.md
docs/pages/index.mdx

closes #772 
closes #778 
mud v1 CLI is still using yarn, and I mistakenly updated this in docs during the pnpm migration, which causes the create-mud package to use pnpm during template install (fails due to a yarn/lerna monorepo)
will address in #775

docs: `yarn create mud` for now

---

packages/dev-tools/.npmignore

whoops, forgot an `.npmignore` file and so `dist` wasn't getting published

fix(dev-tools): publish dist

---

packages/ecs-browser/package.json
packages/ecs-browser/tsconfig.json
packages/ecs-browser/tsup.config.js
pnpm-lock.yaml

related to https://github.com/latticexyz/mud/issues/411
I did this by going through each dep, looking at import usages, and deciding if it should be a regular dep (if used within the app bundle) or dev dep (if only used in tests, type checking, etc.). I also removed a couple extraneous deps.

build(ecs-browser): clean up deps

---

packages/ecs-browser/.npmignore
packages/phaserx/.npmignore
packages/react/.npmignore
packages/recs/.npmignore
packages/utils/.npmignore

We changed the `types` entry in `package.json` to point to the ts source files, but forgot to release the source files to npm

build: include src directory in npm release

---

packages/dev-tools/src/mount.tsx

Attempting to resolve this issue:
I think I could have changed these lines to something like
```ts
const ReactDOM = (await import('react-dom/client')).default;
```
But I wasn't as confident in that approach. TS tells me both the current approach and these alternatives would work, so I'm not sure what's up. I don't use these style imports often, so I'm not sure of the edge cases.
It might also mean that we need to force these deps to be bundled?

fix(dev-tools): change async import approach

---

packages/dev-tools/src/mount.tsx
packages/dev-tools/tsup.config.ts

tsup by default [doesn't bundle deps](https://tsup.egoist.dev/#excluding-packages):
> By default tsup bundles all import-ed modules but dependencies and peerDependencies in your packages.json are always excluded
So when we use this package in a non-react project, it will fail to mount because of missing react deps.
We could declare these deps as peer deps, but we've had bad experiences with that, and it feels awkward for non-react projects to have to have react deps to use the dev tools.
We're gonna try bundling react deps, even though it may cause issues if multiple versions of react are detected on the page. We'll address that as it comes up.

feat(dev-tools): bundle react deps

---

package.json

I noticed we've all run into this a couple of times where CI complains. This should now be automatic on commit!

chore: sort package.json in lint-staged

---

packages/common/package.json

I noticed when creating a new project from a template using `pnpm create mud`, I wasn't getting a strongly typed config:
When I dug into the `mudConfig` reference, I noticed there was a broken/missing TS definition for our common package:
Building this package locally shows it's missing `src` files that we usually have in our packages and expect with our `typesVersions` definition:
I found that this is because the `files` definition here is taking precedence over `.npmignore` in `npm pack` and thus excluding `src`. By removing `files` definition and packing, I can see `src` files in there, so this should fix it.

fix(common): publish source files for types

---

packages/store/gas-report.json
packages/store/test/StoreCoreGas.t.sol
packages/store/test/StoreMock.sol

Fixes #814 
* Integrates the new `expectEmit` behavior introduced in https://github.com/foundry-rs/foundry/pull/4920 by calling functions on a wrapper contract (`IStore(this)`) instead of the library directly (`StoreCore`) to trigger a `CALL`.
* Moves the gas reports to a separate test which still uses `StoreCore`, since calling the methods on a wrapper contract increases gas cost (but for the Store library gas reports we're interested in the library cost, not the contract call cost)

test(store): fix tests after foundry update, move gas reports to separate tests

---

packages/config/src/node/loadConfig.ts

* Loading the config on windows throws `ERR_UNSUPPORTED_ESM_URL_SCHEME` because the path doesn't begin with `file:///`. Note that appending `file:///` would throw an error on systems other than windows. This PR adds an OS check and appends `file:///` to the url in case it's `win32` (which is the case on all windows systems including 64 bit)

fix(config): use file url to load config on windows

---

packages/config/src/node/loadConfig.ts

* follow up to #849: turns out `esbuild` does't like a `file:///` url for entry points; this PR changes the `resolveConfigPath` function to only add the `file:///` prefix if needed (for node.js esm imports on windows)

fix(config): only normalize to file url for node imports

---

templates/react/package.json
templates/vanilla/package.json

closes #832
closes #831
- Windows users are reporting issues with `node-pty`. This PR adds a simple `dev` script relying on `pnpm recursive` to remove the need for `run-pty`/`node-pty`
- I think we should split the `dev:node` command from this dev script because if we have time I'd like to add a simple file watcher that runs codegen and redeploys the contracts when relevant files change, but we don't need to restart anvil for that.
- ~~we still have the `dev:pty` script which is recommended for everyone who doesn't have issues with `node-pty` because it makes it easier to see when things fail and why they fail~~ removing the `run-pty` dependency because it causes issues for the initial install
- this PR also adds a simple `mud:up` script to update mud to the latest canary
- this PR also …

feat(templates): make package scripts more windows friendly, add mud:up

---

packages/world/src/modules/core/tables/SystemHooks.sol

* #804 introduced a change in the size of `PackedCounter`, in #834 we added a new table and merged without accounting for the `PackedCounter` change merged shortly before it.
* This PR regenerates the `SystemHooks` table to account for the updated `PackedCounter` size

fix(world): regenerate SystemHooks table after PackedCounter change

---

packages/std-client/src/setup/setupMUDV2Network.ts

- the cache is indexed by world address, but the world address is often the same locally for different deployments when restarting the local development node. This causes very frequent issues; the current workaround is to append `cache=false` to the url
- this PR disables the local cache for development chains like anvil/hardhat (chainids 31337, 1337)

feat(std-client): disable cache on local chains

---

packages/dev-tools/src/actions/getTransactionResult.ts

By using the block number of the confirmed tx, a simulation for `increment` would show the value incrementing again (one more than what it should be) because the simulation happens at the end of the block (after the tx we're simulating)

fix(dev-tools): simulate result at last block

---

packages/config/src/node/loadConfig.ts

in `loadConfig.ts`:
Node.js caches dynamic imports, so without appending a cache breaking param like `?update={Date.now()}` the import always returns the same config if called multiple times in a single process, like the `dev-contracts` cli

fix(config): invalidate node js import cache

---

packages/dev-tools/package.json
packages/dev-tools/src/App.tsx
packages/dev-tools/src/mount.tsx
pnpm-lock.yaml

related to #777 
- returns `unmount` function from `mount` (inside an optional promise though, which isn't great)
- prevents mounting more than once
- attempts to fix layering (not sure why stacking contexts didn't help here)
- adjusts show/hide button colors to better suit both dark and light backgrounds
- keeps track of open/close state in localStorage (and consistent between browser tabs)

fix(dev-tools): various UX improvements

---

packages/cli/src/commands/dev-contracts.ts

see https://github.com/latticexyz/mud/issues/880
* add loading the config to the try/catch so the dev watcher doesn't die from typos in the mud config

fix(cli): catch config errors in dev watcher

---

packages/network/src/v2/mode/syncTablesFromMode.ts

`decodeSchema` expects the schema to be a single hex string of both value and key schema, but when syncing via MODE we were only passing in the value schema

fix(network): fix key schema sync from MODE

---

packages/common/src/codegen/render-solidity/common.ts
packages/common/src/codegen/utils/index.ts
packages/common/src/codegen/utils/posixPath.ts
packages/store/ts/library/render-solidity/renderTableIndex.ts
packages/store/ts/library/render-solidity/tableOptions.ts

fixes https://github.com/latticexyz/emojimon/issues/11
* Explicitly normalize a paths use a poxis separator (`/`) for when codegenerating solidity files, because `solc` expects posix paths but `path.join` uses the `win32` separator (`\`) if the user is on windows.
* Followup to #854 (we missed a path, this PR changes the location of normalization to the util rendering imports)

fix: render posix paths for solc

---

packages/create-mud/package.json
templates/threejs/packages/client/src/App.tsx

Fixes this issue: <img width="212" alt="CleanShot 2023-05-19 at 20 10 12@2x" src="https://github.com/latticexyz/mud/assets/89248902/770c5ebc-3c25-4a8c-a5ac-8a060a72ed4c">
It seems like `create-create-app` / `handlebars` is interpreting the `{{ height: 100vh }}` as an unknown handlebars option, this is a quick fix to resolve that

test(create-mud): add threejs template to create-mud tests

---

packages/cli/src/commands/dev-contracts.ts

* Prune the anvil cache before every start of `mud dev-contracts` to avoid issues with large cache files

fix(cli): clean anvil cache/logs at start of dev-contracts

---

packages/world/mud.config.ts
packages/world/src/modules/core/tables/SystemHooks.sol

the issue didn't show up in CI because config isn't typechecked in CI, zod silently ignores unknown keys, and keySchema is optional
that config override also doesn't actually change the default key type, just adds a name to it

fix(world): fix config keySchema

---

packages/world/tsconfig.json

this change also matches store's settings, and shouldn't affect build (which already includes mud.config anyways)

fix(world): include mud.config.ts in tsconfig so it gets typechecked

---

packages/services/go.mod
packages/services/go.sum
packages/services/pkg/mode/ingress/ingress.go

Changes to work block number subscription to work with OP testnet. Syncing via log parse worked before, but new block subscription / block number / header did not

chore(mode): make compatible with op testnet

---

packages/std-client/src/setup/utils.ts

- we were applying `nameKeys` to partial updates but still naming all keys, including those that weren't present in the partial update (their value was set to `undefined`, but the key was still created in the object). This caused the partial update logic in `storeCache` to fail, because now all keys were overridden, including those not present in the original partial update.
- this PR makes `nameKeys` only name keys present in the original object and skip non-existent ones

fix(std-client): skip non-existent record keys in nameKeys

---

packages/services/pkg/mode/ingress/handlers.go
packages/services/pkg/mode/keys.go
packages/services/pkg/mode/storecore/encoding.go
packages/services/pkg/mode/storecore/encoding_test.go

One TODO is figuring out how to best handle the mapping of fixed-size byte arrays that ABI decoding returns. Postgres really doesn't like these inserted like this, so we hex encode. But them being fixed sized means that the conversion from interface{} -> []byte doesn't work

feat(mode): abi decode keys instead of custom mud decoding

---

.github/actions/setup/action.yml

fixes the recent examples/templates CI failures
@Kooshaba this is based on ur comments from discord, do u have more context on the root issue?

build: use older foundry version in CI

---

packages/store/src/StoreCore.sol

found this when digging around for reasons I'm not seeing key schema for `mudstore.schema` records propagate to client
this doesn't fix anything but seems like it was meant to be `bytes32` to match the rest of table IDs?

fix(store): `tableId` should be bytes32

---

integration-sandbox/packages/client-vanilla/index.html
integration-sandbox/packages/contracts/test/index.test.ts

trying the original fix from https://github.com/latticexyz/mud/pull/991 (which at the end got replaced by `load` event, which unfortunately didn't fix flakiness)

fix(integration-sandbox): use custom setup status

---

packages/dev-tools/src/actions/TransactionSummary.tsx
packages/dev-tools/src/summary/AccountSummary.tsx
packages/dev-tools/src/summary/SummaryPage.tsx

see #777
- link to tx and block if block explorer is available (this has been handy while trying to debug optimistic rendering issues in testnet)
- rename "burner wallet" to "account" (since its not always gonna be a burner wallet)
- properly format balance (truncated to 4 decimals)
- shows mud version in bottom right of summary page

feat(dev-tools): various improvements

---

docs/pnpm-lock.yaml
examples/minimal/pnpm-lock.yaml
integration-sandbox/pnpm-lock.yaml
pnpm-lock.yaml

I just updated pnpm and recreated all the lockfiles
templates are unchanged because they already have 6.1 lockfileVersion apparently

build: update pnpm

---

packages/cli/src/utils/deployHandler.ts

Anvil is currently increasing the base fee to 1 after a MUD deploy, this temporary workaround is resetting the base fee to 0 after a deployment. We can remove this workaround once the issue is fixed upstream, see https://github.com/foundry-rs/foundry/issues/5161.

fix(cli): temporary workaround to reset anvil base fee to 0

---

.github/actions/setup/action.yml

the issue should be fixed in foundry (https://github.com/foundry-rs/foundry/pull/5163), so it should be fine to remove the pinned version and use the latest nightly

ci: remove pinned foundry version, use nightly instead

---

.github/actions/build/action.yml
.github/actions/setup/action.yml
.github/workflows/build.yml
.github/workflows/examples.yml
.github/workflows/integration-sandbox.yml
.github/workflows/release.yml
.github/workflows/templates.yml
.github/workflows/test.yml

* In #1027 we added a `clean` step before the `build` step. The `clean` step removes build artifacts, so afterwards a full rebuild is necessary. This caused an issue if the turbo cache was hit and the rebuild was skipped, eg https://github.com/latticexyz/mud/actions/runs/5293787981/jobs/9582365505?pr=1011
* This PR changes pulls out the `build` step from the the `Setup` composite action and instead creates a new `Build` composite action that uses the turbo cache and does not clean the artifacts
* This new `Build` composite action is used in all actions, except the `Build and validate artifacts` action, which first cleans the artifacts and then performs a full rebuild without the turbo cache.

ci: clean rebuild in build action, use turbo cache in all other actions

---

.github/workflows/release.yml

followup to #1045 - missed the second clause of the release action

ci: build before release

---

packages/cli/src/commands/worldgen.ts

closes #1038 
Turns out we don't need to modify `world` since it uses `world`'s underlying `worldgen` scripts rather than the CLI as its entry point.
This also sort of fixes the original thing I noticed in #1027, which means we could potentially remove the clean step from CI?

feat(cli): make worldgen clean by default

---

packages/config/src/node/loadConfig.ts

required for (and pulled out of) https://github.com/latticexyz/mud/pull/1077
also useful for generally being able to import local stuff in mud.config

fix(config): bundle local imports when building mud.config

---

packages/common/src/codegen/render-solidity/common.ts

Doesn't fix any current issues
`solidityRelativeImportPath` is only used in `renderAbsoluteImports`, which already wraps the path in `posixPath`
But since `solidityRelativeImportPath` is exported it could be used somewhere else in the future, this fix helps avoid sudden windows-only bugs

fix(common): use posixPath in solidityRelativeImportPath

---

packages/world/gas-report.json
packages/world/src/modules/keyswithvalue/KeysWithValueHook.sol
packages/world/test/KeysWithValueModule.t.sol

fixes https://github.com/latticexyz/mud/issues/1073
the "is changed" optimization doesn't work because 0 is no different from default/absent values,
I could keep it but ignore it if prevValue is 0, but that's hard and only eats more gas for the normal cases
(by hard I mean you can't just compare a blob to 0 - each length of 0s has a different hash - so I need a [memchr, which I have,](https://github.com/dk1a/solidity-stringutils/blob/main/src/utils/memchr.sol) but probably shouldn't put into MUD just for this)
changed the test to be fuzzed, now it includes the prev case (1), and 0, and everything else

fix(world): no longer skip 0 in KeysWithValueModule

---

docs/pages/tutorials/emojimon/getting-started.mdx

It doesn't work as `git clone git@github.com`, it works as `git clone github.com`

docs: fix git clone command

---

packages/schema-type/src/typescript/dynamicAbiTypes.ts

* adds a util function for `isDynamicAbiType` to `schema-type`

feat(schema-type): add isDynamicAbiType

---

packages/protocol-parser/src/encodeRecord.test.ts
packages/protocol-parser/src/encodeRecord.ts

* The packed counter is only appended to the encoded data if there is dynamic data: https://github.com/latticexyz/mud/blob/main/packages/store/src/StoreCore.sol#L434-L442

fix(protocol-parser): only append packed counter if there is dynamic data

---

.changeset/config.json

- we want all mud packages to have the same version number to make it easier for consumers to upgrade all of them to compatible versions
- more info: https://github.com/changesets/changesets/blob/main/docs/fixed-packages.md

chore: synchronize versioning across all packages

---

packages/protocol-parser/src/decodeKeyTuple.test.ts
packages/protocol-parser/src/encodeKeyTuple.test.ts
packages/protocol-parser/src/encodeKeyTuple.ts
packages/protocol-parser/src/index.ts

- add util to encode keys tuples (inverse of decodeKeyTuple)

feat(protocol-parser): add encodeKeyTuple

---

.changeset/fast-ears-hug.md
packages/protocol-parser/src/abiTypesToSchema.test.ts
packages/protocol-parser/src/abiTypesToSchema.ts
packages/protocol-parser/src/index.ts

- add util to sort a list of abi types into a Schema object (with staticFields and dynamicFields)

feat(protocol-parser): add abiTypesToSchema

---

.changeset/tricky-frogs-beam.md
packages/network/src/types.ts
packages/network/src/v2/ecsEventFromLog.ts
packages/network/src/v2/fetchStoreEvents.ts
packages/network/src/workers/SyncWorker.ts

big hack that just removes `devEmit` when we are sending events from the SyncWorker
lmk if this is too hacky and you have a less terrible way of doing it

fix: remove devEmit when sending events from SyncWorker

---

.changeset/config.json

- use the next release version as snapshot version (+ a tag)
- use the git commit hash as tag

chore: update changeset config for snapshot releases

---

.changeset/config.json

- fixes changeset config to properly release snapshot releases with the snapshot action and release all MUD packages with the same version

ci: fix changeset release config

---

packages/schema-type/gas-report.json
packages/schema-type/package.json
packages/schema-type/remappings.txt
packages/schema-type/src/solidity/SchemaType.sol
packages/schema-type/test/solidity/SchemaType.t.sol
packages/store/gas-report.json
packages/world/gas-report.json
pnpm-lock.yaml

fixes a part of https://github.com/latticexyz/mud/issues/1133

refactor(schema-type): add gas-report, optimize

---

packages/store/gas-report.json
packages/store/test/Bytes.t.sol
packages/store/test/Slice.t.sol
packages/store/ts/codegen/ephemeral.ts

for really small view funcs which have unused return value, the optimizer can optimize them out

fix(store): minor gas report fixes, padding

---

.changeset/thin-buses-reply.md
packages/cli/src/commands/set-version.ts
templates/phaser/package.json
templates/react/package.json
templates/threejs/package.json
templates/vanilla/package.json

- updates the `set-version` cli command to work with the new release structure by adding two new options:
- `--tag`: install the latest version of the given tag. For snapshot releases tags correspond to the branch name, commits to `main` result in an automatic snapshot release, so `--tag main` is equivalent to what used to be `-v canary`
- `--commit`: install a version based on a given commit hash. Since commits from `main` result in an automatic snapshot release it works for all commits on main, and it works for manual snapshot releases from branches
- `set-version` now updates all `package.json` nested below the current working directory (expect `node_modules`), so no need for running it each workspace of a monorepo separately.

feat(cli): update set-version to match new release structure, add `--tag`, `--commit`

---

packages/common/src/TableId.test.ts
packages/common/src/TableId.ts

missed this in #1173 when pulling changes from #1113

fix(common): TableId.toHex should also truncate

---

packages/store/gas-report.json
packages/store/test/Gas.t.sol

note that this is just for Storage.sol so I have benchmarks to optimize for, and isn't indicative of MUD's overall performance.
tables vs storage would be a separate comparison

test(store): add gas comparisons for Storage.sol

---

.changeset/brave-rings-tickle.md
packages/store/gas-report.json
packages/store/src/Storage.sol
packages/store/src/StoreCore.sol
packages/store/test/Gas.t.sol
packages/store/test/GasStorageLoad.t.sol
packages/store/test/Storage.t.sol
packages/world/gas-report.json

| | Solidity  | MUD |
| -- | -- | -- |
| write (cold, 1 word) | 22107 | 22339 |
| write (cold, 1 word, partial) | 22136 | 22406 |
| write (cold, 10 words) | 199902 | 199795 |
| write (warm, 1 word) | 107 | 339 |
| write (warm, 1 word, partial) | 236 | 506 |
| write (warm, 10 words) | 1988 | 1795 |
| load (cold, 1 word) | 2109 | 2411 |
| load (cold, 1 word, partial) | 2126 | 2460 |
| load (cold, 10 words) | 19894 | 19911 |
| load (warm, 1 word) | 109 | 414 |
| load (warm, 1 word, partial) | 126 | 462 |
| load (warm, 10 words) | 1897 | 1935 |
surprised I got `storage write (warm, 10 words)` to be more efficient than solidity
but also it doesn't mean anything, this is apples to oranges: https://github.com/latticexyz/mud/blob/b4a68649acdc1f84467f63df150a56750f5cbe72/packages/store/test/Gas.t.s …

refactor(store): optimize Storage library

---

.changeset/afraid-hotels-bathe.md
packages/cli/src/utils/deploy.ts

The Problem
---
Currently if you try to deploy to networks that do not support EIP-1559 then you need to use the --legacy flag within foundry. The custom deploy script as part of the @latticexyz/cli package throws an error on deploy. This blocks the usage of MUD on SKALE (https://skale.space) which is arguably a top network choice for MUD due to the fast speed and zero gas fees.
The Solution
---
I have made a minor update to the script so that it uses EIP-1159 if the values exist, otherwise it falls back to just gasPrice which works on legacy networks i.e SKALE Chains. 
If all values are undefined then it throws an error which is a catch all meaning that there should not be any new issues that arise. 
Note: I have not done any changeset or bumped version as the documentation on both is …

fix(cli): add support for legacy transactions in deploy script

---

docs/pages/world/world-101.mdx

wrong formatting is causing problems in CI

docs: prettier

---

.changeset/itchy-shoes-appear.md
packages/store-indexer/bin/sqlite-indexer.ts
packages/store-indexer/src/sqlite/createIndexer.ts
packages/store-sync/src/recs/syncToRecs.ts
packages/store-sync/src/sqlite/sqliteStorage.test.ts
packages/store-sync/src/sqlite/sqliteStorage.ts

Needed to make the indexed configurable with just RPC URLs

feat(store-indexer,store-sync): make chain optional, configure indexer with RPC

---

.changeset/metal-cats-double.md
.changeset/nice-moose-love.md
packages/store-sync/src/recs/index.ts
packages/store-sync/src/recs/singletonEntity.ts
packages/store-sync/src/recs/syncToRecs.ts

- Export `singletonEntity` as const rather than within the `syncToRecs` result.
- Add `startBlock` option to `syncToRecs`.

feat(store-sync): export singletonEntity as const, allow startBlock in syncToRecs

---

.changeset/large-hats-walk.md
packages/store/abi/StoreCore.sol/StoreCore.abi.json
packages/store/src/StoreCore.sol
packages/world/abi/StoreCore.sol/StoreCore.abi.json
packages/world/abi/src/StoreCore.sol/StoreCore.abi.json

- StoreCore had `tableId` while `IStoreWrite` had `table`, which created two entries in the generated ABI and caused a `duplicate definition` warning
- A nicer solution for this would be to only declare these events once and emit them in `StoreCore` as `IStoreWrite.StoreSetRecord`, but this is only supported from Solidity version 0.8.21 (see https://github.com/ethereum/solidity/pull/14274) and updating the Solidity version is a slightly bigger change than this quick fix

fix(store): align Store event names between IStoreWrite and StoreCore

---

docs/pages/world/world-101.mdx

docs: Explain the root namespace

---

CHANGELOG.md

- Clean up the global changelog to only include v2 changes from changesets

chore: clean up changelog

---

.changeset/tricky-oranges-pump.md
packages/common/package.json
packages/common/src/createContract.ts
packages/common/src/createNonceManager.ts
packages/common/src/index.ts
packages/common/src/transportObserver.ts
pnpm-lock.yaml

feat(common): add createContract, createNonceManager utils

---

.changeset/tricky-kangaroos-love.md
packages/common/src/chains/mudFoundry.ts
packages/common/src/createBurnerAccount.ts
packages/common/src/createContract.ts
packages/common/src/type-utils/common.ts

closes https://github.com/latticexyz/mud/issues/1264
- Moves zero gas fee override to `createContract` until https://github.com/wagmi-dev/viem/pull/963 or similar feature lands
- Skip simulation if `gas` is provided

feat(common): move zero gas fee override to `createContract`

---

docs/pages/index.mdx
docs/theme.config.tsx

Apparently Nextra wants an h1 to determine the page title, otherwise it falls back to the filename rather than what's defined in `_meta`, so we'll force it via the SEO settings.

docs: fix homepage title

---

.changeset/fluffy-moles-march.md
packages/common/package.json
packages/common/src/createContract.ts
pnpm-lock.yaml

closes #1263
I initially thought we needed a queue to handle nonces. But once I separated the transaction simulation (to determine gas) from the nonce handling (incrementing before writing to the mem pool), I discovered we don't even need the queue anymore.
I tried this locally against our testnet and couldn't get nonce issues to appear.
We could improve this further by handling [other mem pool cases](https://github.com/ethereum/go-ethereum/blob/e13fa32cea3497aa311226c62daf21c5847c8e4f/core/txpool/validation.go) and re-simulating as needed (would be nice for failures due to gas price increases).

feat(common): remove need for tx queue in `createContract`

---

docs/pages/store/reading-and-writing.mdx

If this is not a static array it will throw the error
```
➜  contracts git:(main) ✗ forge test
[⠆] Compiling...
[⠢] Compiling 5 files with 0.8.13
[⠆] Solc 0.8.13 finished in 899.89ms
Error:
Compiler run failed:
Error (9582): Member "set" not found or not visible after argument-dependent lookup in type(library MyTable).
--> src/systems/MyTableSystem.sol:23:5:
|
23 |     MyTable.set(keccak256("some.key"), 45, false, fooArray, barArray);
|     ^^^^^^^^^^^
```

docs: barArray should be a static array

---

e2e/packages/sync-test/indexerSync.test.ts

CI is flaky when attempting to start then immediately kill the indexer. This updates tests to only start the indexer when we actually want to use it.

test: only start up indexer for online tests

---

packages/world/gas-report.json
packages/world/test/AccessControl.t.sol

doesn't seem like there's much of anything to optimize here but at least we'll know how much it costs

test(store): add gas tests for AccessControl

---

docs/pages/indexer.mdx
examples/indexer-client/index.ts

When attempting to follow the [installation](https://mud.dev/indexer#installation) instructions on for the indexer and run the indexer. A call to the indexer yields a 404 response. This is because the indexer client url is missing the `/trpc` subroute in order to be able to communicate with the latest indexer.
This commit: 
- Updates the indexer installation documentation
- Updates the indexer client url in the `read-indexer` example

docs: Add /trpc subroute to url indexer documentation and read example

---

.changeset/witty-tigers-rest.md
examples/minimal/packages/contracts/test/CounterTest.t.sol
packages/cli/src/commands/test.ts

- Currently the process always exits with code 0, so CIs can't detect the script failure. Now the script exits with code 1 in case of an error.

fix(cli): make mud test exit with code 1 on test error

---

.changeset/clever-rats-sip.md
packages/services/.npmignore

fix(services): correctly export typescript types

---

package.json

There is a bun issue with `0.8.1` that makes our pre-release changelog action fail in CI, see https://github.com/oven-sh/bun/issues/4327 for context. Pinning it to `0.7.3` should hopefully fix it for now.

ci: pin bun to 0.7.3

---

docs/pages/store/advanced-features.mdx

Chang 
```
if (table != table) revert("invalid table");
```
to
```
if (_table != table) revert("invalid table");
```

docs: fix table references in store hooks example

---

.github/workflows/e2e.yml
.github/workflows/test.yml
e2e/package.json
e2e/packages/contracts/package.json
e2e/packages/sync-test/package.json
package.json
packages/block-logs-stream/package.json
packages/cli/package.json
packages/common/package.json
packages/config/package.json
packages/create-mud/package.json
packages/dev-tools/package.json
packages/gas-report/package.json
packages/noise/package.json
packages/phaserx/package.json
packages/protocol-parser/package.json
packages/react/package.json
packages/recs/package.json
packages/schema-type/package.json
packages/services/package.json
packages/store-indexer/package.json
packages/store-sync/package.json
packages/store/package.json
packages/utils/package.json
packages/world/package.json

Fix #1361
- Added `test:ci` to teach package inside `packages/`, default to `test`
- Updated CI to use `test:ci`

chore: move CI tests to test:ci

---

.changeset/beige-radios-drop.md
packages/world/gas-report.json
packages/world/src/modules/core/implementations/WorldRegistrationSystem.sol
packages/world/test/World.t.sol

fixes #1140. Context in the changeset.
TODO:
TODO in followup: [Add CLI support for upgrading systems](https://github.com/latticexyz/mud/issues/1382)

feat(world): add support for upgrading systems

---

docs/pages/tutorials.mdx
docs/pages/tutorials/minimal.mdx
docs/pages/tutorials/walkthrough/_meta.js
docs/pages/tutorials/walkthrough/minimal-onchain.mdx

In the tutorials which use the template

docs: Change the name of "getting started example" to "template"

---

.github/workflows/docker.yml

This should take any next version (e.g. `2.0.0-next.5`) and publish it under the `next` tag.

build(docker): push latest next version under next tag

---

scripts/changelog.ts

The previous script was processing any added line to the `.changeset/pre.json` file, causing issues when there was a package added to `initialVersions` in `.changeset/pre.json`. Now we're restricting the regex to lines matching the changeset pattern.

fix(ci): only process added changesets in changelog.ts script

---

.changeset/short-ads-jog.md
.changeset/six-cats-agree.md
.changeset/unlucky-guests-cover.md

I wasn't happy with the changelog in https://github.com/latticexyz/mud/pull/1412 so I separated the changesets for each package.

docs: rework abi-ts changesets

---

.changeset/long-lizards-admire.md
packages/abi-ts/src/index.ts

Realized that this will fail for a glob that targets multiple files, e.g. `abi/IWorld.sol/IWorld.abi.json,abi/IStore.sol/IStore.abi.json`. And `glob` already defaults to using `process.cwd()` for how the glob is resolved.

fix(abi-ts): remove cwd join

---

.changeset/silver-mangos-thank.md
packages/world/gas-report.json
packages/world/src/World.sol
packages/world/test/World.t.sol

Fixes #1395 (https://github.com/latticexyz/mud/issues/1395#issuecomment-1706231469)

feat(world): allow callFrom from own address without explicit delegation

---

docs/pages/introduction.mdx

Fix the license hyperlink to align it with the MUD GitHub jump location.

docs: fix the license link

---

e2e/packages/client-vanilla/src/mud/getNetworkConfig.ts
e2e/packages/contracts/worlds.json.d.ts
examples/minimal/packages/client-phaser/src/mud/getNetworkConfig.ts
examples/minimal/packages/client-react/src/mud/getNetworkConfig.ts
examples/minimal/packages/client-vanilla/src/mud/getNetworkConfig.ts
examples/minimal/packages/contracts/worlds.json
examples/minimal/packages/contracts/worlds.json.d.ts
templates/phaser/packages/client/src/mud/getNetworkConfig.ts
templates/phaser/packages/contracts/worlds.json.d.ts
templates/react/packages/client/src/mud/getNetworkConfig.ts
templates/react/packages/contracts/worlds.json.d.ts
templates/threejs/packages/client/src/mud/getNetworkConfig.ts
templates/threejs/packages/contracts/worlds.json.d.ts
templates/vanilla/packages/client/src/mud/getNetworkConfig.ts
templates/vanilla/packages/contracts/worlds.json.d.ts

feat(create-mud): add worlds.json types

---

CHANGELOG.md
docs/pages/changelog.mdx
scripts/changelog.ts

- Write changelog to docs page so it can pick up headings for page overview in sidebar
(tried to do this via import and via symlink but no luck)
- Update headings so page overview formats a bit nicer
Before
After

docs: update changelog headings, write to docs page too

---

docs/pages/world/world-101.mdx

fix the incorrect link
https://mud.dev/reading-and-writing
error code: 404 (not found), linked from page(s):
https://mud.dev/world/world-101

docs: fix the incorrect link on the world-101 page

---

docs/pages/world/modules.mdx

Delete the introduction of the RegistrationModule on the modules page, as the module has been deleted or renamed.
https://mud.dev/world/modules
https://github.com/latticexyz/mud/blob/main/packages/world/src/modules/registration/RegistrationModule.sol
\_____ error code: 404 (not found)
https://github.com/latticexyz/mud/blob/main/packages/world/src/modules/registration/RegistrationSystem.sol
\_____ error code: 404 (not found)
If you wish to keep, please edit it again.

docs: delete the introduction of the RegistrationModule

---

.gitattributes

mostly a quality of life thing to make it easier to review PRs
looks like:

chore: suppress diffs for codegen

---

.changeset/silent-rice-argue.md
packages/protocol-parser/src/fieldLayoutToHex.ts
packages/protocol-parser/src/valueSchemaToFieldLayoutHex.ts

I lost track of where the comment was but I said I'd swap out `fieldLayoutToHex` with a thing that uses `ValueSchema`. This should help with https://github.com/latticexyz/mud/pull/1466 cc @y77cao 
Unfortunately we don't have Solidity tests that map a raw `bytes32` value to `FieldLayout` so I can copy that over to make sure the Solidity and TS line up in terms of behavior, padding, etc. So I skipped adding tests for now.

feat(protoocl-parser): add valueSchemaToFieldLayoutHex

---

.changeset/chatty-news-join.md
packages/cli/src/commands/dev-contracts.ts

Reverts latticexyz/mud#1480
I believe this is the cause of
```
MUDError: Error reading file at out/System.sol/System.json
```

Revert "fix(cli): don't build twice on contract changes"

---

.github/workflows/docker.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/snapshot.yml

attempts to fix docker image tagging by running the docker image step after release so that next tags are present

build: call docker workflow after each release step

---

.changeset/few-jars-turn.md
packages/store/gas-report.json
packages/store/src/Hook.sol
packages/store/src/StoreCore.sol
packages/store/src/StoreHook.sol
packages/store/src/storeHookTypes.sol
packages/store/test/Hook.t.sol
packages/store/test/StoreCore.t.sol
packages/store/test/StoreCoreGas.t.sol
packages/store/test/StoreHook.t.sol
packages/world/gas-report.json
packages/world/src/SystemCall.sol
packages/world/src/SystemHook.sol
packages/world/src/modules/core/implementations/WorldRegistrationSystem.sol
packages/world/src/modules/keysintable/KeysInTableModule.sol
packages/world/src/modules/keyswithvalue/KeysWithValueModule.sol
packages/world/src/systemHookTypes.sol
packages/world/test/SystemHook.t.sol
packages/world/test/World.t.sol

feat(store,world): move hooks to bit flags

---

.changeset/blue-seals-relate.md
packages/dev-tools/src/actions/WriteSummary.tsx

Follow up for https://github.com/latticexyz/mud/pull/1466
Before:
After

feat(dev-tools): update actions to display function name instead of callFrom

---

examples/minimal/packages/client-phaser/package.json
examples/minimal/packages/client-react/package.json
examples/minimal/pnpm-lock.yaml
packages/dev-tools/package.json
packages/react/package.json
pnpm-lock.yaml
templates/phaser/packages/client/package.json
templates/react/packages/client/package.json
templates/threejs/packages/client/package.json

something about a recent package push to `@types/react` caused CI to fall over and seemed to only resolve it by pinning these versions so they all align

build: pin react/react-dom types versions

---

.changeset/mean-islands-brake.md
packages/faucet/bin/faucet-server.ts
packages/faucet/bin/parseEnv.ts

My refactor of env parsing with Zod in #1533 was incomplete and didn't realize the intersection errors got buried.
This replaces the env handling with a nicer error message format like:
```
Missing or invalid environment variables:
RPC_HTTP_URL
FAUCET_PRIVATE_KEY
```

fix(faucet,store-indexer): fix invalid env message

---

.changeset/large-drinks-sell.md
packages/store/gas-report.json
packages/store/src/IStoreErrors.sol
packages/store/src/StoreCore.sol
packages/store/test/StoreCore.t.sol
packages/world/src/AccessControl.sol
packages/world/src/SystemCall.sol
packages/world/src/World.sol
packages/world/src/interfaces/IModule.sol
packages/world/src/interfaces/IWorldErrors.sol
packages/world/src/modules/core/CoreModule.sol
packages/world/src/modules/core/implementations/BalanceTransferSystem.sol
packages/world/src/modules/core/implementations/StoreRegistrationSystem.sol
packages/world/src/modules/core/implementations/WorldRegistrationSystem.sol
packages/world/src/modules/keysintable/KeysInTableModule.sol
packages/world/src/modules/keyswithvalue/KeysWithValueModule.sol
packages/world/src/modules/std-delegations/StandardDelegationsModule.sol
packages/world/src/requireInterface.sol
packages/world/test/AccessControl.t.sol
packages/world/test/StandardDelegationsModule.t.sol
packages/world/test/UniqueEntityModule.t.sol
packages/world/test/World.t.sol
packages/world/test/WorldBalance.t.sol
packages/world/test/WorldDynamicUpdate.t.sol

refactor(store,world): prefix errors with library/contract name

---

.github/workflows/e2e.yml
.github/workflows/test.yml
package.json

too much time is being wasted on waiting for the `test` and `e2e` actions to complete
this PR speeds it up by
- running the tests on a beefier runner
- runnings tests in parallel
- excluding services package from tests

ci: switch to beefy runner for slow actions

---

.changeset/tough-flowers-breathe.md
packages/store/gas-report.json
packages/store/src/ResourceId.sol
packages/world/gas-report.json
packages/world/src/WorldResourceId.sol
packages/world/src/modules/keyswithvalue/getTargetTableId.sol
packages/world/test/KeysWithValueModule.t.sol
packages/world/test/WorldResourceId.t.sol

- Remove `BYTES_TO_BITS` constant, simplify constants used for bitshifting

refactor(store,world): simplify constants

---

.changeset/real-ducks-hope.md
e2e/packages/contracts/worlds.json
examples/minimal/packages/contracts/script/PostDeploy.s.sol
packages/cli/src/utils/deploy.ts
packages/cli/src/utils/systems/getRegisterFunctionSelectorsCallData.ts
packages/cli/src/utils/systems/getRegisterSystemCallData.ts
packages/cli/src/utils/systems/types.ts
packages/cli/src/utils/systems/utils.ts
packages/world/gas-report.json
packages/world/src/interfaces/IWorldRegistrationSystem.sol
packages/world/src/modules/core/implementations/WorldRegistrationSystem.sol
packages/world/src/modules/uniqueentity/UniqueEntityModule.sol
packages/world/test/World.t.sol
packages/world/test/WorldBalance.t.sol

- registerFunctionSelector now accepts the system function signature as a single string. There was no point in separating name and arguments.

feat(world): change registerFunctionSelector signature to accept system signature as a single string

---

.changeset/fresh-scissors-unite.md
packages/common/src/codegen/utils/loadUserTypesFile.ts

- solc doesn't like relative imports without `./`
- solc is fine with `./../`

fix(common): always import relative sol files from ./

---

.changeset/thin-chairs-compare.md
packages/cli/scripts/generate-test-tables.ts
packages/common/src/codegen/utils/loadUserTypesFile.ts
packages/store/ts/config/storeConfig.ts

- minor config format change so we can infer types from the config later

feat(store): add `internalType` property to user types config for type inference

---

.changeset/violet-insects-press.md
packages/cli/contracts/src/codegen/tables/Dynamics1.sol
packages/cli/contracts/src/codegen/tables/Singleton.sol
packages/common/src/codegen/render-solidity/renderTypeHelpers.ts

fix(common): fix memory corruption for dynamic to static array conversion

---

.github/workflows/docker.yml

my last ditch effort to fix docker tagging for next releases
hopefully this lets the docker metadata action find the tag

build: try git context in docker workflow

---

.github/workflows/remove-npm-tag.yml
package.json

adding a small pnpm script util to remove dist tags from npm.
Usage `TAG=<tag> pnpm dist-tag-rm`
Used this to clean up the npm tags for `canary`, `indexing` and `snapshot-test`

chore: add dist-tag-rm script to remove tags from npm

---

.changeset/six-kangaroos-sneeze.md
packages/world/src/IWorldFactory.sol
packages/world/src/WorldFactory.sol

return the address of the newly deployed world from the world factory

feat(world): return world address from WorldFactory

---

.changeset/silver-dolls-shave.md
packages/gas-report/ts/index.ts

fixes https://github.com/latticexyz/mud/issues/1334

feat(gas-reporter): allow gas-reporter to parse stdin

---

.changeset/chilly-kangaroos-clap.md
packages/common/src/chains/mudFoundry.ts

Workaround for regression after bumping viem version. See context in https://github.com/wagmi-dev/viem/pull/1280

fix(common): workaround for zero base fee

---

.changeset/lucky-clocks-love.md
examples/minimal/package.json
examples/minimal/pnpm-lock.yaml
packages/cli/src/commands/set-version.ts
packages/cli/src/common.ts
packages/cli/src/mudPackages.ts
packages/cli/tsup.config.ts

feat(cli): remove backup/restore/force options from set-version

---

.changeset/nice-avocados-poke.md
packages/gas-report/package.json
packages/gas-report/ts/index.ts
pnpm-lock.yaml

- minor addition to pass through logs received via stdin (since the test command can be long running it's useful to know if the tests are still running or the gas reporter is already parsing)

feat(gas-report): add more logs to stdin piping

---

packages/cli/src/utils/deploy.ts

When adding a custom user module to `mud.config.ts`, I am receiving the following error when deploying:
```
MUD dev-contracts watcher failed to deploy config or contracts changes
MUDError: Error reading file at out/0.sol/0.json
```
It appears the deploy script cannot find the compiled contract of my module, because it is using the array index (`0`) as the module name instead of the `name` field.

fix(cli): deploy failing to find user modules

---

.changeset/three-lizards-shave.md
packages/cli/src/commands/test.ts
packages/common/src/foundry/index.ts
packages/world/test/MudTest.t.sol

pulled out of https://github.com/latticexyz/mud/pull/1702

feat(cli): remove .mudtest file in favor of env var

---

.changeset/red-sheep-confess.md
packages/cli/src/deploy/configToTables.ts
packages/cli/src/deploy/deploy.ts
packages/cli/src/deploy/ensureModules.ts
packages/cli/src/deploy/ensureSystems.ts
packages/common/src/utils/index.ts
packages/common/src/utils/uniqueBy.ts
packages/protocol-parser/src/common.ts
packages/store/ts/config/storeConfig.ts

follow up of missed TODO in #1702

fix(cli): support enums in deploy, only deploy modules/systems once

---

.changeset/silent-carrots-glow.md
packages/cli/src/commands/dev-contracts.ts
packages/cli/src/runDeploy.ts

closes #1750
I think we were cleaning before when we had artifacts checked into git and we didn't want to leave around old artifacts, and when we were using typechain to generate types. I don't think this is as concerning anymore now that these are all in a gitignored directory and abi-ts is simple+fast.
I considered replacing `forge clean` with just `rm -rf out` but removing build files creates weird race conditions in Sky Strife deploy + start up, where a process has a chance of starting up while a redeploy is happening and then immediately fails because it can't find e.g. `out/IWorld.sol/IWorld.abi.json`.
If folks want a one-time, pre-deploy clean, they can add that to their script e.g. `forge clean && mud deploy`

feat(cli): remove forge clean from deploy

---

.changeset/loud-mayflies-divide.md
packages/cli/src/deploy/common.ts
packages/cli/src/deploy/deploy.ts
packages/cli/src/deploy/ensureModules.ts
packages/cli/src/deploy/ensureSystems.ts

Using the `pending` block tag to simulate/estimate gas seems to give bad results if the a contract being called does not yet exist (i.e. is itself pending in the mempool). So we need to wait for contracts to be deployed before proceeding.

fix(cli): deploy systems/modules before registering/installing them

---

.changeset/metal-pots-notice.md
packages/cli/src/commands/dev-contracts.ts
packages/cli/src/runDeploy.ts

Helpful if you want to re-run a `mud deploy` with a world that may not have finished deploying. A small workaround until we can do proper failure retries.

feat(cli): add `--alwaysPostDeploy` flag to deploys

---

.changeset/slimy-glasses-tickle.md
e2e/packages/contracts/package.json
examples/minimal/packages/contracts/package.json
packages/cli/src/runDeploy.ts
packages/store/package.json
packages/world-modules/package.json
packages/world/package.json
templates/phaser/packages/contracts/package.json
templates/react/packages/contracts/package.json
templates/threejs/packages/contracts/package.json
templates/vanilla/packages/contracts/package.json

fixes #1773
fixes #1748
Now that forge artifacts are gitignored, we don't need to specifically target which artifacts to build or make them pretty, which greatly speeds up forge because it can use its full cache.

feat(cli,create-mud): use forge cache

---

.changeset/fifty-suits-itch.md
examples/minimal/packages/contracts/script/PostDeploy.s.sol
templates/phaser/packages/contracts/script/PostDeploy.s.sol
templates/react/packages/contracts/script/PostDeploy.s.sol
templates/vanilla/packages/contracts/script/PostDeploy.s.sol

fixes https://github.com/latticexyz/mud/issues/1719

fix(create-mud): set store address in PostDeploy script

---

.changeset/small-dots-poke.md
packages/common/package.json
packages/common/src/codegen/utils/format.ts
packages/common/src/foundry/index.ts
packages/config/package.json
packages/config/src/library/errors.ts
pnpm-lock.yaml

When building a MUD v2 client project with vite (`pnpm run build`), the chalk dependency in `@latticexyz/config` and `@latticexyz/common` causes the following error:
```
error during build:
Error: [vite]: Rollup failed to resolve import "#ansi-styles" from "../../node_modules/.pnpm/chalk@5.3.0/node_modules/chalk/source/index.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
at onRollupWarning (file:///vercel/path0/node_modules/.pnpm/vite@3.2.3_@types+node@18.17.14/node_modules/vite/dist/node/chunks/dep-51c4f80a.js:45522:19)
at onwarn (file:///vercel/path0/node_modules/.pnpm/vite@3.2.3_@types+node@18.17.14/node_modules/vite/dist/node/chunks/dep-51c4f80a.js:45293: …
```

fix(common,config): remove chalk usage

---

.vscode/extensions.json
.vscode/settings.json
e2e/packages/contracts/remappings.txt
examples/minimal/packages/contracts/remappings.txt
templates/phaser/.vscode/extensions.json
templates/phaser/.vscode/settings.json
templates/phaser/packages/contracts/remappings.txt
templates/react/.vscode/extensions.json
templates/react/.vscode/settings.json
templates/react/packages/contracts/remappings.txt
templates/threejs/.vscode/extensions.json
templates/threejs/.vscode/settings.json
templates/threejs/packages/contracts/remappings.txt
templates/vanilla/.vscode/extensions.json
templates/vanilla/.vscode/settings.json
templates/vanilla/packages/contracts/remappings.txt

- updates to hardhat solidity plugin for speed
- removes juanblanco-specific settings
- updates remappings because hardhat solidity didn't like the `./` path

chore: switch to hardhat solidity vscode extension

---

.changeset/dirty-cows-lie.md
.changeset/three-scissors-smile.md
packages/common/src/utils/index.ts
packages/common/src/utils/mapObject.test.ts
packages/common/src/utils/mapObject.ts
packages/store/mud.config.ts
packages/store/ts/config/experimental/resolveConfig.test-d.ts
packages/store/ts/config/experimental/resolveConfig.test.ts
packages/store/ts/config/experimental/resolveConfig.ts
packages/world/mud.config.ts

- Aims to solve one of the main pain points of our current config parser, which breaks on user types in some cases
- Note that this is just a temporary solution, we're still planning to refactor our config parsing from ground up in the medium term (see #1668 for context)

feat(store): add experimental config resolve helper

---

scripts/render-api-docs.ts

builds are occasionally failing due to non-deterministic ordering of files returned by `readdirSync`
https://github.com/latticexyz/mud/actions/runs/6731637925/job/18297224008?pr=1843

docs: sort files from dir before concatenating

---

.changeset/rich-rockets-jog.md
packages/cli/src/mud.ts

The env vars defined in `.env` weren't getting picked up by CLI because the `.env` file isn't loaded by the time the other imports (specifically commands) are loaded.
This changes the CLI import ordering to make sure `.env` is loaded before everything else is imported.

fix(cli): change import order so .env file is loaded first

---

.changeset/purple-ghosts-hear.md
templates/react/packages/client/src/App.tsx

create-create-app treats things that look like `{{ something }}` as a handlebars statement, which doesn't play nicely with React apps
this fix works around that for now

fix(create-mud): workaround create-create-app templating

---

e2e/packages/contracts/test/StaticArray.t.sol

fixes https://github.com/latticexyz/mud/issues/1603

test(e2e): test memory corruption in dynamic-to-static array conversion

---

Dockerfile

trying to run something like `bun --version` in the dockerfile causes it to spin forever 
prob related to me installing via pnpm but setting the `BUN_INSTALL` path to something different, but no time to debug right now

build: remove bun from dockerfile for now

---

next-docs/pages/store/reference/store-core.mdx
next-docs/pages/store/reference/store.mdx

showed up in https://github.com/latticexyz/mud/pull/1919
looks like foundry updated to include parameters

docs: generate solidity params docs

---

.changeset/beige-rockets-return.md
.changeset/cyan-vans-pay.md
packages/store-indexer/src/postgres/getLogs.ts
packages/store-sync/src/postgres-decoded/buildTable.test.ts
packages/store-sync/src/postgres/tables.ts

following up #1965 
not strictly a bug but just doing this for completeness so we don't have to sort inline

fix(store-sync,store-indexer): make last updated block number not null

---

.changeset/fair-baboons-compare.md
packages/store/.npmignore
packages/world/.npmignore

Projects created by `create-mud` are currently failing their `pnpm test` scripts due to TypeScript type checking errors. This pull request addresses this issue and also resolves #1958.
```sh
$ pnpm create mud@2.0.0-next.14 my-project --template vanilla
$ cd my-project
$ pnpm --filter contracts add --save-dev @types/prettier@2.7.2 @types/debug@4.1.7
$ pnpm --filter client add --save-dev @types/prettier@2.7.2 @types/debug@4.1.7 @types/react@18.2.22 @types/react-dom@18.2.7
$ pnpm test # runs `pnpm -r run test` and fails, showing the log below
```
```
$ pnpm --filter client test
> client@0.0.0 test /Users/t/bench/my-project/packages/client
> tsc --noEmit
../../node_modules/.pnpm/@latticexyz+store-sync@2.0.0-next.14_@types+react@18.2.22_react@18.2.0_typescript …
```

fix(store,world): fix `tsc` errors in projects depending on `@latticexyz/store-sync`

---

.changeset/tasty-balloons-collect.md
packages/react/package.json
packages/react/src/useComponentValue.test.ts
packages/react/src/useComponentValue.ts

- Fixes https://github.com/latticexyz/mud/issues/1857 when deleting records

fix(react): trigger useComponentValue on deleted records

---

.changeset/spotty-geese-yawn.md
packages/world-modules/mud.config.ts
packages/world-modules/src/modules/erc20-puppet/tables/ERC20Registry.sol
packages/world-modules/src/modules/erc721-puppet/tables/ERC721Registry.sol

I noticed the ERC721 module was using `erc20Address` (likely copy pasta) and decided to make these names more uniform

fix(world-modules): rename token address fields

---

.changeset/young-pandas-explode.md
packages/store-sync/package.json
packages/store-sync/src/postgres-decoded/buildTable.test.ts
packages/store-sync/src/postgres-decoded/buildTable.ts
pnpm-lock.yaml

fixes https://github.com/latticexyz/mud/issues/1987

feat(store-sync): snake case postgres names in decoded tables

---

.changeset/four-hotels-serve.md
packages/store-sync/src/common.ts
packages/store-sync/src/createStoreSync.ts
packages/store-sync/src/fetchAndStoreLogs.ts

fixes https://github.com/latticexyz/mud/issues/1992

feat(store-sync): fetch and store logs

---

docs/pages/guides/emojimon/5-a-wild-emojimon-appears.mdx
docs/pages/guides/hello-world.mdx

Quick link fixes I ran into while going through the guide.

docs: fix broken links in hello world guide + typo in emojimon guide

---

.changeset/poor-beans-beg.md
packages/abi-ts/tsup.config.ts
packages/block-logs-stream/tsup.config.ts
packages/common/src/codegen/modules.d.ts
packages/common/tsup.config.ts
packages/config/tsup.config.ts
packages/dev-tools/src/router.tsx
packages/dev-tools/tsup.config.ts
packages/faucet/tsup.config.ts
packages/gas-report/tsup.config.ts
packages/noise/tsup.config.ts
packages/phaserx/tsup.config.ts
packages/protocol-parser/tsup.config.ts
packages/react/tsup.config.ts
packages/recs/tsup.config.ts
packages/schema-type/tsup.config.ts
packages/services/tsup.config.ts
packages/store-sync/tsup.config.ts
packages/store/tsup.config.ts
packages/utils/tsup.config.ts
packages/world-modules/tsup.config.ts
packages/world/tsup.config.ts

- Step 1 of the improvements from https://github.com/latticexyz/mud/issues/2051
This pull request enables MUD users with `moduleResolution` set to `bundler` or `node16` in their `tsconfig.json` to pass `tsc` by generating `.d.ts` files during the build. After this change, users with `bundler`/`node16` config can use MUD packages without being affected by MUD's internal TypeScript setup, as they won't need to use the `.ts` files of MUD packages.
Currently, `moduleResolution: node10` is the only supported option for using MUD packages, which is [not ideal for most users](https://www.typescriptlang.org/docs/handbook/modules/guides/choosing-compiler-options.html). For example, here is the config I'd like to use:
```diff
diff --git a/templates/vanilla/packages/client/tsconfig.json …
```

build: allow use by TypeScript projects with `bundler`/`node16` config

---

packages/world/foundry.toml
packages/world/test/CoreModule.t.sol
packages/world/ts/scripts/list-tables-from-store-and-world-configs.ts

Closes #1842.
This pull request introduces a test confirming that `CoreModule` registers all necessary store and world tables. With this test, we can detect missing table registration.
Currently, all tables are registered, allowing this test to pass. To demonstrate the test's functionality, you can revert commit #1841 (`e5a962b`), which resolved a registration oversight. This action will result in a test failure:
```
$ git revert e5a962b
$ cd packages/world
$ forge test --match-path test/CoreModule.t.sol
[⠒] Compiling...
No files changed, compilation skipped
Running 1 test for test/CoreModule.t.sol:CoreModuleTest
[FAIL. Reason: assertion failed] testInstallRoot() (gas: 7153086)
Logs:
Error: table should be registered: otworldFunctionSignatur
Error: Assertion Failed
Test result: FAILED. 0 …
```

test(world): add test to ensure all store/world tables are registered

---

packages/world/test/CoreModule.t.sol

This PR improves a revert message in a test, as mentioned in https://github.com/latticexyz/mud/pull/2064#discussion_r1439322584.
Previously, if the test failed, the error message was like:
```
Error: table should be registered: otworldFunctionSignatur
```
Now, it has been improved to:
```
Error: table should be registered: ot:world:FunctionSignatur
```

test(world): improve revert message

---

.changeset/blue-forks-move.md
packages/store/src/Bytes.sol

Seems like Solidity was casting the `bytes2` `output` variable to the `bytes4` return type.

fix(store): slice4 output should be bytes4 [M-03]

---

docs/pages/cli/test.mdx

The parts that don't work (see #2002 and #2004) are in commit d78d95d68f9909971d00de689e1687bd860730ad. I tried to comment them out, but prettier "helped" by escaping the comments.

docs(cli): add `mud test`

---

packages/world/gas-report.json
packages/world/test/Factories.t.sol

We don't currently have gas tests for `WorldFactory`. Adding this also covers more code like the `Create2` library.

chore(world): add gas reports for deploying world via WorldFactory

---

.changeset/little-starfishes-walk.md
packages/store/src/Slice.sol

The `Slice` library uses `self.pointer()` and `pointer(self)` which are interchangeable. With this PR it only uses `pointer(self)`, which I think is more "direct" than a method attached by the global `using` statement.

refactor(store): slice library uses pointer consistently [n-08]

---

.changeset/happy-ants-lay.md
packages/store/src/Slice.sol
packages/store/src/Storage.sol
packages/store/src/tightcoder/TightCoder.sol
packages/world/src/WorldContext.sol

Specify integers as hex (ie. 0x20) instead of decimal (ie. 32). This is purely for consistency and does not effect the compiled code.

refactor(store,world): use hexadecimal as integer base [n-08]

---

.changeset/little-cherries-rule.md
packages/world/gas-report.json
packages/world/src/WorldFactory.sol

Makes the `coreModule` variable in `WorldFactory` [immutable](https://docs.soliditylang.org/en/latest/contracts.html#constant-and-immutable-state-variables) because it is only set once, in the constructor. This decreases gas cost:
> Compared to regular state variables, the gas costs of constant and immutable variables are much lower ... Immutable variables are evaluated once at construction time and their value is copied to all the places in the code where they are accessed.

refactor(world): make coreModule variable immutable [n-08]

---

.changeset/three-llamas-sin.md
packages/world-modules/gas-report.json
packages/world/gas-report.json
packages/world/src/WorldContext.sol

`WorldContext._world()` currently fetches the world address with `StoreSwitch`. 
For consistency with `_msgSender` and `_msgValue`, it should use`WorldContextConsumerLib` which calls `StoreSwitch` under the hood.

refactor(world): world context gets world from consumer lib [n-08]

---

.changeset/thin-days-sparkle.md
packages/store/gas-report.json
packages/store/src/Slice.sol
packages/world-modules/gas-report.json
packages/world/gas-report.json

We can simplify this by check:
```solidity
if (!(start <= end && end <= data.length)) revert Slice_OutOfBounds(data, start, end);
```
by negating it:
```solidity
if (start > end || end > data.length) revert Slice_OutOfBounds(data, start, end);
```

refactor(store): simplify check in Slice.getSubslice [n-08]

---

packages/store/gas-report.json
packages/store/src/Bytes.sol
packages/world-modules/gas-report.json

This function:
```solidity
function sliceX(bytes memory data, uint256 start) internal pure returns (bytesX) {
assembly {
output := mload(add(add(data, ...), start))
}
return output;
}
```
can be simplified to:
```solidity
function sliceX(bytes memory data, uint256 start) internal pure returns (bytesX output) {
assembly {
output := mload(add(add(data, ...), start))
}
}
```

refactor(store): bytes slice functions have named output [n-08]

---

.changeset/soft-panthers-develop.md
packages/store/src/FieldLayout.sol
packages/world-modules/src/modules/utils/ArrayLib.sol
packages/world/src/modules/core/CoreModule.sol
packages/world/test/SystemHook.t.sol

Solidity variables are initialised to zero by default so we don't need to explicitly set them.

refactor(store,world,world-modules): do not explicitly initialise to zero [n-08]

---

.github/workflows/test.yml

Reverts latticexyz/mud#2119
Turns out this is too noisy and makes it hard to even see test errors due to CI log truncation

Revert "test: increase forge test verbosity in ci"

---

.changeset/breezy-garlics-decide.md
packages/world-modules/gas-report.json
packages/world-modules/src/interfaces/IUniqueEntitySystem.sol
packages/world-modules/src/modules/uniqueentity/getUniqueEntity.sol

Spotted this while working on https://github.com/latticexyz/mud/pull/2160
Using `world.call` means we don't need to maintain this manual system interface and it's cheaper on gas.

refactor(world-modules): simplify getUniqueEntity call

---

.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/snapshot.yml

build: reduce CI concurrency when publishing to npm

---

packages/store-sync/src/zustand/createStorageAdapter.ts

This log was found to be [slowing down](https://github.com/latticexyz/mud/pull/2178#issuecomment-1907918017) the Zustand storage adapter, and is not needed because the preceding `debug` call logs the same information.

chore(store-sync): delete console log

---

packages/cli/src/deploy/resolveConfig.ts

@alvrs pointed this out and I thought we were only relying on the onchain registration for this but apparently not! missed this in #1980

fix(cli): fix namespaced function signatures

---

.changeset/seven-pears-walk.md
packages/world-modules/src/modules/erc20-puppet/ERC20Module.sol
packages/world-modules/src/modules/erc721-puppet/ERC721Module.sol
packages/world-modules/src/modules/keysintable/KeysInTableModule.sol
packages/world-modules/src/modules/keyswithvalue/KeysWithValueModule.sol
packages/world-modules/src/modules/uniqueentity/UniqueEntityModule.sol
packages/world/src/IModule.sol
packages/world/src/IWorldKernel.sol
packages/world/src/Module.sol
packages/world/src/World.sol
packages/world/src/codegen/interfaces/IModuleInstallationSystem.sol
packages/world/src/modules/core/implementations/ModuleInstallationSystem.sol

Fixes https://github.com/latticexyz/mud/issues/1757
This name better reflects that the `bytes` argument is encoded module arguments, not the actual typed arguments.

refactor(world,world-modules): rename module args to encodedArgs

---

.changeset/nine-plants-carry.md
e2e/packages/contracts/src/systems/CustomErrorsSystem.sol
packages/common/src/codegen/utils/contractToInterface.ts

fix(common): include only errors defined in the contract

---

.changeset/rare-dragons-walk.md
packages/store/gas-report.json
packages/store/src/StoreCore.sol
packages/world-modules/gas-report.json

this function is called in `StoreCore` so we can avoid using `StoreSwitch` to write to the table.

refactor(store): push to StoreHooks with StoreCore method

---

.changeset/chatty-timers-hug.md
.changeset/twelve-terms-lay.md
docs/pages/store/reference/store-core.mdx
packages/store/src/StoreCore.sol
packages/store/test/StoreMock.sol
packages/world/src/modules/core/CoreModule.sol

to clarify and clear the "core" term for other uses

feat(store): rename StoreCore.registerCoreTables to registerInternalTables

---

docs/pages/guides/extending-world.mdx
docs/pages/guides/hello-world.mdx
docs/pages/world/balance.mdx

It was `template/typescript/getting-started` rather than `templates/typescript/getting-started`

docs: fix link to getting started

---

.changeset/nasty-rice-pull.md
e2e/packages/sync-test/syncToRecs.test.ts
packages/store-sync/src/createStoreSync.ts

don't ask me why or how, but adding `sleep(1)` after calling the `storageAdapter` made hydration updates show up in the client. i was going crazy trying to figure out why i wasn't receiving them in the main thread, but then remembered having a similar problem in DF with how async calls were being handled. if someone actually knows the mechanism that is being abused here lmk and we can come up with a less obscure solution.
also once i started receiving updates i realized the % calculation was wrong, so fixed that too.
getting these updates is important so i can properly benchmark how long hydration takes on the sky strife end. my manual calculations on my pc are ~5 seconds.

feat(store-sync): wait for idle after each chunk of logs in a block

---

.changeset/fifty-guests-rescue.md
packages/store-sync/src/postgres-decoded/buildColumn.ts
packages/store-sync/src/postgres-decoded/buildTable.test.ts
packages/store-sync/src/postgres-decoded/createStorageAdapter.test.ts
packages/store-sync/src/postgres/createStorageAdapter.test.ts
packages/store-sync/src/postgres/version.ts

- extended fix for #2077
- bumps postgres sync version

fix(store-sync): fix overflowing column types, bump postgres sync version

---

.changeset/lemon-numbers-design.md
packages/store-sync/src/postgres-decoded/buildColumn.ts
packages/store-sync/src/postgres-decoded/createStorageAdapter.test.ts
packages/store-sync/src/postgres/columnTypes.ts
packages/store-sync/src/postgres/createStorageAdapter.test.ts
packages/store-sync/src/postgres/version.ts

Pulled out from https://github.com/latticexyz/mud/pull/2251

feat(store-sync): bool array column types for decoded indexer

---

.changeset/purple-cooks-remember.md
packages/gas-report/ts/index.ts

fix(gas-report): update filename matcher

---

.github/workflows/bench.yml
.github/workflows/test.yml
e2e/package.json
package.json

Adds a GitHub Action where we can run benchmarks on a remote machine and inspect the output.

test: add benchmark GitHub workflow

---

.github/workflows/bench.yml
e2e/package.json

This command was renamed in https://github.com/latticexyz/mud/pull/2228 but not updated in https://github.com/latticexyz/mud/pull/2234

fix: use correct command to generate benchmark data

---

.changeset/forty-weeks-laugh.md
docs/pages/world/reference/world-external.mdx
packages/world/gas-report.json
packages/world/src/IWorldFactory.sol
packages/world/src/WorldFactory.sol
packages/world/test/Factories.t.sol
packages/world/ts/worldEvents.ts

Fixes https://github.com/latticexyz/mud/issues/2285

feat(world): emit salt in WorldDeployed event

---

.changeset/brave-ghosts-walk.md
e2e/packages/sync-test/setup/startIndexer.ts
packages/store-indexer/bin/parseEnv.ts
packages/store-indexer/bin/postgres-decoded-indexer.ts
packages/store-indexer/bin/postgres-indexer.ts
packages/store-indexer/bin/sqlite-indexer.ts
packages/store-sync/src/common.ts
packages/store-sync/src/createStoreSync.ts

- adds `followBlockTag` option, defaults to `latest` (current behavior)
- uses `followBlockTag: safe` for indexers

feat(store-sync,store-indexer): add followBlockTag option

---

.changeset/calm-drinks-dance.md
packages/cli/src/deploy/resolveConfig.ts
packages/world/ts/config/resolveWorldConfig.ts

Resolves #2263 
Throw error when systems with the same ids occur.

fix(cli): throw warning for duplicate systems

---

docs/pages/world/reference/world.mdx
packages/world/src/World.sol

Closes https://github.com/latticexyz/mud/issues/2106 by explaining why we use the `prohibitDirectCallback` modifier.
The comment is a rewording of the PR description from the original PR that added it https://github.com/latticexyz/mud/pull/1563

docs(world): add comments for prohibitDirectCallback modifier

---

.changeset/empty-camels-suffer.md
docs/pages/store/reference/misc.mdx
docs/pages/store/reference/store-hook.mdx
docs/pages/store/reference/store.mdx
packages/store/src/FieldLayout.sol
packages/store/src/IStoreHook.sol
packages/store/src/PackedCounter.sol
packages/store/src/Schema.sol
packages/store/src/Slice.sol
packages/store/src/StoreHook.sol
packages/store/src/errors.sol
packages/store/test/FieldLayout.t.sol
packages/store/test/Schema.t.sol
packages/store/test/StoreCore.t.sol
packages/world-modules/src/modules/erc20-puppet/ERC20Module.sol
packages/world-modules/src/modules/erc721-puppet/ERC721Module.sol
packages/world-modules/src/modules/puppet/Puppet.sol
packages/world-modules/src/modules/puppet/PuppetMaster.sol

refactor(store,world-modules): clean up error names/locations

---

packages/world-modules/test/ERC721.t.sol

Once in a blue moon, the fuzzed `from` address in `testSafeTransferFromToERC721Recipient` is equal to the `recipient` that is deployed during the test. Not sure the probability of this but interesting that it happened [here](https://github.com/latticexyz/mud/actions/runs/8082938117/job/22084862341)!
The addresses being equal means that `from` sends tokens to itself, so the assertion that it's balance decreases to zero (`assertEq(token.balanceOf(from), 0)`) fails. 
Update: looks like we missed an assumption. Fixed by coping the approach from `testSafeTransferFromToERC721RecipientWithData`.

test(world-modules): fix failing token fuzz test

---

.changeset/dull-otters-smash.md
packages/world-modules/src/modules/erc20-puppet/ERC20Module.sol
packages/world-modules/src/modules/erc721-puppet/ERC721Module.sol

Updates the ERC20 and ERC721 implementations to always register the token namespace, instead of checking if it has already been registered. This prevents issues with registering the namespace beforehand, namely that only the owner of a system can create a puppet for it.
Fixes https://github.com/latticexyz/mud/issues/2354

fix(world-modules): token modules always register namespace

---

.changeset/heavy-shirts-dance.md
docs/pages/store/reference/misc.mdx
docs/pages/store/reference/store.mdx
packages/store/src/FieldLayout.sol
packages/store/src/IFieldLayoutErrors.sol
packages/store/src/IPackedCounterErrors.sol
packages/store/src/ISchemaErrors.sol
packages/store/src/ISliceErrors.sol
packages/store/src/IStore.sol
packages/store/src/IStoreErrors.sol
packages/store/src/PackedCounter.sol
packages/store/src/Schema.sol
packages/store/src/Slice.sol
packages/store/test/FieldLayout.t.sol
packages/store/test/Schema.t.sol
packages/store/test/StoreCore.t.sol

Exploring my comment on https://github.com/latticexyz/mud/issues/2158#issuecomment-1971071251
Basically some errors (`FieldLayoutLib_*`, `PackedCounter_*`, etc.), are not included in the `IStore` ABI because they are not defined in that interface or anything it inherits. Instead, they are defined in libraries and are referenced only in the _implementation_ of Store.
Some solutions:
- Define error interfaces for each library, eg. `IPackedCounterErrors` (this PR)
- Move every error to a single `IStoreErrors`
- Use abstract contracts [like OpenZeppelin](https://github.com/ethereum/solidity/issues/13086#issuecomment-1445324173) (I'm not sure how that works)
- Stop using interfaces and have clients import the `Store` implementation

refactor(store): event interfaces for Store libraries 

---

packages/common/src/sendTransaction.ts
packages/common/src/writeContract.ts

somewhat addresses #2081 in that we no longer attempt to parallelize simulate with other things and just do it ahead of the tx we're about to send (see https://github.com/latticexyz/mud/issues/2081#issuecomment-1976837638 for more context) 
I figure a working but slightly slower tx queue is better than a non working one

fix(common): move prepare just before send tx

---

Dockerfile

had this fix/workaround in CI but not in Dockerfile

build: run prepare before install in Dockerfile

---

.changeset/sharp-students-compare.md
packages/store-sync/src/zustand/createStorageAdapter.ts

when playing with this in #2355, I noticed a possible edge case where tracking these updated IDs separately meant that an update -> delete or delete -> update for the same record in the same block could give the wrong results in the end (out of sync from chain state)

fix(store-sync): track changed records together in zustand

---

.changeset/lemon-falcons-arrive.md
docs/pages/store/reference/misc.mdx
e2e/packages/contracts/src/codegen/tables/Multi.sol
e2e/packages/contracts/src/codegen/tables/Vector.sol
examples/multiple-accounts/packages/contracts/src/codegen/tables/LastCall.sol
package.json
packages/cli/contracts/src/codegen/tables/Offchain.sol
packages/cli/contracts/src/codegen/tables/Singleton.sol
packages/cli/contracts/src/codegen/tables/Statics.sol
packages/cli/contracts/src/codegen/tables/UserTyped.sol
packages/store/gas-report.json
packages/store/src/Bytes.sol
packages/store/src/codegen/tables/Tables.sol
packages/store/test/Bytes.t.sol
packages/store/test/Storage.t.sol
packages/store/test/StoreCore.t.sol
packages/store/test/codegen/tables/Mixed.sol
packages/store/test/codegen/tables/Vector2.sol
packages/store/ts/codegen/field.ts
packages/world-modules/src/modules/erc20-puppet/tables/ERC20Metadata.sol
packages/world-modules/src/modules/keysintable/tables/UsedKeysIndex.sol
packages/world/src/WorldResourceId.sol
packages/world/src/codegen/tables/FunctionSelectors.sol
packages/world/src/codegen/tables/Systems.sol
packages/world/src/requireValidNamespace.sol
packages/world/test/codegen/tables/TwoFields.sol
templates/react/packages/contracts/src/codegen/tables/Tasks.sol
templates/threejs/packages/contracts/src/codegen/tables/Position.sol
test/mock-game-contracts/src/codegen/tables/Position.sol

These were removed in #2090 as part of audit fixes because they appeared unused, but we missed that they are used by codegen (likely because the function signature is generated by a template string):
https://github.com/latticexyz/mud/blob/1a82c278dd8037155b6449e383b3a00d6453ea3e/packages/store/ts/codegen/field.ts#L269
Shoutout to @transmissions11 for spotting this and kicking this off in #2402
While I was here, I renamed the helpers from `Bytes.sliceN` to `Bytes.getBytesN` to both match the `Bytes.setBytesN` methods and to better differentiate this from `Slice` and `SliceLib` utils.

fix(store): restore bytesN helpers

---

e2e/packages/contracts/mud.config.ts
e2e/packages/contracts/src/codegen/tables/StaticArray.sol
e2e/packages/contracts/test/StaticArray.t.sol

Fixes the test created in https://github.com/latticexyz/mud/pull/1880
I'm not 100% sure what the intention of this test is, when I run it the memory it the elements of `result` are the same as `data` (ie. not corrupted). Maybe this test added _before_ the fix, to prove it was broken?

test(e2e): fix memory corruption test

---

packages/store/ts/config/index.ts
packages/store/ts/config/v2/generics.ts
packages/store/ts/config/v2/index.ts
packages/store/ts/config/v2/store.ts
packages/world/ts/config/v2/world.test.ts
packages/world/ts/config/v2/world.ts

- adds the runtime implementation corresponding to #2389

feat(world): add config resolution at runtime

---

.changeset/sixty-queens-brake.md
e2e/packages/contracts/src/codegen/tables/StaticArray.sol
packages/cli/contracts/src/codegen/tables/Dynamics1.sol
packages/cli/contracts/src/codegen/tables/Singleton.sol
packages/cli/contracts/test/Tablegen.t.sol
packages/store/ts/codegen/field.ts

The static array length getters return a constant, so the unused args were causing build errors:

refactor(store): make static array length a constant

---

packages/store-sync/src/query-cache/subscribeToQuery.test.ts
packages/store-sync/src/query-cache/subscribeToQuery.ts

I removed the original `subjects$` in favor of just `subjectEvents$` but we need `subjects$` for RECS compat

feat(store-sync): query subjects$ and subjectEvents$

---

.changeset/rich-penguins-film.md
examples/multiple-accounts/.vscode/extensions.json
templates/phaser/.vscode/extensions.json
templates/react-ecs/.vscode/extensions.json
templates/react/.vscode/extensions.json
templates/threejs/.vscode/extensions.json
templates/vanilla/.vscode/extensions.json

This PR adds additional recommended vscode extensions for the templates and the multi-accounts example.
continued from #2429

feat(create-mud): add additional recommended vscode extensions

---

packages/config/src/exports/index.ts
packages/protocol-parser/src/exports/index.ts
packages/query/package.json
packages/query/src/exports/index.ts
packages/query/src/exports/internal.ts
packages/query/tsup.config.ts
packages/schema-type/src/typescript/exports/index.ts
packages/store-sync/src/query-cache/query.ts
packages/store-sync/src/query-cache/subscribeToQuery.ts

follows patterns in https://github.com/latticexyz/mud/pull/2452

refactor(query): update exports

---

packages/store/ts/config/v2/README.md
packages/store/ts/config/v2/input.ts
packages/store/ts/config/v2/namespaces.ts
packages/store/ts/config/v2/schema.ts
packages/store/ts/config/v2/store.test.ts
packages/store/ts/config/v2/store.ts
packages/store/ts/config/v2/storeWithShorthands.test.ts
packages/store/ts/config/v2/storeWithShorthands.ts
packages/store/ts/config/v2/table.ts
packages/store/ts/config/v2/tableShorthand.ts
packages/store/ts/config/v2/tables.ts
packages/world/ts/config/v2/world.test.ts
packages/world/ts/config/v2/world.ts
packages/world/ts/config/v2/worldWithShorthands.ts

- Adds an explicit type error to validators when trying to override `namespace` or `name` when defining tables in a store/world config. `name`/`namespace` is still on the `TableInput` type so we can use it internally.
- Slightly refactored the validator pattern to move runtime validation to `defineX` and expect a fully validated input in `resolveX`
- Updates the store resolver to map tables to a prefixed key if a `namespace` option is provided in the config

feat(store/world): disable `namespace`/`name` override on store/world table inputs, move validation to define

---

packages/store/ts/config/v2/input.ts
packages/store/ts/config/v2/schema.ts
packages/store/ts/config/v2/table.test.ts
packages/store/ts/config/v2/table.ts
packages/world/ts/config/v2/world.ts

Add more type errors for missing required keys or invalid inputs

feat(store, world): throw if required keys are not provided, more validations

---

.changeset/config.json
test/mock-game-contracts/CHANGELOG.md
test/mock-game-contracts/package.json

Reverts latticexyz/mud#2509
> error ValidationError: Some errors occurred when validating the changesets config:
> error The package "@latticexyz/store-sync" depends on the ignored package "mock-game-contracts", but "@latticexyz/store-sync" is not being ignored. Please add "@latticexyz/store-sync" to the `ignore` option.

Revert "chore: ignore test package in changeset flow"

---

.changeset/dry-toes-lay.md
packages/store/package.json
packages/store/ts/config/v2/input.ts
packages/store/ts/config/v2/store.test.ts
packages/store/ts/config/v2/table.test.ts
packages/store/ts/config/v2/table.ts
packages/store/ts/exports/index.ts
packages/world/package.json
packages/world/ts/config/v2/input.ts
packages/world/ts/config/v2/world.test.ts
packages/world/ts/config/v2/worldWithShorthands.test.ts
packages/world/ts/exports/index.ts
pnpm-lock.yaml

Minor fixes to config input validations:
- `systems.openAccess` incorrectly expected `true` as the only valid input. It now allows `boolean`.
- The config complained if parts of it were defined `as const` outside the config input. This is now possible.
- Shorthand inputs are now enabled.

fix(store,world): minor config validation fixes

---

docs/pages/store/tables.mdx

The biggest change is that this syntax doesn't compile for some reason:
```
FieldLayout fieldLayout = FieldLayoutLib.encode({
staticFields: staticFields,
numDynamicFields: 0
});
```

docs(store/tables): update for MUD 2.0

---

.github/workflows/lint.yml
.github/workflows/test.yml

PR https://github.com/latticexyz/mud/pull/2506 disabled the `test` workflow for docs, but it missed that linting is still run here and applies to docs.
This moves the linting into a seperate workflow that activates on docs changes.

chore: add lint workflow for docs

---

docs/pages/guides/emojimon/5-a-wild-emojimon-appears.mdx

1. Highlight an updated line in `createSystemCalls` the same way as the rest of the guide, when some code is added/changed.
2. Remove mention of `awaitStreamValue` in favor of `waitForTransaction` since the flow changed with the new return type of `setupNetwork`. (see [version 2.0.0](https://mud.dev/changelog#version-200-next1))

docs: minor fixes in Emojimon guide

---

.changeset/poor-maps-itch.md
packages/common/src/actions/transactionQueue.ts
packages/common/src/createNonceManager.ts
packages/common/src/getContract.ts
packages/common/src/sendTransaction.ts
packages/common/src/writeContract.ts

After hearing from @kooshaba about Sky Strife latency, specifically when playing from Japan, I did a bit of testing with a fresh template deployed to Redstone Holesky to find out where some of the latency was coming from. There's quite a few factors at play:
- each tx requires gas estimation, and viem does two RPC round trips: one to get max priority fee per gas and one to get the gas estimate of the call
- the former can likely be cached but I am unclear how safe it is to do so (is this a hardcoded chain value? or something that fluctuates based on demand?)
- the latter can possibly be cached for recurring calls to the same methods with same/similar args (Sky Strife does some variant of this) but would need some thought to get this right, if not just leave this to user land to figure out …

feat(common): allow specifying concurrency in transactionQueue

---

docs/pages/world/modules/keyswithvalue.mdx
docs/pages/world/namespaces-access-control.mdx
docs/pages/world/tables.mdx

Since it's a different value in 2.0.4.
Note: This only updates pages that don't have an active PR on them. I updated the active PRs separately as needed.

docs(*): update the default `World` address 🏎 

---

templates/threejs/packages/contracts/test/WorldTest.t.sol

something recently changed in foundry to cause CI to start failing for threejs template because there are no tests to run
I didn't wanna remove the `mud test` call because it's useful to make sure the template's world/MUD config can be deployed, so I just added a really basic test instead (copied from other templates)

fix(create-mud): add test for threejs template

---

.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/snapshot.yml

> The workflow is not valid. .github/workflows/snapshot.yml (Line: 65, Col: 3): Error calling workflow 'latticexyz/mud/.github/workflows/docker.yml@a9e8a407b5d6f356d7d0a1c1f093de926ffb072f'. The nested job 'docker' is requesting 'packages: write', but is only allowed 'packages: read'.
CI is broken, I think since moving to GitHub Enterprise? I'm not really sure how to fix this but wanna unblock npm releases.

build: skip docker build/release for now

---

.github/actions/setup-prerequisites/action.yml

There is a Foundry issue that only happens in CI: https://github.com/foundry-rs/foundry/issues/7620
So we can pin CI to an old version for now.

fix: pin CI foundry version

---

.changeset/tasty-geckos-bathe.md

accidentally force-pushed over this in #2645

docs: add changeset for #2645

---

packages/store-sync/src/query-cache/createStorageAdapter.test.ts
packages/store-sync/src/query-cache/query.test.ts
packages/store-sync/src/query-cache/subscribeToQuery.test.ts

see https://github.com/latticexyz/mud/issues/2671
since we're not using querying yet and it's on pause, going to disable these tests for now to keep CI happy

test(store-sync): skip flaky query cache tests

---

.changeset/few-glasses-rhyme.md
packages/store-sync/src/createStoreSync.ts

This change was introduced by https://github.com/latticexyz/mud/pull/2665/files but @dhvanipa found a bug with the new approach (we actually want to await the storing of logs, which might get out of order with just `map`)

fix(store-sync): await fetchAndStoreLogs

---

.changeset/tender-cherries-hammer.md
e2e/packages/sync-test/registerDelegationWithSignature.test.ts
packages/world-modules/gas-report.json
packages/world-modules/src/modules/callwithsignature/getSignedMessageHash.sol
packages/world-modules/test/CallWithSignatureModule.t.sol
packages/world/ts/callWithSignatureTypes.ts

Making signatures more legible with a `string` systemId

feat(world-modules): string systemId in `callWithSignature` typehash

---

.changeset/five-pots-switch.md
packages/cli/src/deploy/getResourceIds.ts

Attempting to fetch invalid logs from an RPC can error with a [400 Bad Request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400) and `"block is out of range"`. In this case, Viem's `getLogs` does not [retry the query](https://github.com/wevm/viem/blob/main/src/utils/buildRequest.ts#L199-L217). 
However, when using a request router like [proxyd](https://github.com/ethereum-optimism/optimism/tree/develop/proxyd), it is possible that some RPC's are slightly behind and do not have the newer logs. In this case we do actually want to retry the query until the RPC has caught up. 
This PR adds a `pretry` to the `getLogs` call in the `getResourceIds` function which has consistently failed in deployment.

fix(cli): add retry to getLogs when getting resource ID's

---

packages/cli/src/deploy/getResourceIds.ts

Linting error was caused in https://github.com/latticexyz/mud/pull/2709 but missed because CI wasn't working

chore(cli): run prettier on getResourceIds

---

packages/cli/src/deploy/ensureDeployer.ts
packages/cli/src/deploy/getDeployer.ts

As noted in https://github.com/latticexyz/mud/pull/2662#discussion_r1577694925, it is useful to get the address of the CREATE2 deployer, but we should not export it directly in case the deployer contract does not exist.
This adds a `getDeployer() => Promise<Address | undefined>` function.

refactor(cli): add getDeployer

---

packages/cli/src/deploy/ensureWorldFactory.ts
packages/cli/src/deploy/getWorldContracts.ts
packages/cli/src/deploy/getWorldFactoryContracts.ts
packages/cli/src/deploy/getWorldProxyFactoryContracts.ts

In https://github.com/latticexyz/mud/pull/2662 (contract verification) it is useful to have a list of the names and bytecode for the standard contracts deployed by MUD (`InitModule`, `World` etc.)
As pointed out in https://github.com/latticexyz/mud/pull/2662#discussion_r1577697220 we can split this into a seperate PR and rework the approach too.

refactor(cli): getWorldContracts

---

.changeset/angry-ties-travel.md
packages/common/src/sendTransaction.ts

- if we don't use the fee ref here, we don't get the "site recommended" fee to show up in Metamask
- also doesn't seem to hurt, just makes submission a bit faster
- i believe this is what was causing nonce gap issues during the last playtest. players could improperly set their fee and get a tx stuck in the mempool indefinitely

fix(common): use feeRef for sendTransaction calls

---

.changeset/little-crabs-unite.md
packages/store-indexer/bin/postgres-indexer.ts
packages/store-indexer/bin/sqlite-indexer.ts
packages/store-indexer/src/koa-middleware/metrics.ts

Followup to #2739, adding `latest_stored_block_number` and `follow_block_tag` to prometheus metrics

feat(store-indexer): add latest stored block number to metrics

---

.changeset/afraid-eagles-learn.md
.changeset/eighty-actors-live.md
packages/store-indexer/bin/parseEnv.ts

Allow an empty `STORE_ADDRESS=` env variable to be passed in to the store indexer

fix(store-indexer): transform env var to undefined

---

.changeset/eighty-actors-live.md
packages/store-indexer/bin/parseEnv.ts

Followup to #2741, which didn't actually fixed the issue (merged too quickly). This does.

fix(store-indexer): allow empty env variable

---

packages/store-indexer/bin/parseEnv.ts

The fix in #2746 changed the output type of `STORE_ADDRESS` from `Hex | undefined` to `string | undefined`. This changes it back to `Hex | undefined`.

fix(store-indexer): refine parsed type

---

.changeset/sour-otters-warn.md
packages/cli/src/commands/verify.ts
packages/cli/src/verify.ts
packages/cli/src/verify/verifyContract.ts
packages/schema-type/.npmignore
packages/store/.npmignore
packages/world-modules/.npmignore
packages/world/.npmignore

`mud verify` attempts to verify external contracts (`InitModule`, `World`, etc.) by changing the working directory to the relevant dependency (eg. `cd node_module@latticexyz/world`) and running `forge verify-contract`. 
However these dependencies on NPM are incomplete, causing issues when attempting to compile the source files:
1) Without `solidity-files-cache.json`, Forge cannot locate the contract by name alone (eg. `World`), and requires the full path. We fix this by publishing the cache on NPM.
2) The sub-dependencies of each dependency are not installed, so for example, if `world.sol` imports `schema-type`, `world.sol` cannot be compiled. We fix this by running `npm install` in each dependency during verification.

fix(cli): fix verify with sourcify for dependencies

---

.changeset/plenty-pianos-boil.md
packages/cli/src/utils/postDeploy.ts

reverts #2638
- got a report that postdeploy via `mud deploy` was waiting ~forever for txs, prob due to gas too low
- ran postdeploy script manually with garnet RPC and saw that it set the gas fee appropriately
- if you want to set manually during `mud deploy`, you can now use `mud deploy --forgeScriptOptions` (#2703)

fix(cli): remove postdeploy gas setting in favor of script options

---

.github/workflows/test.yml
packages/common/src/account/kms/kmsKeyToAccount.test.ts

This test does not need a custom environment variable, we can set [`AWS_ENDPOINT_URL`](https://docs.aws.amazon.com/sdkref/latest/guide/feature-ss-endpoints.html) and the AWS SDK will pick it up.

test(common): kms test uses sdk environment variable

---

.github/workflows/e2e.yml

This PR add a timeout of 25 minutes to the e2e tests.
After looking at the history of the e2e tests runs, I saw that it usually takes 8-12 minutes to complete these tests so I arbitrarly chose 25 minutes which is approximately 2x of the max runtime observed.
Let me know if you feel that 25 minutes is still too high.
Closes #2761

ci: add timeout to e2e tests

---

.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/snapshot.yml
.github/workflows/test-published-packages.yml

moves our npm publish step to a single workflow that calls out to the previous workflows, but with `needs` to ensure order of operations
noticed that we had both "snapshot" and "release" CI steps running simultaneously, where "snapshot" would sometimes run first (due to concurrency), which would publish a new npm version for a release but not properly tag+release on github

ci: separate publish workflow to ensure order

---

.changeset/plenty-peas-love.md
packages/common/src/chains/garnet.ts
packages/common/src/chains/redstone.ts

- fixed redstone, garnet chain contract objects, which should have been extending the OP chain config contracts (otherwise its missing predeploys like price oracle)
- added redstone contract addresses now that redstone is live

fix(common): extend OP contracts, add redstone ones

---

.changeset/lazy-rivers-live.md
packages/store-indexer/bin/postgres-indexer.ts
packages/store-indexer/bin/sqlite-indexer.ts

Followup to #2763 - the intention was for the `distance_from_follow_block` gauge to be a positive number if the latest stored block is lagging behind the follow block

fix(store-indexer): fix distance from follow block metric

---

.changeset/seven-windows-tickle.md
packages/world/ts/config/defaults.ts
packages/world/ts/config/types.ts
packages/world/ts/config/v2/compat.ts
packages/world/ts/config/v2/defaults.ts
packages/world/ts/config/v2/input.ts
packages/world/ts/config/v2/output.ts
packages/world/ts/config/v2/world.ts
packages/world/ts/config/worldConfig.ts

If you define a list of modules like
```ts
const modules = [...];
```
then later use them in your `mud.config.ts`, you'll get an error like this:
cc @0xhank 
pulled out of https://github.com/latticexyz/mud/pull/2803

fix(world): config uses readonly arrays

---

Dockerfile

increasing node memory to be able to build the store-sync package

---

packages/common/src/LruMap.ts
packages/common/src/index.ts
packages/store-sync/src/recs/decodeEntity.ts
packages/store-sync/src/recs/encodeEntity.ts

spotted this as a source of heavy computation during hydration of sky strife

feat(store-sync): add lru cache to recs encode/decode entity

---

Dockerfile

changing the way the memory is set to be in line with the main branch (see #2810)

build: up node memory during docker build (historical-indexer)

---

Dockerfile

applying the same change as on #2802, but on main branch
(cherry picked from commit 31e0a4b14e914e08f878785b3a040cc528e4146d)

build: up node memory during docker build

---

.changeset/sweet-lemons-eat.md
packages/store/ts/config/v2/compat.ts
packages/store/ts/config/v2/enums.ts
packages/store/ts/config/v2/generics.ts
packages/store/ts/config/v2/input.ts
packages/store/ts/config/v2/output.ts
packages/store/ts/config/v2/store.test.ts
packages/store/ts/config/v2/store.ts
packages/store/ts/config/v2/storeWithShorthands.test.ts
packages/world/ts/config/v2/world.test.ts
packages/world/ts/config/v2/worldWithShorthands.test.ts

transforms enum input arrays into an object so they can be used in TS
closes #1957

feat(store,world): usable enum values from config

---

.github/workflows/templates.yml

It gave me an error message saying I need to run `gas-report`, even though that's not used in the templates. So I fixed it.

build: use correct error message 🏎

---

.github/workflows/test.yml

trying to address runaway tests: https://github.com/latticexyz/mud/pull/2823#issuecomment-2111072372
these take a few mins to run, so 15 mins should give plenty of room for growth

ci: add timeout for tests

---

docs/pages/guides/adding-delegation.mdx

Specifically, change `App.tsx` to account for the fact `getContract` now wants a structure with the two clients.

docs(guides/adding-delegation): change to account for API changes 🏎 

---

docs/pages/guides/hello-world/add-system.mdx

docs(guides/hello/add system): update for the `app` namespace 🚗 

---

tsconfig.paths.json

missed that this import path was under `/internal` in https://github.com/latticexyz/mud/pull/2828

build: fix world modules mud config path

---

packages/gas-report/package.json

missed in https://github.com/latticexyz/mud/pull/2828

fix(gas-report): include foundry.toml in published package

---

.changeset/selfish-olives-yawn.md
packages/common/package.json
packages/common/tsconfig.base.json
packages/common/tsconfig.json
packages/create-mud/scripts/copy-templates.sh
packages/create-mud/scripts/tsconfig.base.json
templates/phaser/package.json
templates/phaser/tsconfig.json
templates/react-ecs/package.json
templates/react-ecs/tsconfig.json
templates/react/package.json
templates/react/tsconfig.json
templates/threejs/package.json
templates/threejs/tsconfig.json
templates/vanilla/package.json
templates/vanilla/tsconfig.json
tsconfig.json

This migrates `tsconfig.base.json` to `@latticexyz/common` so it can be referenced in templates, and updated overtime without creating breaking changes.

feat(common): export base tsconfig

---

package.json
packages/abi-ts/package.json
packages/block-logs-stream/package.json
packages/cli/package.json
packages/common/package.json
packages/common/tsconfig.base.json
packages/config/package.json
packages/dev-tools/package.json
packages/faucet/package.json
packages/gas-report/package.json
packages/protocol-parser/package.json
packages/query/package.json
packages/react/package.json
packages/recs/package.json
packages/schema-type/package.json
packages/solhint-config-mud/package.json
packages/solhint-plugin-mud/package.json
packages/store-indexer/package.json
packages/store-sync/package.json
packages/store/package.json
packages/utils/package.json
packages/world-modules/package.json
packages/world/package.json

closes https://github.com/latticexyz/mud/issues/2871
for backwards compatibility with `moduleResolution: "node"`
we had removed this in https://github.com/latticexyz/mud/pull/2828 but it broke projects when upgrading MUD verisons
(intentionally didn't include a changeset because this can be considered part of the changes in https://github.com/latticexyz/mud/pull/2828 and https://github.com/latticexyz/mud/pull/2873)

feat: restore typesVersions

---

packages/store/ts/codegen/tablegen.ts
packages/store/ts/config/defaults.ts
packages/store/ts/config/storeConfig.ts
packages/store/ts/config/v2/compat.ts
packages/store/ts/register/mudConfig.test-d.ts

This usages of this property can be replaced by the V2 `config.codegen.indexFilename`.
Pulled out of https://github.com/latticexyz/mud/pull/2880

refactor(store): remove V1 `codegenIndexFilename`

---

.changeset/tender-badgers-ring.md
packages/common/src/resourceToHex.test.ts
packages/common/src/resourceToHex.ts
packages/store/ts/config/v2/store.test.ts
packages/world/ts/config/v2/world.test.ts
packages/world/ts/config/v2/worldWithShorthands.test.ts

feat(common): throw instead of truncating namespace

---

packages/store/ts/config/v2/input.ts
packages/store/ts/config/v2/output.ts
packages/store/ts/config/v2/tables.ts
packages/world/ts/config/v2/input.ts
packages/world/ts/config/v2/namespaces.ts
packages/world/ts/config/v2/output.ts
packages/world/ts/config/v2/systems.ts

just a small internal naming change for key names used in TS mappings to align with the terminology we've started using

refactor(store,world): rename TS keys of resource labels

---

.github/workflows/remove-npm-tag.yml

makes tag an input for the action rather than assuming it should use the branch name

build: remove npm tag by name

---

.changeset/four-peas-swim.md
packages/store-sync/src/recs/syncToRecs.ts

No strong types are needed for this part of the config and @ssalbdivad spotted that the part of the config is a major typescript performance bottleneck.

fix(store-sync): add NoInfer to syncToRecs options

---

.changeset/selfish-readers-occur.md
packages/cli/package.json
packages/cli/src/commands/trace.ts
packages/cli/src/deploy/resolveConfig.ts
packages/world/ts/node/render-solidity/worldgen.ts
packages/world/ts/node/resolveSystems.ts
pnpm-lock.yaml

refactor(cli): remove last ethers usage

---

.changeset/nine-books-reflect.md
packages/cli/src/commands/trace.ts
packages/cli/src/deploy/common.ts
packages/cli/src/deploy/ensureNamespaceOwner.ts
packages/cli/src/deploy/getFunctions.ts
packages/cli/src/deploy/getResourceAccess.ts
packages/cli/src/deploy/getResourceIds.ts
packages/cli/src/deploy/getSystems.ts
packages/cli/src/deploy/getTables.ts
packages/cli/src/runDeploy.ts
packages/store/ts/codegen/tableOptions.ts
packages/world/ts/scripts/list-tables-from-store-and-world-configs.ts

goes with https://github.com/latticexyz/mud/pull/2963

refactor(cli): use config namespaces for tables

---

packages/store/ts/codegen/renderTableIndex.ts
packages/world/ts/node/findSolidityFiles.ts

I saw that there is an issue with codegen on Windows and found 2 problems that are causing it:
- in the `renderTableIndex.ts` file, `node:path/posix` was imported, but using the posix implementation interfered with the ` path.relative` call on Windows, which resulted in an invalid `relative` path (it would return the full path to the table file instead of the relative path to the index file)
- another issue I found is with the `findSolidityFiles` function. It uses the `glob` package in order to find the solidity files using a `pattern`, however, this `pattern` is generated using the `path` node module, which on Windows returns an "escaped" pattern (Windows paths have backslashes which are actually considered escaped characters in the `pattern` used by `glob`). Looking at the `glob` …

fix(store,world): codegen on Windows

---

package.json
pnpm-lock.yaml

trying to see if bumping the version fixes the issue where a `minor` changeset bumped to a major version for next release

chore: bump changesets cli

---

.changeset/config.json
packages/dev-tools/package.json

closes #2977 
looks like changeset has some weird logic for resolving peer dependencies: https://github.com/changesets/changesets/issues/1279
we can work around this by:
- enabling experimental peer dep flag in changeset
- specifying a wider version range for workspace peer deps

fix: changeset minor version

---

.changeset/orange-dancers-nail.md

clarified how we're using resource labels (originally landed in https://github.com/latticexyz/mud/pull/2953) when it comes to top-level config output keys

docs: update resource labels changeset

---

.changeset/chilly-horses-accept.md
.changeset/new-ways-count.md
packages/cli/src/runDeploy.ts
packages/store/mud.config.ts

codegen-only tables should not be deployed

fix(cli,store): don't deploy disabled tables

---

docs/components/Params.module.css
docs/components/Params.tsx
docs/pages/config.mdx
docs/pages/config/reference.mdx

docs(config): add multi-namespace support

---

.changeset/quiet-pugs-rule.md
docs/pages/config/reference.mdx
e2e/packages/contracts/mud.config.ts
e2e/packages/contracts/src/systems/HiddenSystem.sol
packages/cli/src/deploy/common.ts
packages/cli/src/deploy/deploy.ts
packages/cli/src/deploy/getSystems.ts
packages/cli/src/deploy/resolveConfig.ts
packages/world/ts/config/v2/defaults.ts
packages/world/ts/config/v2/input.ts
packages/world/ts/config/v2/output.ts
packages/world/ts/config/v2/system.test.ts
packages/world/ts/config/v2/system.ts
packages/world/ts/config/v2/world.test.ts
packages/world/ts/node/render-solidity/worldgen.ts

addresses some of https://github.com/latticexyz/mud/issues/2979

feat(world,cli): add system deploy config

---

.changeset/twenty-trains-bathe.md
packages/world/ts/node/render-solidity/worldgen.ts

Missed this when refactoring systems and worldgen. This issue only shows up when you cwd and rootDir are different, e.g. running worldgen from a different dir than where the mud config lives.
Found while adding a second MUD config to world-modules in https://github.com/latticexyz/mud/pull/3026

fix(world): worldgen should read system source from root dir

---

packages/cli/src/deploy/ensureModules.ts
packages/cli/src/deploy/ensureResourceLabels.ts
packages/world-module-metadata/gas-report.json
packages/world-module-metadata/src/MetadataModule.sol
packages/world-module-metadata/test/MetadataModule.t.sol

since the deployer doesn't really support idempotent modules with prerequisites (like this module needing ownership of the metadata namespace), we'll just do a "not installed" check for now
when we update the module to be idempotent, it'll be different bytecode and deployed to a separate address anyway, and can remove the "not installed" check at that point
this hopefully improves UX of rerunning deploy with module already installed instead of the cryptic error around "optional module install failed" until #3035 is done

refactor(cli,world-module-metadata): install metadata module once

---

.changeset/quick-frogs-fold.md
.changeset/tasty-toys-deliver.md
packages/cli/src/deploy/common.ts
packages/config/src/common.ts
packages/store/ts/config/v2/defaults.ts
packages/store/ts/config/v2/input.ts
packages/store/ts/config/v2/store.test.ts
packages/store/ts/config/v2/table.ts
packages/store/vitestSetup.ts
packages/world/ts/config/v2/defaults.ts
packages/world/ts/config/v2/input.ts
packages/world/ts/config/v2/namespace.ts
packages/world/ts/config/v2/output.ts
packages/world/ts/config/v2/system.test.ts
packages/world/ts/config/v2/system.ts
packages/world/ts/config/v2/systems.ts
packages/world/ts/config/v2/world.test.ts
packages/world/ts/config/v2/world.ts
packages/world/vitestSetup.ts

goes with #3039 and closes some gaps we had there

feat(world): add namespaceLabel to system config

---

.changeset/clean-worms-walk.md
packages/common/src/createFeeRef.ts
packages/common/src/createNonceManager.ts
packages/common/src/getFeeRef.ts
packages/common/src/getNonceManagerId.ts
packages/common/src/sendTransaction.ts
packages/common/src/writeContract.ts

we were doing this inconsistently and it makes it harder to override underlying behavior

fix(common): route all actions through viem client

---

packages/explorer/src/app/api/world/route.ts
packages/explorer/src/app/layout.tsx
packages/explorer/src/app/worlds/[worldAddress]/interact/Form.tsx
packages/explorer/src/app/worlds/[worldAddress]/interact/page.tsx
packages/explorer/src/app/worlds/[worldAddress]/layout.tsx
packages/explorer/src/components/LatestBlock.tsx
packages/explorer/src/components/Navigation.tsx
packages/explorer/src/components/ui/Skeleton.tsx
packages/explorer/src/queries/useAbiQuery.ts

While fetching ABI, initially the ABI that's returned is not complete i.e. only includes system functions. Now showing a loader in navbar to indicate if the world is still being registerer. In addition, showing skeletons while "Interact" page is loading for better UX.

feat(explorer): abi fetch loaders

---

e2e/packages/contracts/package.json
examples/local-explorer/packages/contracts/package.json
examples/minimal/packages/contracts/package.json
examples/multiple-accounts/packages/contracts/package.json
examples/multiple-namespaces/package.json
packages/cli/package.json
packages/store/package.json
packages/world-modules/package.json
packages/world/package.json
templates/phaser/packages/contracts/package.json
templates/react-ecs/packages/contracts/package.json
templates/react/packages/contracts/package.json
templates/threejs/packages/contracts/package.json
templates/vanilla/packages/contracts/package.json
test/mock-game-contracts/package.json

if a project switches to multi-namespace mode, the previous command will no longer remove all codegen files, but this new command will

fix: update codegen dir in rm commands

---

docs/pages/config/reference.mdx
docs/pages/world/modules.mdx
docs/pages/world/modules/erc721.mdx

docs(world/modules): add `mud.config.ts` installation 🚗 

---

.changeset/long-dogs-wash.md
packages/cli/src/deploy/configToModules.ts
packages/cli/src/deploy/deploy.ts
packages/cli/src/deploy/ensureContract.ts
packages/cli/src/deploy/ensureContractsDeployed.ts
packages/cli/src/deploy/ensureFunctions.ts
packages/cli/src/deploy/ensureModules.ts
packages/cli/src/deploy/ensureResourceTags.ts
packages/cli/src/deploy/ensureSystems.ts
packages/cli/src/deploy/ensureTables.ts
packages/cli/src/deploy/waitForTransactions.ts

we're seeing issues in garnet where registering function selectors fails
```
mud:cli:deploy found CREATE2 deployer at 0x4e59b44847b379578588920ca78fbf26c0b4956c +0ms
mud:cli:deploy found balance transfer system at 0xA274B9a7E743cd8dF3c6Fd0aBD47eD55Fc943BC3 +63ms
mud:cli:deploy found batch call system at 0x53E5c08d82A377167069Ade46d087Ab753538608 +1ms
mud:cli:deploy found access management system at 0x17ffDEfF94ed0b80c493A179d4B3b09D6d71f627 +13ms
mud:cli:deploy found core module at 0xDa4E062e8C69D39d9472945232a53F579904AC45 +5ms
mud:cli:deploy found core registration system at 0xd416f26aafcaaECa50b0dC35bd023e7286BE2961 +6ms
mud:cli:deploy found world factory at 0x573802f86c51B61d7Cf620952217eC6Ce0537d2E +34ms
mud:cli:deploy found app__TasksSystem system at …
```

fix(cli): deployer should wait for prereq txs

---

packages/explorer/src/app/(explorer)/worlds/page.tsx

Force worlds page to be rendered on every request in order to pick up `worldAddress`.

fix(explorer): force dynamic worlds page

---

.changeset/shy-walls-suffer.md
packages/cli/src/deploy/ensureModules.ts

refactored this in #3113 and missed an `await` 😭 
https://github.com/latticexyz/mud/commit/0738d295f802be28524d517d75efe3b5837f10c1#diff-88faa6929d6f4326095b26d63a22e1e294b285941b5ec6f2b3eefd9b0388d4ccR48
see also https://github.com/latticexyz/mud/issues/2040

fix(cli): add missing await

---

.changeset/lazy-ties-double.md
packages/explorer/src/app/(explorer)/error.tsx
packages/explorer/src/app/(explorer)/worlds/[worldAddress]/explorer/DataExplorer.tsx
packages/explorer/src/app/api/utils/getDatabase.ts

Optionally, show error message for error pages.

feat(explorer): show error message in error page

---

.changeset/metal-brooms-enjoy.md
packages/cli/src/deploy/deploy.ts

closes https://github.com/latticexyz/mud/issues/3170

feat(cli): register namespace labels

---

docs/components/common-text/FilterTypes.mdx
docs/pages/guides/hello-world/filter-sync.mdx
docs/pages/state-query/dozer.mdx

docs(filter-sync and dozer): explain that there are two sync types 🚗 

---

packages/world/gas-report.json

Gas reporting seems to have changed in forge version `96ad8a6`, this PR makes our CI happy again.

chore: update gas-report after foundryup

---

.changeset/smooth-tigers-exist.md
packages/world/ts/config/v2/output.ts
packages/world/ts/config/v2/world.ts

Pulled out from #3192 - turns out we weren't resolving the module types with defaults, so if your MUD config included modules it didn't satisfy the `World` output type.

fix(world): resolve module config

---

.changeset/perfect-parrots-wonder.md
packages/explorer/src/observer/decorator.ts

it's hard to extend certain clients (e.g. in a Wagmi's `createConfig`'s `client` option) without this
follows decorator patterns seen in viem

fix(explorer): better observer decorator types

---

.changeset/thick-countries-double.md
examples/local-explorer/packages/client/src/mud/setupNetwork.ts
packages/explorer/src/exports/observer.ts
packages/explorer/src/observer/decorator.ts
packages/explorer/src/observer/messages.ts
packages/store-sync/src/stash/syncToStash.ts

I thought moving towards `waitForStateChange` would be clearer, but realized state may not change as a result of a transaction, so reverting back to `waitForTransaction`.

refactor: waitForStateChange -> waitForTransaction

---

.changeset/flat-bulldogs-smash.md
packages/cli/src/runDeploy.ts
packages/cli/src/utils/enableAutomine.ts

currently if you deploy to a non-anvil chain, the deploy starts out with a big error
```
mud:cli Enabling automine +0ms
mud:cli Skipping automine +43ms
mud:cli MethodNotFoundRpcError: The method "anvil_getAutomine" does not exist / is not available.
mud:cli
mud:cli URL: [http://](https://rpc.garnetchain.com/)
mud:cli Request body: {"method":"anvil_getAutomine"}
mud:cli
mud:cli Details: Method not found
mud:cli Version: 2.21.6
mud:cli     at withRetry.delay.count.count (/Users/kevin/Projects/latticexyz/eat-the-fly/node_modules/.pnpm/viem@2.21.6_bufferutil@4.0.8_typescript@5.4.2_utf-8-validate@5.0.10_zod@3.23.8/node_modules/viem/utils/buildRequest.ts:132:25)
mud:cli     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
we can probably just quiet these

feat(cli): quieter automine

---

package.json
pnpm-lock.yaml

pulled out of https://github.com/latticexyz/mud/pull/3215
adds sort-package-json as a monorepo dev dep, which greatly improved git hook speed when on an unstable internet connection
also renamed to not collide with the dep's bin name

chore: add sort-package-json dev dep

---

.changeset/early-poems-heal.md
packages/common/src/actions/transactionQueue.ts
packages/store-sync/src/common.ts
packages/store-sync/src/createStoreSync.ts
packages/store-sync/src/postgres-decoded/createStorageAdapter.ts
packages/store-sync/src/postgres-decoded/syncToPostgres.ts
packages/store-sync/src/postgres/createStorageAdapter.ts
packages/store-sync/src/postgres/syncToPostgres.ts
packages/store-sync/src/recs/syncToRecs.ts
packages/store-sync/src/sqlite/sqliteStorage.ts
packages/store-sync/src/sqlite/syncToSqlite.ts
packages/store-sync/src/stash/syncToStash.ts
packages/store-sync/src/zustand/syncToZustand.ts

pulled out of https://github.com/latticexyz/mud/pull/3215
simplifies types by removing some unused generics and only adding them where they're needed
hoping this helps with TS speed 🤞

feat(store-sync): remove unused generics

---

.changeset/good-crabs-trade.md
.changeset/large-windows-sort.md
packages/block-logs-stream/src/blockRangeToLogs.test.ts
packages/block-logs-stream/src/blockRangeToLogs.ts
packages/block-logs-stream/src/createBlockStream.ts
packages/block-logs-stream/src/fetchBlockLogs.ts
packages/block-logs-stream/src/fetchLogs.test.ts
packages/block-logs-stream/src/fetchLogs.ts
packages/block-logs-stream/src/groupLogsByBlockNumber.ts
packages/block-logs-stream/src/index.ts
packages/cli/package.json
packages/cli/src/deploy/getWorldDeploy.ts
packages/common/src/utils/iteratorToArray.ts
pnpm-lock.yaml

pulled out of https://github.com/latticexyz/mud/pull/3215
related to https://github.com/latticexyz/mud/issues/1522
closes https://github.com/latticexyz/mud/issues/2729
leans on `fetchLogs` to get all logs of a given range, paginating and reducing block range as needed

feat(cli): paginate world deploy logs

---

.changeset/tricky-chefs-care.md
packages/cli/src/deploy/deploy.ts

deploy world then user contracts instead of the other way around, to keep from spending gas on contract deploys in cases where world deploy fails

refactor(cli): adjust deploy order

---

.changeset/sixty-comics-love.md
packages/explorer/package.json
packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/DataExplorer.tsx
packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/TableSelector.tsx
packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/TablesViewer.tsx
pnpm-lock.yaml

Added type-safe URL search params using `nuqs`. Given that the Explorer is going to have more filters, and other state, in the future, it's useful to add it now. Also, table state is now stored in URL search params as well so it can be shared.

feat(explorer): move filter state to url

---

.changeset/sour-bats-compare.md
docs/pages/store/reference/misc.mdx
packages/store/src/ResourceId.sol
packages/store/test/ResourceId.t.sol

feat(store): add unwrap() function to ResourceIdInstance

---

packages/explorer/src/components/Navigation.tsx

- click target for nav items is bigger and now includes the underline/bottom border
- hovering now shows bottom border

feat(explorer): improve nav click target

---

.changeset/hip-rings-rule.md
packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/observe/TransactionTableRow.tsx

Nested inputs would show up as `[Object object]` before. Now showing the full input.

fix(explorer): display nested inputs

---

docs/pages/guides/emojimon/3-players-and-movement.mdx

In Solidity, `msg.sender` is not a function, so the docs are incorrect and this is confusing. This corrects it so it makes sense.

docs: correct msg.sender in emojimon

---

.changeset/soft-bears-rest.md
packages/explorer/src/app/(explorer)/[chainName]/layout.tsx
packages/explorer/src/app/(explorer)/[chainName]/page.tsx
packages/explorer/src/app/(explorer)/[chainName]/worlds/WorldsForm.tsx
packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/interact/Form.tsx
packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/layout.tsx
packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/observe/TransactionTableRow.tsx
packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/page.tsx
packages/explorer/src/app/(explorer)/[chainName]/worlds/page.tsx
packages/explorer/src/app/(explorer)/queries/useTablesQuery.ts
packages/explorer/src/app/(explorer)/utils/timeAgo.ts
packages/explorer/src/common.ts
packages/explorer/src/components/Navigation.tsx

fix(explorer): various fixes

---

.changeset/nice-ligers-cough.md
packages/cli/src/deploy/ensureTables.ts
packages/cli/src/deploy/getTables.ts
packages/protocol-parser/src/getKeySchema.ts

fix(cli): throw error on schema changes

---

.changeset/soft-rings-grab.md
packages/world/package.json
packages/world/ts/getFunctions.ts
pnpm-lock.yaml

fix(world): use fetchLogs in getFunctions

---

packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/observe/TransactionsWatcher.tsx

see https://github.com/wevm/viem/issues/2995 for details

fix(explorer): get block when transaction hashes are missing

---

docs/pages/world/modules/erc20.mdx

Adapted the erc20 puppet module docs to use the new erc20 module.

docs(world-module-erc20): replace erc20 docs

---

packages/store-consumer/package.json
pnpm-lock.yaml

there are no typescript files in `store-consumer` so `tsup` errors when running `dev`

chore(store-consumer): skip dev script

---

packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/EditableTableCell.tsx
packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/TablesViewer.tsx
packages/explorer/src/app/(explorer)/queries/useTableDataQuery.ts

There is a discrepancy between how dozer and local indexer store boolean values which needs to be taken into account.

fix(explorer): editable checkbox display

---

packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/useQueryValidator.ts

Semicolon at the end of SQL queries are now optional.

feat(explorer): optional semicolon for sql queries

---

.changeset/config.json
.github/workflows/snapshot.yml

This should fix not being able to tag snapshot versions in npm with a slash from our branch naming scheme.
The underlying issue is we're using the branch name in both the npm version and npm tag. And npm seems to explode when there's a slash in the version name because the version determines the path/filename of the packaged `.tgz` file.
If we decouple the npm version from the npm tag, we should get the behavior we want.

ci: only use commit in snapshot version

---

.changeset/tender-ties-draw.md
packages/common/src/actions/transactionQueue.ts
packages/common/src/sendTransaction.ts
packages/common/src/writeContract.ts

Internally, we've migrated to using `getAction` for all client actions (https://github.com/latticexyz/mud/pull/3071), so we don't need this specific of a type. This lets us pass in plain/undecorated clients into these helpers.

feat(common): loosen client type in tx queue

---

packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/consts.ts
packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/useMonacoSuggestions.ts

Limit suggested SQL keywords to a predefined list. This is because the default suggestion list is too long, and dozer won't even support most of the suggestions.

feat(explorer): limit suggested sql keywords

---

packages/store-sync/src/stash/createStorageAdapter.ts

like zustand storage adapter, this applies all logs as one `applyUpdates` operation, resulting in one subscriber emission instead of one per log

feat(store-sync): apply logs as one stash update

---

tsconfig.paths.json

chore: add ts path for common internal exports

---

.changeset/little-tables-wait.md
packages/world/ts/actions/callFrom.ts
packages/world/ts/encodeSystemCall.ts
packages/world/ts/encodeSystemCallFrom.ts
packages/world/ts/encodeSystemCalls.ts
packages/world/ts/encodeSystemCallsFrom.ts
packages/world/ts/worldCallAbi.ts

pulled out of https://github.com/latticexyz/mud/pull/3419
it's common among our packages that you'll see these TS errors from world package when running tsc
```
% pnpm tsc
../world/ts/actions/callFrom.ts:135:9 - error TS2488: Type 'unknown' must have a '[Symbol.iterator]()' method that returns an iterator.
135   const [staticData, encodedLengths, dynamicData] = await _readContract({
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../world/ts/encodeSystemCall.ts:19:22 - error TS2344: Type '{ type: string; name: string; inputs: { name: string; type: string; internalType: string; }[]; outputs: { name: string; type: string; internalType: string; }[]; stateMutability: string; }[]' does not satisfy the constraint 'Abi'.
Type '{ type: string; name: string; inputs: { name: string; type: string; …
```

fix(world): switch to TS for ABIs in utils

---

.changeset/sharp-lions-cover.md
packages/protocol-parser/src/getKeyTuple.ts
packages/store/ts/exports/internal.ts
packages/store/ts/getRecord.ts
packages/store/ts/getStaticDataLocation.ts

pulled out of https://github.com/latticexyz/mud/pull/3419

feat(store): add getRecord and getStaticDataLocation helpers

---

packages/entrykit/package.json
packages/entrykit/src/getSessionClient.ts
packages/entrykit/src/onboarding/Session.tsx
pnpm-lock.yaml

I was seeing errors like `extendFn is not a function` that stemmed from assuming `smartAccountActions` was meant to be called/instantiated. Not sure how this didn't show up before, but I seem to recall seeing this sporadically. Might be related to semver (as in a prior patch version had diff behavior), so I also pinned the permissionless version.

fix(entrykit): don't call decorator

---

.changeset/tricky-experts-pull.md
packages/store-sync/src/common.ts
packages/store-sync/src/createStoreSync.ts
packages/store-sync/src/getRecords.ts
packages/store-sync/src/postgres-decoded/createStorageAdapter.test.ts
packages/store-sync/src/postgres-decoded/createStorageAdapter.ts
packages/store-sync/src/postgres/createStorageAdapter.test.ts
packages/store-sync/src/postgres/createStorageAdapter.ts
packages/store-sync/src/sqlite/sqliteStorage.test.ts
packages/store-sync/src/sqlite/sqliteStorage.ts

going to need this for some stash + store-sync hooks

feat(store-sync): use client instead of decorated public client

---

packages/store-sync/.eslintrc
packages/store-sync/src/postgres-decoded/buildColumn.ts
packages/store-sync/src/postgres/columnTypes.ts
packages/store-sync/src/react/SyncProvider.tsx
packages/store-sync/src/react/useSync.ts
packages/store-sync/src/recs/defineInternalComponents.ts
packages/store-sync/src/sqlite/buildColumn.ts
packages/store-sync/src/sqlite/columnTypes.ts
packages/store-sync/src/trpc-indexer/createAppRouter.ts

pulled out of #3439 and follows #3451
Whenever I try to work around React Query to get a simpler interface, I always end up rebuilding the same stuff (pending states, error states, etc.). When will I learn to just use React Query? :)

feat(store-sync): simplify SyncProvider

---

.changeset/seven-seahorses-roll.md
packages/cli/src/deploy/common.ts
packages/cli/src/deploy/deploy.ts
packages/cli/src/deploy/resolveConfig.ts
packages/cli/tsconfig.json

pulled out of https://github.com/latticexyz/mud/pull/3290
not sure why this appeared there but not in main, but `abi` on `System` type was being overloaded (`Abi` set by `DeterministicContract` and then `string[]` set by `System`) throwing type errors
ideally one of these becomes authoritative (e.g. manifest) but didn't wanna think through that at the moment, so I moved the metadata stuff aside

fix(cli): don't overload system abi type

---

.changeset/fair-rocks-exercise.md
packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/Explorer.tsx
packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/SQLEditor.tsx
packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/TablesViewer.tsx
packages/explorer/src/app/(explorer)/queries/useTableDataQuery.ts

feat(explorer): pause/resume live query

---

.changeset/cuddly-pandas-fail.md

after merging https://github.com/latticexyz/mud/pull/3444, I spotted [a subtle bug fix](https://github.com/latticexyz/mud/pull/3444/files#diff-9b06d0bdfafdf404c488f6a77449e85ea71d13ac2214e3ac7ea6319500b79949R90) that wanted to make sure was captured by changelog in case anyone uses MUD v2.2.15

docs: add changeset for bug fix

---

Dockerfile

I think the error I am seeing in https://github.com/latticexyz/mud/actions/runs/12892450708/job/35947142354 is due to race conditions? Going to switch this over to turbo to see if that helps

build: use turbo in docker build

---

.changeset/olive-countries-visit.md
packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/SQLEditor.tsx
packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/TablesViewer.tsx

Until now, it was only possible to execute query if it changed because the `useTableDataQuery` hook would only rerun in case `query` changed. Now calling `refetch()` explicitly to trigger new table data fetch.

feat(explorer): enable re-executing query

---

.changeset/thin-pianos-repair.md
packages/explorer/src/app/(explorer)/api/sqlite-indexer/route.ts

Explorer used to throw an error in case of empty results when using local indexer. Now returning an empty array instead of throwing an error.

fix(explorer): return empty array for empty results (sqlite indexer)

---

packages/create-mud/scripts/copy-templates.ts
packages/create-mud/src/bin/cli.ts

npm excludes `.gitignore` when packaging and publishing, so although these were getting copied with build, they were missing from npm artifacts:
https://www.npmjs.com/package/create-mud/v/2.2.17-86f455c0a09d5d8af64d030669ebf30ffa71420b?activeTab=code
we resolve this by moving the file aside and moving it back when creating the template
no changeset because these new templates aren't published yet and this fix is captured under existing changesets

fix(create-mud): ensure gitignore is copied

---

.changeset/warm-rules-listen.md
packages/cli/src/deploy/logsToWorldDeploy.ts

Fixes #3305 – quick fix to add `getAddress` to checksum these (`viem` bug).

fix(cli): checksum deployed world addresses

---

packages/entrykit/src/getSessionSigner.ts

fixes some type issues introduced in https://github.com/latticexyz/mud/pull/3498 and cleans up a bit

refactor(entrykit): clean up session signer

---

.changeset/silly-kids-enjoy.md
packages/cli/src/commands/verify.ts

Usage of system.name can result in an incorrectly abbreviated contract path. Use system.label to ensure the full path is correctly resolved.

fix(cli): use system label when verifying

---

.changeset/famous-doors-listen.md
packages/cli/src/commands/verify.ts
packages/cli/src/verify.ts

The `verify` command currently looks up system addresses using the bytecode artifact without considering library link references. This fix uses the same lookup logic as the `deploy` command to inject these references into the bytecode used for create2 address lookup.

fix(cli): support verifying systems with linked libraries

---

.changeset/empty-shoes-thank.md
packages/store-sync/src/createStoreSync.ts

fixes https://github.com/latticexyz/mud/issues/3516
I don't love that we're kinda lying about the `status` of a transaction in the return value of this, but given that it's our own `WaitForTransactionResult`, this seems fine?

fix(store-sync): handle user ops in waitForTransaction

---

packages/block-logs-stream/src/getLogs.ts

There's a check for `internal_clientOptions` being defined but not if `validateBlockRange` is set to true in `getLogs`

fix(block-logs-stream): add missing check for validateBlockRange

---

.changeset/serious-rules-whisper.md
packages/entrykit/src/common.ts
packages/entrykit/src/getSessionAccount.ts

if you try to use `sessionClient` with a function like `sendUserOperation`, it fails type checking

fix(entrykit): session client uses smart account

---

.changeset/cold-clocks-shout.md
packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/interact/FunctionField.tsx

Fixes #3359 by doing what the user intended and making it clear what to input.

chore(explorer): handle tuples in interact form

---

.changeset/eight-starfishes-tell.md
packages/vite-plugin-mud/README.md
packages/vite-plugin-mud/env.d.ts
packages/vite-plugin-mud/src/plugin.ts
templates/react-ecs/packages/client/src/common.ts
templates/react/packages/client/src/common.ts

`define` values get passed around as JSON, but bigint (still) isn't compatible with built-in JSON methods 😭

fix(vite-plugin-mud): start block as number

---

packages/entrykit/src/EntryKitConfigProvider.tsx

the modal currently isn't themed, just the account button, and it's jarring to go from light-mode rainbowkit to dark-mode entrykit

feat(entrykit): always use rainbowkit dark theme

---

.changeset/tall-days-doubt.md
packages/store-sync/src/postgres-decoded/cleanStrings.ts
packages/store-sync/src/postgres-decoded/createStorageAdapter.ts
packages/store-sync/src/postgres-decoded/removeNullCharacters.ts

Currently an invalid UTF-8 character in a `string` type column makes the decoded postgres indexer error with `PostgresError: invalid byte sequence for encoding "UTF8": 0x00`. This PR adds a cleanup step before upserting values into postgres to remove `0x00` characters.

fix(store-sync): skip invalid utf-8 characters in strings before inserting into postgres

---

packages/common/src/account/kms/kmsKeyToAccount.test.ts
packages/store-sync/src/stash/createStorageAdapter.test.ts
packages/store-sync/src/zustand/createStorageAdapter.test.ts
packages/store/ts/flattenStoreLogs.test.ts
packages/store/ts/getStoreLogs.test.ts
test/with-anvil/src/snapshotAnvilState.ts

trying to address flaky tests in CI
this may leave stuff around in the chain from the deploy in `beforeAll`, so if this doesn't do the trick, we might try adding snapshots back into `beforeAll` but alongside the deploy like
```ts
beforeAll(async () => {
const resetAnvilState = await snapshotAnvilState();
await deployMockGame();
return resetAnvilState;
});
```

test: only snapshot anvil state in beforeEach

---

.changeset/long-dolls-jam.md
.changeset/shy-adults-train.md
packages/common/src/chains/garnet.ts
packages/entrykit/src/EntryKitConfigProvider.tsx

"no bundler" error was being swallowed and resulted in an infinite spinner (will fix the error visibility seperately)
it now looks like:
also added bundler config to garnet chain

fix(entrykit): require bundler

---

.changeset/lemon-rivers-run.md
packages/store-indexer/package.json

`pnpm start:postgres` starts both indexer backend and frontend, `pnpm start:postgres-decoded` was just starting the backend (but docs said it starts both)

chore(store-indexer): start frontend with decoded backend

---

.changeset/ninety-beers-behave.md
packages/world-module-erc20/src/experimental/Constants.sol

This makes it consistent with other modules.

refactor(world-module-erc20): change erc20 module table names to pascal case

---

packages/abi-ts/tsup.config.ts
packages/block-logs-stream/tsup.config.ts
packages/cli/tsup.config.ts
packages/common/tsup.config.ts
packages/config/tsup.config.ts
packages/create-mud/tsup.config.ts
packages/dev-tools/tsup.config.ts
packages/entrykit/tsup.config.ts
packages/explorer/tsup.config.ts
packages/faucet/tsup.config.ts
packages/gas-report/tsup.config.ts
packages/protocol-parser/tsup.config.ts
packages/react/tsup.config.ts
packages/recs/tsup.config.ts
packages/schema-type/tsup.config.ts
packages/solhint-config-mud/tsup.config.ts
packages/solhint-plugin-mud/tsup.config.ts
packages/stash/tsup.config.ts
packages/store-indexer/tsup.config.ts
packages/store-sync/tsup.config.ts
packages/store/tsup.config.ts
packages/utils/tsup.config.ts
packages/vite-plugin-mud/tsup.config.ts
packages/world-module-callwithsignature/tsup.config.ts
packages/world-module-erc20/tsup.config.ts
packages/world-module-metadata/tsup.config.ts
packages/world-modules/tsup.config.ts
packages/world/tsup.config.ts
tsup.config.base.ts

pulled out of https://github.com/latticexyz/mud/pull/3561
intentionally removed minifying because it's 1) much harder to dig through dist source and 2) doesn't improve the package size much and 3) makes build take longer 
likely that the end-user bundle will minify anyway

build: base tsup config

---

.changeset/hip-carpets-shave.md
packages/cli/src/build.ts
packages/cli/src/commands/dev-contracts.ts
packages/cli/src/commands/devnode.ts
packages/cli/src/commands/test.ts
packages/cli/src/commands/trace.ts
packages/cli/src/utils/postDeploy.ts
packages/cli/src/utils/printCommand.ts
packages/cli/src/verify/verifyContract.ts
packages/common/src/foundry/index.ts

fixes https://github.com/latticexyz/mud/issues/3560
and improves output (color is preserved, commands are easier to identify)

fix(cli): use execa directly instead of custom foundry wrappers

---

.changeset/clean-apricots-hide.md
.changeset/gorgeous-falcons-roll.md
docs/pages/guides/modules.mdx
docs/pages/world/reference/internal/init-module.mdx
docs/pages/world/reference/module.mdx
packages/world-module-callwithsignature/src/CallWithSignatureModule.sol
packages/world-module-erc20/src/experimental/ERC20Module.sol
packages/world-module-metadata/src/MetadataModule.sol
packages/world-modules/src/modules/erc20-puppet/ERC20Module.sol
packages/world-modules/src/modules/erc721-puppet/ERC721Module.sol
packages/world-modules/src/modules/keysintable/KeysInTableModule.sol
packages/world-modules/src/modules/keyswithvalue/KeysWithValueModule.sol
packages/world-modules/src/modules/puppet/PuppetModule.sol
packages/world-modules/src/modules/std-delegations/StandardDelegationsModule.sol
packages/world-modules/src/modules/uniqueentity/UniqueEntityModule.sol
packages/world/src/Module.sol
packages/world/src/modules/init/InitModule.sol

mostly a clean up thing that has been bugging me
this means module authors don't need to implement this revert on their own, they just have to implement the install method that is appropriate

refactor(world): add default-reverting methods to Module

---

.changeset/rich-islands-stare.md
packages/world-consumer/src/examples/SimpleVault.sol
packages/world-consumer/src/experimental/WorldConsumer.sol
packages/world-consumer/test/WorldConsumer.t.sol
packages/world-module-erc20/gas-report.json
packages/world-module-erc20/src/examples/ERC20PausableBurnable.sol
packages/world-module-erc20/src/experimental/Constants.sol
packages/world-module-erc20/src/experimental/ERC20Module.sol
packages/world-module-erc20/src/experimental/ERC20Pausable.sol
packages/world-module-erc20/src/experimental/MUDERC20.sol
packages/world-module-erc20/src/experimental/Pausable.sol
packages/world-module-erc20/test/ERC20BaseTest.t.sol
packages/world-module-erc20/test/ERC20Burnable.t.sol
packages/world-module-erc20/test/ERC20Module.t.sol
packages/world-module-erc20/test/ERC20Pausable.t.sol

- WorldConsumer now doesn't keep track of a namespace
- Added `onlyNamespace(namespace)` and `onlyNamespaceOwner(namespace)` modifiers
- MUDERC20:
- now receives table ids as constructor args
- example token deployed by module now has an `initialize()` function that can only be called by namespaceOwner. This function sets the metadata and initial paused state.

refactor(world-consumer): remove namespace

---

packages/entrykit/src/store.ts

Without this check, importing entrykit in a nodejs environment will cause the following errors:
```
ReferenceError: window is not defined
at eval (../../../src/store.ts:30:0)
```

fix(entrykit): add a defined check for window

---

.changeset/dry-yaks-kiss.md
packages/common/src/chains/pyrope.ts

There is no wiresaw deployed to Pyrope yet, but the wiresaw rpc url in the chain config caused the sync stack to wait for wiresaw events.

fix: remove wiresaw from pyrope chain definition

---

.changeset/poor-apples-roll.md
packages/world/ts/node/render-solidity/worldgen.ts

Currently it is not possible generate libraries for systems configured to not register as world functions. This restriction is not necessary, as libraries don't depend on the world's interface.

fix(world): support generating libraries for systems without function registration

---

.changeset/thin-insects-draw.md
packages/world/ts/node/render-solidity/renderSystemLibrary.ts

This is needed so that systems can have functions with arguments that don't have a name (useful if you are making the system inherit from an interface and are not using all args). In the current implementation you would get a compile error due to the encoding of the system calls.

fix(world): support functions with missing argument names in system libraries

---

.changeset/hot-bananas-invite.md
packages/store-sync/src/stash/createStorageAdapter.ts

If there is a pending deletion, `value` is undefined. If there is another `Store_SpliceStaticData` update, we previously passed in a partial record (consisting of only the key) to `encodeValueArgs`, which would throw an error when trying to encode the missing fields. Now we're handling this case by setting the `previousValue` to `undefined`, just like it would be if the pending deletion was already applied.

fix(store-sync): handle pending deletion in stash storage adapter

---

.changeset/happy-melons-own.md
packages/store-indexer/package.json
packages/store-indexer/src/sqlite/apiRoutes.ts
packages/store-indexer/src/sqlite/formatSqlQuery.test.ts
packages/store-indexer/src/sqlite/formatSqlQuery.ts
pnpm-lock.yaml

Currently, local SQLite indexer stores column as kebab case. In order to conform to SQL API queries format, camelCase column names are converted to snake_case automatically.

feat(store-indexer): format sql queries

---

.changeset/famous-experts-deliver.md
.github/actions/setup-prerequisites/action.yml
packages/entrykit/src/onboarding/GasBalance.tsx
packages/entrykit/src/onboarding/common.ts
packages/entrykit/src/onboarding/quarry/Allowance.tsx
packages/entrykit/src/onboarding/usePrerequisites.ts

min gas balance wasn't a requirement for returning a complete session account but was required for getting through onboarding steps in entrykit
for now, we'll remove the min gas balance and just require anything >0

feat(entrykit): loosen min gas balance

---

.changeset/seven-pets-sell.md
packages/entrykit/src/onboarding/usePrerequisites.ts

- Currently a balance of 0 passes the top up step, but the balance should be non-zero
- Otherwise it assumes the step is done, and doesnt show the app wallet address
- Also, the delegation tx fails and the user cant get pass the onboarding

fix(entrykit): make required gas balance non-zero

---

.changeset/blue-gorillas-buy.md
packages/store-sync/src/createPreconfirmedBlockStream.ts
packages/store-sync/src/watchLogs.ts

* attempt to prevent dangling http connections we're seeing in wiresaw infra metrics
* wait before reconnecting if precious connection attempt failed

fix(store-sync): backoff on failed connection, close websockets

---

packages/store-sync/src/createPreconfirmedBlockStream.ts

followup to #3762 
The type of `preconfirmedTransactionLogs[txHash]` was inferred at non-null, but it can be null if we haven't seen this transaction in the preconfirmed stream.

fix(store-sync): preconfirmedLogs can be undefined

---

packages/entrykit/src/useSessionClientReady.ts

We don't need the connector until the modal is open and we're requesting signatures from the user. This avoids a flash of unconnected state.

fix(entrykit): don't wait for connector when returning session client

---

packages/entrykit/src/useSessionClientReady.ts

Reverts latticexyz/mud#3768
For some reason, this causes the ConnectKit modal to open automatically, which is not what we want. Need to do a deeper dive into this.

Revert "fix(entrykit): don't wait for connector when returning session client"

---

docs/pages/guides/hello-world/add-chain-client.mdx

Replaced the outdated link to the non-existent "getting-started" file with the correct "vanilla" template guide in the add-chain-client tutorial. This ensures users are directed to the appropriate setup instructions for the vanilla TypeScript template.

docs: fix template link

---

.changeset/pink-hats-sip.md
packages/store-sync/src/watchLogs.ts

changed `ws.on` to `ws.addEventListener` for better cross environment compatibility

fix(store-sync): update watchLogs websocket api

---

.changeset/funny-otters-explode.md
packages/store-sync/src/createStoreSync.ts

if you lose connection (internet connection or remote server dies), this retry loop will get stuck in an infinite loop, block the main thread, and make the browser/tab unresponsive

fix(store-sync): block stream retry backoff
