- packages/services/cmd/ecs-snapshot/main.go
- packages/services/cmd/ecs-stream/main.go
- packages/services/go.mod
- packages/services/go.sum
- packages/services/pkg/ecs/ecs.go
- packages/services/pkg/eth/client.go
- packages/services/pkg/eth/events.go
- packages/services/pkg/eth/logs.go
- packages/services/pkg/grpc/server.go
- packages/services/pkg/grpc/snapshot.go
- packages/services/pkg/grpc/stream.go
- packages/services/pkg/logger/logger.go
- packages/services/pkg/multiplexer/multiplexer.go
- packages/services/pkg/snapshot/constants.go
- packages/services/pkg/snapshot/core.go
- packages/services/pkg/snapshot/snapshot.go
- packages/services/pkg/snapshot/state.go
- packages/services/pkg/snapshot/sync.go
- packages/services/pkg/stream/core.go
- packages/services/pkg/utils/address.go
- packages/services/pkg/utils/constants.go
- packages/services/pkg/utils/io.go
- packages/services/pkg/utils/retry.go
Adds go doc comments to mud services
> docs(services): add go doc comments

- packages/phaserx/src/createInput.ts
- Due to a race condition between the `mousedown`/`mouseup` events and Phaser's `pointer.leftButtonDown`, the `click$` stream would not fire on every click. This PR changes the internal logic to use to `mousedown`/`mouseup` as source of truth for the click$ stream.
> fix: phaser input click$ stream

- packages/recs/src/Component.ts
- add mvp of `createLocalCache`
> feat(recs): add local cache component

- packages/network/src/createFaucetService.ts
- packages/network/src/index.ts
> feat(network): add util for creating faucet service

- packages/services/Makefile
- packages/services/cmd/ecs-snapshot/main.go
- packages/services/pkg/grpc/server.go
- packages/services/pkg/grpc/snapshot.go
- packages/services/pkg/snapshot/constants.go
- packages/services/pkg/snapshot/core.go
- packages/services/pkg/snapshot/snapshot.go
- packages/services/pkg/snapshot/sync.go
- packages/services/pkg/utils/address.go
- Clean up code around allowing sync from block via param
- Lookup snapshots by checksumming the address in RPC requests (avoid mismatch of lowercases)
- Move more params to flags for snapshot service for easier tweaks
- Rewrite server code to have more code reuse
> feat: general service improvements

- packages/network/src/createTxQueue.ts
- packages/network/src/workers/Sync.worker.ts
- packages/network/src/workers/syncUtils.ts
- packages/std-client/src/setup/setupMUDNetwork.ts
Added some additional logging tags (eg: "[SyncWorker]") to make logs clearer
> chore: better logging

- packages/solecs/src/BareComponent.sol
- packages/solecs/src/interfaces/IComponent.sol
- packages/std-contracts/src/components/AddressBareComponent.sol
- packages/std-contracts/src/components/BoolBareComponent.sol
- packages/std-contracts/src/components/CoordBareComponent.sol
- packages/std-contracts/src/components/FunctionBareComponent.sol
- packages/std-contracts/src/components/Int32BareComponent.sol
- packages/std-contracts/src/components/StringArrayBareComponent.sol
- packages/std-contracts/src/components/StringArrayComponent.sol
- packages/std-contracts/src/components/StringBareComponent.sol
- packages/std-contracts/src/components/Uint256ArrayBareComponent.sol
- packages/std-contracts/src/components/Uint256BareComponent.sol
- packages/std-contracts/src/components/Uint32ArrayBareComponent.sol
- packages/std-contracts/src/components/Uint32BareComponent.sol
- packages/std-contracts/src/components/Uint32Component.sol
- packages/std-contracts/src/components/VoxelCoordBareComponent.sol
- Add BareComponent for gas savings if reverse mapping is not needed
> feat: add BareComponent

- packages/std-contracts/src/components/Uint32Component.sol
> fix(std-contracts): fix name of Uint32Component

- packages/mud.dev/src/App.tsx
> chore: add discord banner to mud.dev

- packages/recs/src/Component.ts
- packages/std-client/src/setup/setupMUDNetwork.ts
- allow components to be registered in the client sync after the initial setup
> feat: expose registerComponent method from setupMUDNetwork

- packages/std-contracts/src/systems/UpgradableSystem.sol
Add UpgradableSystem as proxy to make other systems upgradable
> feat: add UpgradableSystem

- packages/std-client/src/setup/setupMUDNetwork.ts
We were exiting out of the for loop when encountering an unknown component while reducing component update events instead of just skipping the individual event
> fix: avoid early return for unknown components

- packages/network/src/index.ts
> feat(network): export createBlockNumberStream

- packages/solecs/README.md
Few minor edits in README of solecs package
> docs(solecs): fix typos

- packages/network/src/createSystemExecutor.ts
- packages/std-client/src/setup/index.ts
- packages/std-client/src/setup/setupMUDNetwork.ts
- packages/std-client/src/setup/types.ts
- packages/std-client/src/setup/utils.ts
Add support when using the Streaming service. Currently only supports events over RPC.
Relevant RFC for Streaming service support: https://www.notion.so/latticexyz/System-Call-Events-in-Stream-Service-b04601c721c644859e890e2cee984c17
> feat(network,std-client): add support for SystemCall events in default MUD network setup

- packages/solecs/src/BareComponent.sol
- packages/solecs/src/Component.sol
Allow overriding Component logic (except access control)
And add some code reuse internally so Component inherits BareComponent
> feat(solecs): better inheritance for Component and BareComponent

- packages/cli/package.json
- packages/cli/src/commands/system-types.ts
- packages/cli/src/commands/types.ts
- yarn.lock
Integrates the TypeChain ethers types generation into the mud cli
> feat(cli): integrate TypeChain into mud cli

- packages/services/README.md
- packages/services/cmd/ecs-relay/main.go
- packages/services/cmd/ecs-snapshot/main.go
- packages/services/cmd/ecs-stream/main.go
- packages/services/cmd/faucet/main.go
> docs: services

- packages/cli/src/utils/hsr.ts
Hot reloading would fail when trying to generate a deploy script if you had a circular dependency in Solidity (A.sol imports B.sol and B.sol imports A.sol). Since Solidity compiles circular dependencies fine, I felt like it was probably best to just fix the module resolution here (with a warning) rather than preventing circular deps.
> fix: cli issue with circular dependencies

- packages/solecs/src/Ownable.sol
https://github.com/latticexyz/mud/pull/265#discussion_r1065996811
Fixes compliance with EIP-173 and makes the code look a bit better
> fix(solecs): use _setOwner in Ownable constructor

- packages/phaserx/src/createEmbodiedEntity.ts
this was the cause of another spooky disappearing sprite bug for me
> fix(phaserx): reset game object masks when resetting embodied entity

- packages/network/src/createTxQueue.ts
> fix(network): throw errors from txQueue calls

- tutorials/emojimon/step-0.md
- tutorials/emojimon/step-10/step-10.3.md
- tutorials/emojimon/step-10/step-10.5.md
- tutorials/emojimon/step-10/step-10.6.md
- tutorials/emojimon/step-10/step-10.7.md
- tutorials/emojimon/step-11.md
- tutorials/emojimon/step-12.md
- tutorials/emojimon/step-13.md
- tutorials/emojimon/step-7/step-7.2.md
- tutorials/emojimon/step-8.md
- tutorials/emojimon/step-9.md
A continuation of #360  (we merged early in prep for a workshop)
Follow ups noted in #384
> docs: emojimon tutorial (part 2)

- packages/solecs/src/OwnableWritable.sol
Make it possible to customize component write access.
> fix(solecs): make OwnableWritable overridable

- README.md
- retype.yml
Follows up https://github.com/latticexyz/lattice.xyz/pull/2
> docs: update discord links

- packages/store/gas-report.txt
- packages/store/src/PackedCounter.sol
- packages/store/src/Schema.sol
- packages/store/src/StoreCore.sol
- packages/store/src/Types.sol
- packages/store/src/schemas/AddressArray.sol
- packages/store/src/schemas/CallbackArray.sol
- packages/store/src/schemas/Mixed.sol
- packages/store/src/schemas/Route.sol
- packages/store/src/schemas/Vector2.sol
- packages/store/test/Schema.t.sol
- packages/store/test/StoreCore.t.sol
Here I just refactor types, they're used and tested in #396
> feat(store): expand schema type

- packages/create-mud/templates/minimal/packages/client/.eslintrc
- packages/create-mud/templates/minimal/packages/client/tsconfig.json
- packages/create-mud/templates/react/packages/client/.eslintrc
- packages/create-mud/templates/react/packages/client/tsconfig.json
(ported from emojimon tutorial)
> fix(create-mud): small linting/type fixes for templates

- tutorials/emojimon/step-0.md
- tutorials/emojimon/step-1.md
- tutorials/emojimon/step-10/step-10.1.md
- tutorials/emojimon/step-10/step-10.2.md
- tutorials/emojimon/step-10/step-10.3.md
- tutorials/emojimon/step-10/step-10.4.md
- tutorials/emojimon/step-10/step-10.5.md
- tutorials/emojimon/step-10/step-10.6.md
- tutorials/emojimon/step-10/step-10.7.md
- tutorials/emojimon/step-11.md
- tutorials/emojimon/step-2.md
- tutorials/emojimon/step-3.md
- tutorials/emojimon/step-4.md
- tutorials/emojimon/step-5.md
- tutorials/emojimon/step-6.md
- tutorials/emojimon/step-7/step-7.1.md
- tutorials/emojimon/step-7/step-7.2.md
- tutorials/emojimon/step-7/step-7.3.md
- tutorials/emojimon/step-8.md
- tutorials/emojimon/step-9.md
Walking through the tutorial and updating the code at the same time.
> docs(emojimon): refresh emojimon tutorial with mud 1.39.0

- packages/phaserx/src/createEmbodiedEntity.ts
this is very helpful when debugging object pool issues
> feat(phaserx): tag native phaser game objects with object pool id

- packages/world/src/schemas/SystemSchema.sol
Pulling this fix out of https://github.com/latticexyz/mud/pull/415
> fix(world): fix schema order

- packages/cli/src/commands/deploy-v2.ts
- packages/cli/src/config/commonSchemas.ts
- packages/cli/src/config/loadWorldConfig.ts
- packages/cli/src/config/validation.ts
Fix to allow usage of cli utils in other non-nodejs packages
> fix(cli): avoid fs usage in utils, create deployment output directory if it doesn't exist

- packages/cli/modules.d.ts
- packages/services/Makefile
- packages/services/protobuf/ts/ecs-relay/ecs-relay.ts
- packages/services/protobuf/ts/ecs-snapshot/ecs-snapshot.ts
- packages/services/protobuf/ts/ecs-stream/ecs-stream.ts
- packages/services/protobuf/ts/faucet/faucet.ts
> fix(services): fix protobuf imports

- packages/store/src/IErrors.sol
- packages/store/src/IStore.sol
- packages/store/src/StoreCore.sol
- packages/store/test/StoreCore.t.sol
- packages/world/src/World.sol
- packages/world/src/interfaces/IWorldCore.sol
fixes https://github.com/latticexyz/mud/issues/559
Since systems are called via IWorld, I assume `System` doesn't need to inherit `IErrors`?
> feat: use IErrors in IStore and IWorldCore

- packages/cli/src/render-solidity/renderSystemInterface.ts
- packages/cli/src/render-solidity/types.ts
- packages/cli/src/utils/contractToInterface.ts
includes `payable`, `view`, `pure` in system interfaces
related to https://github.com/latticexyz/mud/pull/568
> feat(cli): include stateMutability in worldgen

- packages/services/package.json
- packages/services/protobuf/ts/ecs-relay/ecs-relay.ts
- packages/services/protobuf/ts/ecs-snapshot/ecs-snapshot.ts
- packages/services/protobuf/ts/ecs-stream/ecs-stream.ts
- packages/services/protobuf/ts/faucet/faucet.ts
- packages/services/protobuf/ts/mode/mode.ts
- packages/services/tsconfig.json
- yarn.lock
pulled out of https://github.com/latticexyz/mud/pull/591
> build(services): bump ts proto deps, rebuild

- templates/minimal/packages/client/src/config.ts
- templates/minimal/packages/contracts/package.json
- templates/react/packages/client/src/config.ts
- templates/react/packages/contracts/package.json
https://github.com/latticexyz/issues/issues/81
> refactor(create-mud): templates disable cache in dev

- .github/workflows/release.yml
missed this in https://github.com/latticexyz/mud/pull/640
> fix: fix codegen command in release workflow

- packages/services/package.json
forgot to adjust the name in https://github.com/latticexyz/mud/pull/633
> build(services): rename build:codegen step to build:protobuf

- examples/v2-minimal/packages/contracts/package.json
- examples/v2-minimal/pnpm-lock.yaml
- templates/minimal/packages/contracts/package.json
- templates/react/packages/contracts/package.json
pulled out of https://github.com/latticexyz/mud/pull/669 (should have been in #670)
> chore: align @types/node version

- .github/workflows/examples.yml
- .github/workflows/templates.yml
- examples/v2-minimal/package.json
- examples/v2-minimal/packages/client/package.json
- examples/v2-minimal/packages/contracts/types/ethers-contracts/IWorld.ts
- examples/v2-minimal/packages/contracts/types/ethers-contracts/factories/IWorld__factory.ts
- packages/create-mud/README.md
CI didn't catch the pop changes for examples project
> ci: initialize examples, check for outdated files

- .github/actions/setup/action.yml
https://github.com/arduino/setup-protoc#usage
> ci: add token to fix protoc rate limiting

- .github/workflows/examples.yml
- .gitignore
- examples/v2-minimal/package.json
- examples/v2-minimal/packages/contracts/.env
- examples/v2-minimal/packages/contracts/.gitignore
- examples/v2-minimal/packages/contracts/script/PostDeploy.s.sol
Next would be good to add a workflow to actually run these tests in CI
> docs(examples): add PostDeploy, test examples

- packages/common/src/codegen/utils/contractToInterface.ts
fixes https://github.com/latticexyz/mud/issues/719
> fix(world): within worldgen allow identifiers as static array lengths

- packages/config/src/library/validation.ts
- packages/std-client/src/mud-definitions/world/contractComponents.ts
- packages/store/ts/library/config/index.ts
- packages/world/mud.config.ts
- packages/world/src/modules/core/tables/FunctionSelectors.sol
- packages/world/ts/library/config/resolveWorldConfig.ts
fixes https://github.com/latticexyz/mud/issues/706
> feat: limit default selector names to 16 bytes

- packages/store/package.json
- packages/store/ts/library/config/index.ts
- packages/store/ts/register/index.test.ts
- packages/store/ts/register/index.ts
- packages/world/package.json
- packages/world/ts/library/config/resolveWorldConfig.ts
- packages/world/ts/register/index.test.ts
- packages/world/ts/register/index.ts
fixes https://github.com/latticexyz/mud/issues/707
> feat: require unique table and system names

- examples/minimal/packages/contracts/types/ethers-contracts/IWorld.ts
- examples/minimal/packages/contracts/types/ethers-contracts/factories/IWorld__factory.ts
- integration-sandbox/packages/contracts/types/ethers-contracts/IWorld.ts
- integration-sandbox/packages/contracts/types/ethers-contracts/factories/IWorld__factory.ts
- packages/cli/contracts/src/codegen/tables/Dynamics.sol
- packages/cli/contracts/src/codegen/tables/Singleton.sol
- packages/cli/contracts/test/Tablegen.t.sol
- packages/common/src/codegen/render-solidity/renderTypeHelpers.ts
- packages/store/gas-report.json
- packages/store/src/IStore.sol
- packages/store/src/StoreCore.sol
- packages/store/src/StoreRead.sol
- packages/store/src/StoreSwitch.sol
- packages/store/src/codegen/tables/Callbacks.sol
- packages/store/src/codegen/tables/Hooks.sol
- packages/store/src/codegen/tables/Mixed.sol
- packages/store/src/codegen/tables/StoreMetadata.sol
- packages/store/test/StoreCore.t.sol
- packages/store/test/StoreCoreDynamic.t.sol
- packages/store/ts/library/render-solidity/field.ts
- packages/world/gas-report.json
- packages/world/src/modules/keysintable/tables/KeysInTable.sol
- packages/world/src/modules/keyswithvalue/tables/KeysWithValue.sol
- packages/world/test/tables/AddressArray.sol
fixes https://github.com/latticexyz/mud/issues/735
fixes https://github.com/latticexyz/mud/issues/736
World size changed less than I expected: 21.564 -> 22.167
> feat(store): add getFieldLength and getFieldSlice

- packages/dev-tools/package.json
- packages/dev-tools/tsup.config.ts
- pnpm-lock.yaml
> fix(dev-tools): bundle non-mud deps

- packages/store/ts/library/render-solidity/tableOptions.ts
- packages/store/ts/library/render-solidity/tablegen.ts
followup to #851 - unfortunately I added the regex at the wrong place
> fix(store): replace windows path separator with posix path separator

- docs/pages/client-side.mdx
- docs/pages/world/world-101.mdx
the current docs interpret this as a relative link
> docs: fix link to emergence.land

- packages/network/jest.config.js
- packages/network/package.json
- packages/network/src/createNetwork.ts
- pnpm-lock.yaml
> fix(network): connect to mud chains before public chains

- templates/react/package.json
- templates/vanilla/package.json
git bash on windows doesn't like single quotes
> fix(templates): fix dev script for windows

- packages/create-mud/scripts/copy-templates.sh
- packages/solhint-plugin-mud/package.json
- templates/phaser/packages/contracts/.solhint.json
- templates/phaser/packages/contracts/package.json
- templates/react/packages/contracts/.solhint.json
- templates/react/packages/contracts/package.json
- templates/vanilla/packages/contracts/.solhint.json
- templates/vanilla/packages/contracts/package.json
needs the plugin to be published to work correctly
> feat(create-mud): use solhint-plugin-mud in templates

- README.md
Adds a link to mud 101 to the README.md.  This should help adoption with folks who are curious to learn more.
> docs: add mud 101 to README

- README.md
updates to the reuploaded MUD 101 video without audio bugs
> docs: update MUD 101 video

- packages/dev-tools/src/summary/NetworkSummary.tsx
- packages/dev-tools/src/useStore.ts
- packages/network/src/dev/observables.ts
- packages/network/src/workers/SyncWorker.ts
See https://github.com/latticexyz/mud/issues/777
> feat(dev-tools): add world address

- packages/noise/contracts/Perlin.sol
fixes #935 
* tooling for deploying public libraries is bad and with MUD2 using (private) systems is preferable to public libraries
> feat(perlin): change function visibility to internal

- packages/network/src/createNetwork.ts
- packages/network/src/types.ts
- allow passing in chain config
- don't explode if we can't construct viem clients (just used by dev tools right now)
> feat(network): allow passing in chain config

- docs/pages/store/_meta.js
- docs/pages/store/internals.mdx
- docs/pages/world/_meta.js
- docs/pages/world/internals.mdx
- docs/pages/world/modules.mdx
seen a couple people ask about some internals, like how to get a system's address
should also be useful for ourselves, I don't think we have a good summary of internals atm (I guess mud.config, but it doesn't have systems, which you have to know to look for in core module's folder)
> docs(store,world): add internal tables and systems, update internal modules

- packages/dev-tools/src/actions/TransactionSummary.tsx
> fix(dev-tools): don't explode on logs with missing ABI

- packages/services/pkg/mode/db/api.go
- packages/services/pkg/mode/ingress/handlers.go
- packages/services/pkg/mode/schema/utils.go
- packages/services/pkg/mode/storecore/encoding.go
- packages/services/pkg/mode/write/row.go
Handles singleton table updates, where a setField only updates fields without specifying what the key is (because there are no keys)
> feat(mode): handle singleton table updates

- examples/minimal/packages/contracts/mud.config.ts
- examples/minimal/packages/contracts/script/PostDeploy.s.sol
- examples/minimal/packages/contracts/src/interfaces/IChatNamespacedSystem.sol
- examples/minimal/packages/contracts/src/systems/ChatNamespacedSystem.sol
- examples/minimal/packages/contracts/test/ChatNamespaced.t.sol
test for https://github.com/latticexyz/mud/pull/952
> feat(examples): test ephemeral table within namespaced system

- packages/world/src/Utils.sol
- packages/world/test/Utils.t.sol
fixes https://github.com/latticexyz/mud/issues/978
> feat(world): add systemNamespace util

- .github/workflows/integration-sandbox.yml
- integration-sandbox/packages/client-vanilla/index.html
- integration-sandbox/packages/contracts/test/index.test.ts
did a lot of CI reruns and it's reliably passing now, as long as I wait for setup to finish
> build: re-enable integration sandbox CI

- .github/workflows/examples.yml
- .github/workflows/integration-sandbox.yml
- .github/workflows/templates.yml
- examples/minimal/package.json
- examples/minimal/packages/client-phaser/package.json
- examples/minimal/packages/client-react/package.json
- examples/minimal/packages/client-vanilla/package.json
- examples/minimal/packages/contracts/package.json
- integration-sandbox/packages/contracts/package.json
- integration-sandbox/pnpm-lock.yaml
- templates/phaser/package.json
- templates/phaser/packages/client/package.json
- templates/phaser/packages/contracts/foundry.toml
- templates/phaser/packages/contracts/package.json
- templates/react/package.json
- templates/react/packages/client/package.json
- templates/react/packages/contracts/foundry.toml
- templates/react/packages/contracts/package.json
- templates/threejs/package.json
- templates/threejs/packages/client/package.json
- templates/threejs/packages/contracts/foundry.toml
- templates/threejs/packages/contracts/package.json
- templates/vanilla/package.json
- templates/vanilla/packages/client/package.json
- templates/vanilla/packages/contracts/foundry.toml
- templates/vanilla/packages/contracts/package.json
fixes https://github.com/latticexyz/mud/issues/997
> build(examples,templates): refactor build scripts

- integration-sandbox/packages/client-vanilla/package.json
- integration-sandbox/packages/contracts/package.json
- integration-sandbox/pnpm-lock.yaml
- packages/cli/package.json
- packages/common/package.json
- packages/dev-tools/package.json
- packages/noise/package.json
- packages/react/package.json
- packages/schema-type/package.json
- packages/std-client/package.json
- packages/store-cache/package.json
- packages/store/package.json
- packages/world/package.json
- pnpm-lock.yaml
pulled out of https://github.com/latticexyz/mud/pull/995
> test: bump vitest

- packages/services/README.md
minor fixes to the MODE readme
> docs(services): fix local chain id

- .github/workflows/release.yml
> build: don't use turbo cache in release

- templates/phaser/packages/contracts/script/PostDeploy.s.sol
phaser test is currently failing, there's no CI check for it (there isn't much to check either)
> fix(create-mud): align phaser PostDeploy script

- docs/pages/quick-start.mdx
From `clientComponents.ts` to `createClientComponents.ts`.
> docs: Update the component file name

- packages/world/gas-report.json
- packages/world/test/KeysWithValueModule.t.sol
noticed a typo in https://github.com/latticexyz/mud/pull/1088 after merging
> test(world): fix KeysWithValue test name

- docs/theme.config.tsx
So that **Edit this page** will go to the correct location.
> docs: Update the location of the doc files

- docs/pages/client-side.mdx
Fix documentation errors in useRow/useRows
> docs: fix useRow/useRows usage

- docs/theme.config.tsx
Hopefully this time I got it right.
> docs: Fix `docsRepositoryBase`

- .changeset/many-phones-study.md
- followup to #1099, forgot to add a changeset
> chore(protocol-parser): add changeset for #1099

- packages/schema-type/test/solidity/SchemaType.t.sol
fixes a part of https://github.com/latticexyz/mud/issues/444
> test(schema-type): add more tests

- docs/pages/world/world-101.mdx
> docs: small fixes to world 101

- docs/pages/store/spec.mdx
> docs: fix typo

- docs/pages/world/config.mdx
> docs(config): itemize the items

- .changeset/olive-parrots-move.md
- packages/recs/src/Component.ts
> fix(recs): improve messages for v2 components

- turbo.json
previously just built dependencies rather than self, should now build both!
should help with bootstrapping issues
> build: fix turbo dev

- docs/package.json
- docs/pnpm-lock.yaml
fixes issue with copying code selection (https://github.com/shuding/nextra/pull/1947)
> docs: bump nextra

- .github/workflows/snapshot.yml
Workaround for https://github.com/changesets/changesets/issues/1195, addresses first item of #1187
> chore: fix snapshot release action

- .changeset/dirty-items-retire.md
- change `feat` to `major` in `dirty-items-retire.md`
> chore: fix changeset type

- .changeset/giant-masks-carry.md
- packages/store-sync/src/recs/defineInternalComponents.ts
- packages/store-sync/src/recs/syncToRecs.ts
fixes https://github.com/latticexyz/mud/issues/1226
> feat(store-sync): add block numbers to SyncProgress

- packages/store-sync/src/recs/syncToRecs.ts
oops, this was meant to be in https://github.com/latticexyz/mud/pull/1235
> feat(store-sync): add `startBlock` option to `syncToRecs`

- e2e/packages/client-vanilla/src/mud/contractComponents.ts
- examples/minimal/packages/client-phaser/src/mud/contractComponents.ts
- examples/minimal/packages/client-react/src/mud/contractComponents.ts
- examples/minimal/packages/client-vanilla/src/mud/contractComponents.ts
- packages/cli/src/render-ts/renderRecsV1Tables.ts
- packages/std-client/src/mud-definitions/store/contractComponents.ts
- packages/std-client/src/mud-definitions/world/contractComponents.ts
- templates/phaser/packages/client/src/mud/contractComponents.ts
- templates/react/packages/client/src/mud/contractComponents.ts
- templates/threejs/packages/client/src/mud/contractComponents.ts
- templates/vanilla/packages/client/src/mud/contractComponents.ts
We don't need the closure anymore and removing it makes it easier to read/understand.
> style(cli,create-mud): remove recs components closure

- package.json
- pnpm-lock.yaml
- scripts/changelog.ts
- add a script to generate a global changelog as part of the versioning & pre-release action
> feat: add script to generate global changelog

- docs/pages/store/advanced-features.mdx
- docs/pages/store/config.mdx
- docs/pages/store/reading-and-writing.mdx
- docs/pages/store/spec.mdx
> docs: fixes

- .changeset/smooth-pots-nail.md
- packages/dev-tools/src/recs/ComponentData.tsx
- packages/dev-tools/src/recs/ComponentsPage.tsx
- packages/dev-tools/src/recs/StoreComponentDataTable.tsx
- packages/dev-tools/src/recs/getComponentName.ts
- packages/dev-tools/src/summary/ComponentsSummary.tsx
- packages/store-sync/src/recs/defineInternalComponents.ts
> feat(dev-tools): improve support for non-store recs components

- .changeset/config.json
- packages/network/package.json
- pnpm-lock.yaml
reverts #1320 and tries another fix
see https://github.com/changesets/changesets/discussions/1215
> build: fix changesets for deleted network package

- .changeset/brave-needles-love.md
not sure if this will work since it's now a private/empty package, but let's see!
> docs: changeset for deleted network package

- packages/world/gas-report.json
> test: update gas report

- docs/pages/indexer.mdx
https://github.com/latticexyz/mud/pull/1387 got merged before lint cleared CI
cc @qbzzt
> docs: prettier

- .github/workflows/docker.yml
missed that we needed to configure the workflow for tags being pushed
> build: trigger docker for tag push

- packages/store/src/StoreCore.sol
> docs(store): remove todo

- docs/pages/world/world-101.mdx
> docs: fix link

- docs/pages/world/config.mdx
> docs: fix spelling errors in internal links

- docs/pages/client-side.mdx
Replace the uppercase S of Store with the lowercase s
> docs: Fix challenge failure caused by case errors in client-side.mdx

- packages/block-logs-stream/src/blockRangeToLogs.ts
- packages/block-logs-stream/src/fetchLogs.ts
trying to figure out where the indexer gets stuck
> feat(block-logs-stream): add more logging

- docs/pages/store/advanced-features.mdx
https://mud.dev/store/advanced-features
https://mud.dev/store/tablegen
\_____ error code: 404 (not found)
> docs: fix the incorrect link on the advanced-features page

- .changeset/chatty-news-join.md
- packages/cli/src/commands/dev-contracts.ts
> fix(cli): don't build twice on contract changes

- packages/world/.npmignore
> fix(world): include MudTest in npm package artifact

- .changeset/clever-items-appear.md
- packages/cli/src/commands/trace.ts
- packages/cli/src/utils/deploy.ts
- packages/store/.npmignore
- packages/world/.npmignore
followup to #1483 
- release bytecode of world and store on npm
> fix: release bytecode on npm and import abi in cli deploy

- packages/cli/src/commands/trace.ts
followup to #1490 
(let's wait for CI this time 🙈)
> fix(cli): use IBaseWorld.abi.json in trace.ts

- .changeset/small-boxes-rush.md
- packages/dev-tools/src/actions/WriteSummary.tsx
will follow with the refactor noted in https://github.com/latticexyz/mud/pull/1354/files#diff-eab70e6cd2e61a3b84cd264fbf86739f953fd5d675d482bca309d885018cc825R135
> fix(dev-tools): table -> tableId

- .changeset/nasty-trains-drop.md
forgot a changeset in https://github.com/latticexyz/mud/pull/1384
> docs: cli changeset after deploy changes

- .changeset/silly-snakes-fold.md
- packages/dev-tools/src/actions/WriteSummary.tsx
fixes #1504 
missed this in https://github.com/latticexyz/mud/pull/1502
> fix(dev-tools): key -> keyTuple

- .changeset/proud-insects-perform.md
- packages/store-indexer/bin/postgres-indexer.ts
- packages/store-indexer/bin/sqlite-indexer.ts
- packages/store-indexer/package.json
- packages/store-indexer/tsup.config.ts
- pnpm-lock.yaml
> feat(store-indexer): run indexers with npx

- .changeset/lovely-fireants-behave.md
- packages/world/mud.config.ts
- packages/world/src/Delegation.sol
- packages/world/src/SystemCall.sol
- packages/world/src/World.sol
- packages/world/src/WorldContext.sol
- packages/world/src/interfaces/IDelegationControl.sol
- packages/world/src/interfaces/ISystemHook.sol
- packages/world/src/interfaces/IWorldKernel.sol
- packages/world/src/interfaces/IWorldRegistrationSystem.sol
- packages/world/src/modules/core/CoreModule.sol
- packages/world/src/modules/core/implementations/ModuleInstallationSystem.sol
- packages/world/src/modules/core/implementations/StoreRegistrationSystem.sol
- packages/world/src/modules/core/implementations/WorldRegistrationSystem.sol
- packages/world/src/modules/std-delegations/CallboundDelegationControl.sol
- packages/world/src/modules/std-delegations/TimeboundDelegationControl.sol
- packages/world/src/modules/std-delegations/tables/CallboundDelegations.sol
- packages/world/test/World.t.sol
- packages/world/test/WorldContext.t.sol
> feat(world): rename `funcSelectorAndArgs` to `callData`

- packages/world/gas-report.json
- packages/world/src/Delegation.sol
- packages/world/src/World.sol
- packages/world/src/interfaces/IDelegationControl.sol
- packages/world/src/modules/core/implementations/ModuleInstallationSystem.sol
- packages/world/src/modules/core/implementations/StoreRegistrationSystem.sol
- packages/world/test/StandardDelegationsModule.t.sol
- packages/world/test/Utils.t.sol
- packages/world/test/World.t.sol
- packages/world/test/WorldContext.t.sol
closes https://github.com/latticexyz/mud/issues/1525
> refactor(world): use abi.encodeCall instead of abi.encodeWithSelector

- packages/store/src/version.sol
- packages/world/src/version.sol
we should merge this just before we do the prerelease
> feat(store,world): set version

- .changeset/real-crews-hide.md
- packages/cli/src/utils/deploy.ts
followup to prevent this in the future: #1620
> fix(cli): register namespace with namespaceId

- .changeset/nice-bikes-double.md
> docs: changeset for indexer/store sync table IDs param

- .gitattributes
- templates/phaser/.gitattributes
- templates/react/.gitattributes
- templates/threejs/.gitattributes
- templates/vanilla/.gitattributes
I noticed while updating emojimon that the diffs had a lot of codegen stuff, so this should help with some nicer defaults.
closes #1679
> chore: add gitattributes to templates

- packages/store/ts/storeEvents.test.ts
- packages/store/ts/storeEvents.ts
- packages/store/ts/storeEventsAbi.test.ts
pulled out of https://github.com/latticexyz/mud/pull/1702
> feat(store): add HelloStore event to TS event definitions

- .changeset/chatty-planets-heal.md
> docs(world): add changeset for system call helpers

- .changeset/gold-rings-switch.md
- .changeset/plenty-guests-hunt.md
- packages/common/src/codegen/debug.ts
- packages/common/src/codegen/utils/formatAndWrite.ts
- packages/store/ts/codegen/tablegen.ts
this was feeling slow when watching logs, but not sure this actually helps much!
> feat(store): parallelize table codegen

- packages/common/src/hexToResource.ts
spotted this bad error message when attempting to connect to an old world
> fix(common): improve hexToResource error when type is invalid

- .changeset/cyan-baboons-breathe.md
- .changeset/rude-cycles-travel.md
- package.json
- packages/world-modules/gas-report.json
- packages/world-modules/src/modules/keysintable/KeysInTableModule.sol
- packages/world-modules/src/modules/keyswithvalue/KeysWithValueModule.sol
- packages/world-modules/src/modules/uniqueentity/UniqueEntityModule.sol
- packages/world-modules/test/KeysInTableModule.t.sol
- packages/world-modules/test/KeysWithValueModule.t.sol
- packages/world-modules/test/UniqueEntityModule.t.sol
- packages/world/src/IModule.sol
lazy/naive fix so we can catch these errors during deploys and not panic
> feat(world-modules): only install modules once

- packages/store-sync/src/createStoreSync.ts
> fix(store-sync): recs progress percentage should be out of 100

- templates/phaser/packages/client/src/mud/createSystemCalls.ts
- templates/phaser/packages/client/src/mud/setupNetwork.ts
- templates/react/packages/client/src/mud/createSystemCalls.ts
- templates/react/packages/client/src/mud/setupNetwork.ts
- templates/threejs/packages/client/src/mud/createSystemCalls.ts
- templates/threejs/packages/client/src/mud/setupNetwork.ts
- templates/vanilla/packages/client/src/mud/createSystemCalls.ts
- templates/vanilla/packages/client/src/mud/setupNetwork.ts
Except for links to the deploy article, I'll do that after it is updated.
> docs(template): fix links to the source code and to the mud.dev

- .changeset/bright-flies-hug.md
- packages/cli/src/commands/dev-contracts.ts
> fix(cli): don't bail dev-contracts during deploy failure

- packages/world-modules/src/modules/erc20-puppet/ERC20Module.sol
- packages/world-modules/src/modules/erc721-puppet/ERC721Module.sol
> fix(world-modules): reduce ERC721Module and ERC20Module contract sizes

- .changeset/heavy-rings-punch.md
- examples/minimal/packages/contracts/package.json
- examples/minimal/pnpm-lock.yaml
- package.json
- packages/common/package.json
- pnpm-lock.yaml
- templates/phaser/packages/contracts/package.json
- templates/react-ecs/packages/contracts/package.json
- templates/react/packages/contracts/package.json
- templates/threejs/packages/contracts/package.json
- templates/vanilla/packages/contracts/package.json
react template seems broken, potentially due to latest release of prettier-plugin-solidity
> fix(create-mud): pin prettier-plugin-solidity

- .changeset/hip-files-sin.md
- .changeset/proud-turkeys-compete.md
- examples/minimal/packages/client-vanilla/src/index.ts
- packages/dev-tools/package.json
- packages/dev-tools/src/App.tsx
- packages/dev-tools/src/RootPage.tsx
- packages/dev-tools/src/TruncatedHex.tsx
- packages/dev-tools/src/common.ts
- packages/dev-tools/src/recs/getComponentName.ts
- packages/dev-tools/src/router.tsx
- packages/dev-tools/src/summary/SummaryPage.tsx
- packages/dev-tools/src/summary/TablesSummary.tsx
- packages/dev-tools/src/zustand/FieldValue.tsx
- packages/dev-tools/src/zustand/TableData.tsx
- packages/dev-tools/src/zustand/TableDataTable.tsx
- packages/dev-tools/src/zustand/TablesPage.tsx
- packages/dev-tools/src/zustand/useRecords.ts
- packages/dev-tools/src/zustand/useTables.ts
- packages/store-sync/src/zustand/createStorageAdapter.test.ts
- packages/store-sync/src/zustand/createStorageAdapter.ts
- packages/store-sync/src/zustand/createStore.ts
- pnpm-lock.yaml
- templates/react/packages/client/src/index.tsx
> feat(dev-tools): show zustand tables

- next-docs/pages/cli/deploy.mdx
- next-docs/pages/guides/hello-world/_meta.js
- next-docs/pages/guides/hello-world/deploy.mdx
Also, have the guide/hello-world redirect there.
> docs(cli): add `mud deploy` to newdocs

- .changeset/brave-islands-wash.md
- packages/cli/src/deploy/common.ts
- packages/cli/src/deploy/deploy.ts
- packages/cli/src/deploy/ensureContract.ts
- packages/cli/src/deploy/ensureModules.ts
- packages/cli/src/deploy/ensureSystems.ts
- packages/cli/src/deploy/ensureWorldFactory.ts
- packages/cli/src/deploy/getSystems.ts
- packages/cli/src/deploy/resolveConfig.ts
- packages/cli/src/utils/modules/constants.ts
- packages/cli/src/utils/utils/getContractData.ts
> feat(cli): warn when contract is over or close to the size limit

- .changeset/purple-buttons-mix.md
- packages/store/package.json
- packages/world/package.json
attempting to resolve issues when running store-indexer via dist/bin
> fix(store,world): explicit mud.config exports

- .changeset/purple-buttons-mix.md
- packages/store/package.json
- packages/world/package.json
> Revert "fix(store,world): explicit mud.config exports"

- packages/block-logs-stream/src/blockRangeToLogs.test.ts
fixes https://github.com/latticexyz/mud/issues/1170
> test(block-logs-stream): attempt to fix flaky tests with timers

- .changeset/two-feet-jam.md
forgot this in https://github.com/latticexyz/mud/pull/1885
> docs: add changeset for SystemboundDelegationControl

- next-docs/pages/cli/gas-report.mdx
- next-docs/pages/cli/test.mdx
- next-docs/pages/cli/trace.mdx
- next-docs/pages/introduction.mdx
- next-docs/pages/plugins.mdx
- next-docs/pages/protocol-vs-framework.mdx
- next-docs/pages/services/faucet.mdx
- next-docs/pages/state-synchronization/approach.mdx
- next-docs/pages/state-synchronization/introduction.mdx
- next-docs/pages/state-synchronization/typescript/reference.mdx
- next-docs/pages/state-synchronization/typescript/storage-adapters.mdx
- next-docs/pages/templates/godot.mdx
- next-docs/pages/templates/unity.mdx
- next-docs/pages/world/reference.mdx
Also, add information that we have somewhere when encountered
> docs(newdocs): add **Coming soon** as appropriate

- packages/store-sync/src/zustand/createStore.ts
- packages/store-sync/src/zustand/syncToZustand.ts
At some point I want to rethink this abstraction but going to ship with this for now for consistency and unblocking workshops.
> feat(zustand): add sync progress

- packages/store-indexer/src/postgres/createQueryAdapter.ts
- packages/store-sync/src/postgres/postgresStorage.ts
maybe fixes https://github.com/latticexyz/mud/issues/1923
> fix(store-indexer,store-sync): catch query errors

- packages/store-sync/src/postgres/getTables.ts
- packages/store-sync/src/postgres/postgresStorage.ts
continued from #1930 
maybe fixes #1923
> fix(store-sync): filter postgres tables by ones we can query

- docs/pages/templates/unity.mdx
As requested by neilsonks on discord
> docs(template): change github for unity template

- .changeset/ninety-lions-double.md
- e2e/packages/contracts/package.json
- examples/minimal/packages/contracts/package.json
- packages/cli/src/build.ts
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/index.ts
- packages/cli/src/runDeploy.ts
- templates/phaser/packages/contracts/package.json
- templates/react-ecs/packages/contracts/package.json
- templates/react/packages/contracts/package.json
- templates/threejs/packages/contracts/package.json
- templates/vanilla/packages/contracts/package.json
closes https://github.com/latticexyz/mud/issues/1803
> feat(cli): add build command

- docs/pages/cli/faucet.mdx
- docs/pages/services/faucet.mdx
- examples/faucet-client/README.md
- examples/faucet-client/index.ts
- examples/faucet-client/package.json
- examples/faucet-client/pnpm-lock.yaml
- examples/faucet-client/tsconfig.json
- Explain that `mud faucet` isn't relevant anymore
- Show how to run the faucet service
- Add a sample program about how to get the drip from the faucet
> docs(faucet): the faucet service

- packages/store-sync/src/postgres-decoded/createStorageAdapter.test.ts
- packages/store-sync/src/postgres/createStorageAdapter.test.ts
- packages/store-sync/src/postgres/version.ts
to trigger a rebuild of DB after #2003
> chore(store-sync,store-indexer): bump postgres sync version

- docs/pages/templates/typescript/getting-started.mdx
based on https://discord.com/channels/865335009915961364/1181367844630429847/1181371732108513290
> docs(template/typescript): add prereqs to getting-started

- docs/pages/guides/hello-world/add-table.mdx
The new form is simpler, and would make filters much more obvious when I write that guide (hopefully later today).
> docs(guides/hello-world): add-table UI changes

- docs/pages/services/indexer.mdx
- Change to use the new default `World` address
- Add an explanation of how we got the URL, to avoid having a "magical value" that isn't explained
> docs(services): update the indexer verification portion

- .changeset/fresh-seals-compare.md
- packages/common/src/createBenchmark.ts
> chore(common): log benchmark to stderr

- docs/pages/templates/_meta.js
- docs/pages/templates/disclaimer.mdx
- docs/pages/templates/godot.mdx
- docs/pages/templates/pwa.mdx
- docs/pages/templates/svelte.mdx
- docs/pages/templates/swift.mdx
- docs/pages/templates/unity.mdx
Also fix a grammar issue in the disclaimer.
No answer on twitter, so I decided to ask for forgiveness rather than permission ;-)
> docs(templates): add svelte and pwa

- .changeset/tiny-lions-listen.md
- packages/faucet/bin/faucet-server.ts
- packages/faucet/package.json
- packages/faucet/src/createAppRouter.ts
- pnpm-lock.yaml
> fix(faucet): use MUD's sendTransaction for better nonce handling

- .github/workflows/test.yml
https://github.com/latticexyz/mud/issues/2118#issuecomment-1889312499
> test: increase forge test verbosity in ci

- packages/store/gas-report.json
- packages/store/test/StoreCore.t.sol
- packages/store/test/StoreCoreGas.t.sol
Adds tests + gas report for setting and deleting a record in an offchain table.
> test(store): add tests and gas reports for using offchain tables

- Dockerfile
Fixes https://github.com/latticexyz/mud/issues/2109
> chore(docker): remove remove go dependencies from Dockerfile

- packages/store/test/FieldLayout.t.sol
- packages/store/test/Schema.t.sol
fixes https://github.com/latticexyz/mud/issues/2113
> test(store): replace testFail with expectRevert

- .changeset/olive-bugs-add.md
- packages/store-sync/src/zustand/createStorageAdapter.ts
> fix(store-sync): improve syncToZustand hydration speed

- packages/store-indexer/bin/postgres-decoded-indexer.ts
accidentally duplicated this in #2163
> fix(store-indexer): remove duplicate middleware

- .changeset/mighty-points-study.md
> docs: changeset for #2187

- .changeset/chilly-fishes-speak.md
- .changeset/warm-colts-sleep.md
- packages/store/gas-report.json
- packages/store/src/StoreCore.sol
- packages/store/test/StoreCore.t.sol
- packages/world-modules/gas-report.json
- packages/world-modules/test/KeysWithValueModule.t.sol
- packages/world/src/modules/core/implementations/StoreRegistrationSystem.sol
- packages/world/src/modules/core/implementations/WorldRegistrationSystem.sol
- packages/world/test/World.t.sol
Adding two checks that we missed in https://github.com/latticexyz/mud/pull/2142
> fix(world): check table exists for register store and system hook [L-09]

- packages/store-sync/src/postgres-decoded/createStorageAdapter.test.ts
- packages/store-sync/src/postgres/createStorageAdapter.test.ts
> test: increase timeout of postgres tests

- docs/pages/_meta.js
- docs/pages/guides/replicating-onchain-state.mdx
https://mud-docs-git-holic-store-state-from-onchain-latticexyz.vercel.app/guides/replicating-onchain-state
> docs: add guide for replicating onchain state

- docs/components/MUDTable.module.css
- docs/components/MUDTable.tsx
- docs/next.config.mjs
- docs/pages/guides/_meta.js
- docs/pages/guides/extending-a-world.mdx
- docs/pages/guides/hello-world.mdx
- docs/pages/guides/how-mud-models-data.mdx
- docs/pages/guides/replicating-onchain-state.mdx
- docs/pages/store/_meta.js
- docs/pages/store/data-model.mdx
- docs/pages/store/introduction.mdx
- docs/pages/store/table-intro.mdx
- docs/pages/store/tables.mdx
- docs/pages/world/function-selectors.mdx
- docs/pages/world/introduction.mdx
- docs/tsconfig.json
https://mud-docs-git-holic-docs-mud-data-model-latticexyz.vercel.app/store/data-model
> docs: "How MUD models data" guide

- packages/store-sync/src/postgres-decoded/buildColumn.ts
Fixes https://github.com/latticexyz/mud/issues/2077
> fix(store-sync): use integer instead of smallint in decoded indexer

- docs/pages/world/account-delegation.mdx
- docs/pages/world/balance.mdx
- docs/pages/world/batch-calls.mdx
- docs/pages/world/function-selectors.mdx
- docs/pages/world/modules.mdx
- docs/pages/world/namespaces-access-control.mdx
- docs/pages/world/system-hooks.mdx
- docs/pages/world/systems.mdx
> docs(world): fix links to source code, `core`->`init`

- docs/pages/world/balance.mdx
Thanks to @jaxer (see https://discord.com/channels/865335009915961364/1204167080509706290/1204228835722403870)
> docs(world/balance): add solidity example

- docs/pages/guides/emojimon/1-preface-the-ecs-model.mdx
- docs/pages/guides/emojimon/2-getting-started.mdx
- docs/pages/guides/emojimon/3-players-and-movement.mdx
- docs/pages/guides/emojimon/4-map-and-terrain.mdx
- docs/pages/guides/emojimon/5-a-wild-emojimon-appears.mdx
- docs/pages/guides/emojimon/6-advanced.mdx
> docs(guides/emojimon): update for next.16

- .changeset/long-dots-think.md
missed this in https://github.com/latticexyz/mud/pull/2038
> docs: add missing changeset

- packages/store-sync/src/postgres-decoded/createStorageAdapter.test.ts
- packages/store-sync/src/postgres/createStorageAdapter.test.ts
- packages/store-sync/src/postgres/setupTables.test.ts
- packages/store-sync/src/sqlite/sqliteStorage.test.ts
> test: turn off drizzle logger

- .changeset/strange-cheetahs-drop.md
- docs/pages/world/reference/module-external.mdx
- docs/pages/world/reference/world-external.mdx
- packages/world-modules/test/KeysInTableModule.t.sol
- packages/world-modules/test/KeysWithValueModule.t.sol
- packages/world-modules/test/UniqueEntityModule.t.sol
- packages/world/src/IModule.sol
- packages/world/src/IModuleErrors.sol
- packages/world/src/IWorldKernel.sol
Ensures that the world ABI includes module errors
> feat(world): world kernel inherits `IModuleErrors`

- docs/pages/cli/deploy.mdx
> docs(cli): typo

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .vscode/extensions.json
This PR improves the devcontainer setup for a quick dev environment setup:
- installs vscode extensions to improve developer experience (eslint, prettier and solidity)
- spins up a postgres instance
- forwards all needed ports to host machine
Happy to make any additional changes to improve it even more ;)
> feat: devcontainer setup improvements

- docs/pages/store/data-model.mdx
Inspired by [this thread](https://discord.com/channels/865335009915961364/1217857860789342258/1218254472262844476).
> docs(store/data-models): clarify what `static` and `dynamic` means

- packages/store/ts/config/v2/compat.ts
- packages/store/ts/config/v2/output.ts
- packages/store/ts/config/v2/store.test.ts
- packages/store/ts/config/v2/storeWithShorthands.test.ts
- packages/store/ts/config/v2/table.test.ts
- packages/store/ts/config/v2/table.ts
- packages/world/ts/config/v2/world.test.ts
- packages/world/ts/config/v2/worldWithShorthands.test.ts
- add `getKeySchema` and `getValueSchema` helpers
- remove `keySchema` and `valueSchema` from default table resolver output
> feat(store): add getKeySchema and getValueSchema helpers

- packages/store-sync/src/query-cache/common.ts
- packages/store-sync/src/query-cache/createStorageAdapter.ts
- packages/store-sync/src/query-cache/createStore.ts
- packages/store-sync/src/query-cache/getTables.ts
- packages/store-sync/src/query-cache/syncToQueryCache.ts
- packages/store-sync/tsup.config.ts
Looks like a couple areas were missed in https://github.com/latticexyz/mud/pull/2475
> fix: store-sync uses `getKeySchema` helper

- packages/protocol-parser/package.json
- packages/protocol-parser/src/exports/index.ts
- packages/protocol-parser/src/exports/internal.ts
- packages/protocol-parser/src/getKeySchema.ts
- packages/protocol-parser/src/getSchemaTypes.ts
- packages/protocol-parser/src/getValueSchema.ts
- packages/store-sync/src/query-cache/createStorageAdapter.ts
- packages/store-sync/src/query-cache/createStore.ts
- packages/store/ts/config/v2/compat.ts
- packages/store/ts/config/v2/table.test.ts
- packages/store/ts/config/v2/table.ts
- pnpm-lock.yaml
pulled out of https://github.com/latticexyz/mud/pull/2470
> feat(protocol-parser): add new schema helpers

- .changeset/pre.json
> Revert "chore: exit prerelease"

- .github/workflows/bench.yml
- .github/workflows/build.yml
- .github/workflows/e2e.yml
- .github/workflows/examples.yml
- .github/workflows/prerelease.yml
- .github/workflows/snapshot.yml
- .github/workflows/templates.yml
- .github/workflows/test.yml
we don't need to run any of these when only docs changes
> build: ignore docs for most CI things

- CHANGELOG.md
- docs/pages/changelog.mdx
- package.json
- pnpm-lock.yaml
- scripts/changelog.ts
now supports ~any changeset mode, not just prerelease
> docs: update global changelog with changesets files

- .changeset/cold-tools-admire.md
Adding changeset missed in https://github.com/latticexyz/mud/pull/2473
> chore: threejs template changeset

- templates/threejs/packages/client/src/App.tsx
Template could not be published because the style used the template engine handlebars 
https://github.com/latticexyz/mud/actions/runs/8391273439/job/22986718489
> fix: threejs template style handlebars

- .changeset/silver-dancers-compete.md
- packages/cli/src/build.ts
> refactor(cli): remove forge cache workaround

- .changeset/five-colts-refuse.md
- packages/common/src/getNonceManager.ts
> fix(common): pass through rest of nonce manager opts

- .changeset/fresh-horses-type.md
- packages/world-modules/gas-report.json
- packages/world-modules/src/interfaces/IUnstable_CallWithSignatureSystem.sol
- packages/world-modules/src/modules/delegation/IUnstable_CallWithSignatureErrors.sol
- packages/world-modules/src/modules/delegation/Unstable_CallWithSignatureModule.sol
- packages/world-modules/src/modules/delegation/Unstable_CallWithSignatureSystem.sol
- packages/world-modules/src/modules/delegation/validateCallWithSignature.sol
- packages/world-modules/test/CallWithSignatureModule.t.sol
this is what using it would look like: https://github.com/latticexyz/gas-tank/pull/5
> feat(world-modules): add `validateCallWithSignature` to `Unstable_CallWithSignatureModule`

- e2e/packages/contracts/.env
- e2e/packages/sync-test/setup/startBrowserAndPage.ts
- e2e/packages/sync-test/setup/startIndexer.ts
- e2e/packages/test-data/generateLogs.ts
fixes https://github.com/latticexyz/mud/issues/2494
> test: reduce e2e CI logs

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
> Revert "build: skip docker build/release for now"

- package.json
- packages/abi-ts/tsup.config.ts
- packages/block-logs-stream/tsup.config.ts
- packages/cli/tsup.config.ts
- packages/common/tsup.config.ts
- packages/config/tsup.config.ts
- packages/dev-tools/tsup.config.ts
- packages/faucet/tsup.config.ts
- packages/gas-report/tsup.config.ts
- packages/protocol-parser/tsup.config.ts
- packages/query/tsup.config.ts
- packages/react/tsup.config.ts
- packages/recs/tsup.config.ts
- packages/schema-type/tsup.config.ts
- packages/services/tsup.config.ts
- packages/solhint-config-mud/tsup.config.ts
- packages/solhint-plugin-mud/tsup.config.ts
- packages/store-indexer/tsup.config.ts
- packages/store-sync/tsup.config.ts
- packages/store/tsup.config.ts
- packages/utils/tsup.config.ts
- packages/world-modules/tsup.config.ts
- packages/world/tsup.config.ts
> build: disable DTS in dev

- packages/dev-tools/src/summary/AccountSummary.tsx
> feat(dev-tools): add balance top up button when running on anvil

- .changeset/thirty-keys-cross.md
> docs: add changeset for devtools top up

- packages/cli/src/commands/build.ts
- packages/cli/src/commands/tablegen.ts
- packages/cli/src/commands/trace.ts
- packages/cli/src/commands/worldgen.ts
- packages/cli/src/runDeploy.ts
Pulled out of https://github.com/latticexyz/mud/pull/2662, suggested by https://github.com/latticexyz/mud/pull/2662#discussion_r1569248632
> docs(cli): description says path to the MUD config

- packages/world/gas-report.json
- packages/world/src/WorldProxy.sol
continued from https://github.com/latticexyz/mud/pull/2632
This means we can detect when the MUD protocol version has changed
> feat(world): worldProxy emits hello events when upgraded

- packages/world/gas-report.json
Looks like this was skipped in CI
> chore(world): run gas report

- .changeset/dry-cycles-film.md
- packages/block-logs-stream/src/fetchLogs.ts
> fix(block-logs-stream): handle proxyd errors

- CHANGELOG.md
- scripts/changelog.ts
Fixes https://github.com/latticexyz/mud/issues/2588
With this fix we can go back and fix all previous changesets
> docs: fix changelog

- .changeset/tall-steaks-give.md
- packages/common/src/chains/garnet.ts
- packages/common/src/chains/index.ts
- packages/common/src/chains/redstone.ts
> feat(common): add redstone chain config

- packages/cli/src/runDeploy.ts
Crept in by not merging main into https://github.com/latticexyz/mud/pull/2766
> fix(cli): postDeploy uses correct kms flag

- .github/workflows/release.yml
- .github/workflows/snapshot.yml
to resolve deadlock
https://github.com/latticexyz/mud/actions/runs/8915405248
> ci: remove concurrency from called workflows

- .github/workflows/docker.yml
forgot to remove this in #2783
> ci: remove docker matrix

- .changeset/small-turkeys-deliver.md
- packages/cli/package.json
- packages/config/package.json
- packages/faucet/package.json
- packages/store-indexer/package.json
- packages/store-sync/package.json
- packages/store/package.json
- packages/world-modules/package.json
- packages/world/package.json
- pnpm-lock.yaml
need this in https://github.com/latticexyz/mud/pull/2803 and abitype has been complaining about this anyway
> chore: bump zod

- .changeset/silver-mugs-talk.md
> docs(store-sync): add changeset for #2808

- .changeset/fuzzy-tools-explain.md
- templates/phaser/packages/client/src/mud/createSystemCalls.ts
- templates/phaser/packages/contracts/mud.config.ts
- templates/phaser/packages/contracts/script/PostDeploy.s.sol
- templates/phaser/packages/contracts/src/codegen/tables/Counter.sol
- templates/phaser/packages/contracts/src/codegen/world/IIncrementSystem.sol
- templates/phaser/packages/contracts/test/CounterTest.t.sol
- templates/react-ecs/packages/client/src/mud/createSystemCalls.ts
- templates/react-ecs/packages/contracts/mud.config.ts
- templates/react-ecs/packages/contracts/script/PostDeploy.s.sol
- templates/react-ecs/packages/contracts/src/codegen/tables/Counter.sol
- templates/react-ecs/packages/contracts/src/codegen/world/IIncrementSystem.sol
- templates/react-ecs/packages/contracts/test/CounterTest.t.sol
- templates/react/packages/client/src/mud/createSystemCalls.ts
- templates/react/packages/contracts/mud.config.ts
- templates/react/packages/contracts/script/PostDeploy.s.sol
- templates/react/packages/contracts/src/codegen/tables/Tasks.sol
- templates/react/packages/contracts/src/codegen/world/ITasksSystem.sol
- templates/react/packages/contracts/test/TasksTest.t.sol
- templates/threejs/packages/client/src/mud/createSystemCalls.ts
- templates/threejs/packages/contracts/mud.config.ts
- templates/threejs/packages/contracts/src/codegen/tables/Position.sol
- templates/threejs/packages/contracts/src/codegen/world/IMoveSystem.sol
- templates/vanilla/packages/client/src/mud/createSystemCalls.ts
- templates/vanilla/packages/contracts/mud.config.ts
- templates/vanilla/packages/contracts/script/PostDeploy.s.sol
- templates/vanilla/packages/contracts/src/codegen/tables/Counter.sol
- templates/vanilla/packages/contracts/src/codegen/world/IIncrementSystem.sol
- templates/vanilla/packages/contracts/test/CounterTest.t.sol
Replacing #2816 , #2817 , #2818 , #2819 , #2821
> feat(create-mud): use app namespace

- docs/pages/guides/emojimon/2-getting-started.mdx
- docs/pages/guides/extending-a-world/index.mdx
- docs/pages/quickstart.mdx
- docs/pages/templates/typescript/react-ecs.mdx
- docs/pages/templates/typescript/threejs.mdx
- docs/pages/templates/typescript/vanilla.mdx
Rather than just `pnpm create mud`
> docs: specify to `pnpm create mud@latest` 🏎

- docs/pages/guides/hello-world/add-table.mdx
As well as a few minor changes
> docs(guide/hello/add-table): update to account for the namespace change 🚗 

- packages/gas-report/package.json
missed in https://github.com/latticexyz/mud/pull/2828
> fix(gas-report): include solidity in published package

- packages/dev-tools/src/actions/getTransactionResult.ts
> fix(dev-tools): pass tx.value in getTransactionResult

- docs/pages/cli/deploy.mdx
Need shown in https://discord.com/channels/865335009915961364/1249026926497108010
> docs(cli/deploy): explain interaction with TypeScript templates 🚗 

- docs/pages/state-query/typescript/recs.mdx
Closing: https://github.com/latticexyz/mud/issues/2856
> docs(state-query/recs): update for new config file 🚗 

- .github/actions/setup-prerequisites/action.yml
see https://github.com/pnpm/action-setup/issues/135
> chore: bump pnpm setup action

- .github/workflows/remove-npm-tag.yml
> build: fix env in rm npm tag action

- .github/workflows/remove-npm-tag.yml
more and more convinced this never worked
> build: fix rm npm tag setup

- packages/store-sync/src/zustand/tablesByLabel.test.ts
> test(store-sync): add test for tablesByLabel keys

- .changeset/four-peas-swim.md
- packages/store-sync/src/recs/syncToRecs.ts
Followup to #2943, simplifying types
> chore(store-sync): simplify types

- .changeset/orange-dancers-nail.md
- packages/cli/src/deploy/getTables.ts
- packages/config/src/common.ts
- packages/protocol-parser/src/getKeySchema.ts
- packages/protocol-parser/src/getValueSchema.ts
- packages/store-sync/src/common.ts
- packages/store-sync/src/logToTable.test.ts
- packages/store-sync/src/logToTable.ts
- packages/store-sync/src/postgres-decoded/createStorageAdapter.test.ts
- packages/store-sync/src/recs/createStorageAdapter.ts
- packages/store-sync/src/recs/tableToComponent.ts
- packages/store-sync/src/recs/tablesToComponents.test.ts
- packages/store-sync/src/recs/tablesToComponents.ts
- packages/store-sync/src/zustand/createStorageAdapter.test.ts
- packages/store-sync/src/zustand/tablesByLabel.test.ts
- packages/store-sync/src/zustand/tablesByLabel.ts
- packages/store/ts/codegen/tableOptions.ts
- packages/store/ts/config/v2/index.ts
- packages/store/ts/config/v2/input.ts
- packages/store/ts/config/v2/namespacedTables.ts
- packages/store/ts/config/v2/output.ts
- packages/store/ts/config/v2/store.test.ts
- packages/store/ts/config/v2/store.ts
- packages/store/ts/config/v2/storeWithShorthands.test.ts
- packages/store/ts/config/v2/table.test.ts
- packages/store/ts/config/v2/table.ts
- packages/store/ts/config/v2/tableShorthand.ts
- packages/store/ts/config/v2/tables.ts
- packages/world/ts/config/v2/world.test.ts
- packages/world/ts/config/v2/worldWithShorthands.test.ts
pulled out of https://github.com/latticexyz/mud/pull/2929
changeset added for user-facing changes, the rest are internal
> feat(store,store-sync,world): add table labels, use them throughout

- packages/store/ts/config/v2/input.ts
- packages/store/ts/config/v2/namespace.ts
- packages/store/ts/config/v2/output.ts
- packages/store/ts/config/v2/store.test.ts
- packages/store/ts/config/v2/store.ts
- packages/store/ts/config/v2/storeWithShorthands.test.ts
- packages/store/ts/config/v2/table.test.ts
- packages/store/ts/config/v2/table.ts
- packages/world/ts/config/v2/world.test.ts
- packages/world/ts/config/v2/world.ts
- packages/world/ts/config/v2/worldWithShorthands.test.ts
- packages/world/ts/config/v2/worldWithShorthands.ts
no changeset yet as this isn't super useful on its own and we won't release until this is all done
will do a bigger changeset for the overall multi namespaces feature
> feat(store,world): add `namespaces` to config output

- docs/pages/world/modules/keysintable.mdx
Just fixed a a wrong link that was pointing to KeysWithValue. Also fixed a broken import.
> docs(*/reference and world/modules/keysintable): fixed import and link

- docs/pages/world/modules/keysintable.mdx
> docs(*/reference and world/modules/keysintable): added explanations

- Dockerfile
- e2e/package.json
> build: align dockerfile pnpm version, remove engines from e2e

- .changeset/seven-melons-kneel.md
to match snippets in announcements
> docs: update namespaces changeset

- package.json
- packages/store/ts/config/v2/schema.test.ts
- packages/store/ts/config/v2/scope.test.ts
- packages/store/ts/config/v2/store.test.ts
- packages/world/ts/config/v2/world.test.ts
- pnpm-lock.yaml
see https://github.com/arktypeio/arktype/issues/1078 and https://github.com/arktypeio/arktype/issues/1077
> chore: bump attest to 0.11, update snapshots

- packages/explorer/package.json
Add only the necessary files to `@latticexyz/explorer` package.
> chore(explorer): add files to explorer package

- packages/world/ts/node/findContractArtifacts.ts
similar to https://github.com/latticexyz/mud/pull/2975
> fix(world): glob on windows

- .prettierignore
- docs/pages/world/reference/internal/erc165.mdx
- scripts/render-api-docs.ts
pulled out of https://github.com/latticexyz/mud/pull/3078
> docs: fix ref

- .github/workflows/test-published-packages.yml
tried and failed in #3078 
ditching windows support for now (windows users can use WSL if they want MUD)
> ci: disable windows

- docs/pages/_meta.js
> docs(top bar): remove status 🚗 

- docs/pages/world/modules/erc721.mdx
> docs(world/modules/erc721): change `DDDD` to `MyToken` 🚗 

- docs/pages/guides/hello-world.mdx
- docs/pages/guides/hello-world/_meta.js
- docs/pages/guides/hello-world/deploy.mdx
> docs(guide/hello-world): deploy guide

- docs/pages/indexer/postgres-event-only.mdx
- docs/pages/indexer/sqlite.mdx
- docs/pages/services/_meta.js
Also remove the old `services` directory
> docs(indexer/sqlite): add `PORT` env variable 🚗 

- docs/pages/world/modules/_meta.js
- docs/pages/world/modules/erc20.mdx
> docs(world/modules/erc20): first version

- .changeset/bright-rabbits-trade.md
- packages/common/src/createNonceManager.ts
- packages/common/src/getNonceManager.ts
- packages/common/src/sendTransaction.ts
- packages/common/src/writeContract.ts
> fix(common): use latest block tag in nonce manager

- docs/pages/guides/_meta.js
- docs/pages/guides/replicating-onchain-state.mdx
- docs/pages/introduction.mdx
- docs/pages/templates.mdx
> docs(guide/replication): add a note that it's not something you're likely to need to do

- .husky/pre-commit
- package.json
- pnpm-lock.yaml
fixes issues we saw with branch named `stash`
> chore: bump lint-staged

- packages/stash/package.json
- packages/stash/src/actions/runQuery.test.ts
- packages/stash/src/actions/subscribeQuery.test.ts
- packages/stash/src/boundTable.test.ts
- packages/stash/src/createStash.test.ts
- packages/stash/vitestSetup.ts
- pnpm-lock.yaml
closes https://github.com/latticexyz/mud/issues/3258
> chore(stash): consistent ark deps

- .changeset/hot-buckets-draw.md
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/Explorer.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/TablesViewer.tsx
- packages/explorer/src/app/(explorer)/queries/useTableDataQuery.ts
> feat(explorer): show explore table error message

- packages/store/package.json
hoping this helps with MUD config issues in CI until #3290 is ready
> test(store): don't parallelize files

- packages/stash/package.json
- packages/stash/src/exports/react.ts
- packages/stash/tsup.config.ts
- tsconfig.paths.json
> fix(stash): export react

- .changeset/little-ligers-impress.md
- packages/explorer/package.json
- packages/explorer/src/app/(explorer)/api/world-abi/route.ts
- pnpm-lock.yaml
Switch to `fetchBlockLogs` to fetch params for world ABI.
> fix(explorer): switch to fetchBlockLogs

- .changeset/itchy-fireants-drop.md
> chore: add changeset for cli PR #3350

- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/Providers.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/EditableTableCell.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/interact/useContractMutation.ts
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/observe/TransactionsWatcher.tsx
reduces rpc spam for anvil from https://github.com/latticexyz/mud/pull/3365
> feat(explorer): use websocket transport when available, reduce anvil polling

- docs/app/DevconBanner.tsx
- docs/app/layout.tsx
> docs: mud day banner

- packages/explorer/src/app/(explorer)/[chainName]/worlds/WorldsForm.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/interact/page.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/layout.tsx
- packages/explorer/tailwind.config.ts
- Background / layout height fix
- "Enter" key for submitting world address
- Enter world on world address option select
- Mobile layout improvements (nav, padding)
> chore(explorer): polishes

- .changeset/ten-hornets-greet.md
- packages/explorer/package.json
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/ExportButton.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/TablesViewer.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/utils/exportTableData.ts
- packages/explorer/src/app/(explorer)/utils/constructTableName.ts
- packages/explorer/src/components/ui/DropdownMenu.tsx
- pnpm-lock.yaml
> feat(explorer): export table data

- packages/world-modules/test/CallWithSignatureModule.t.sol
> docs(world-modules): fix comment

- packages/world/test/WorldResourceId.t.sol
> test(world): add test for trimmed string

- .changeset/thick-peas-burn.md
- packages/world/ts/actions/callFrom.ts
> feat(world): rework types for callFrom viem action

- .eslintrc
- .gitignore
> chore: allow unused vars with _ prefix

- packages/entrykit/src/createWagmiConfig.ts
> fix(entrykit): missing arg/import

- .changeset/perfect-steaks-fold.md
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/Explorer.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/ExportButton.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/SQLEditor.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/TableSelector.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/TablesViewer.tsx
> feat(explorer): run query shortcut

- .changeset/khaki-panthers-collect.md
- packages/vite-plugin-mud/README.md
- packages/vite-plugin-mud/env.d.ts
- packages/vite-plugin-mud/package.json
- packages/vite-plugin-mud/src/exports/index.ts
- packages/vite-plugin-mud/src/isReadable.ts
- packages/vite-plugin-mud/src/plugin.ts
- packages/vite-plugin-mud/tsconfig.json
- packages/vite-plugin-mud/tsup.config.ts
- pnpm-lock.yaml
- tsconfig.paths.json
pulled out of https://github.com/latticexyz/mud/pull/3439
> feat(vite-plugin-mud): add MUD vite plugin

- .changeset/slimy-lemons-think.md
- packages/stash/src/exports/react.ts
- packages/stash/src/react/isArrayEqual.ts
- packages/stash/src/react/useRecord.ts
- packages/stash/src/react/useRecords.ts
pulled out of https://github.com/latticexyz/mud/pull/3439
> feat(stash): add useRecord and useRecords hooks

- .changeset/fast-nails-build.md
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/TablesViewer.tsx
> feat(explorer): key columns indicator

- .changeset/curly-carrots-sit.md
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/SQLEditor.tsx
> feat(explorer): indicate unsaved query changes

- packages/entrykit/src/getSessionSigner.ts
> feat(entrykit): reuse accountkit session if available

- .changeset/wild-starfishes-yell.md
- packages/cli/src/runDeploy.ts
> chore(cli): print mud version in deploy

- .changeset/beige-pears-exercise.md
- packages/world/ts/node/resolveSystems.ts
- namespaceLabel should be compared to namespaceLabel not namespace
> fix(world): namespaceLabel should be compared to namespaceLabel not namespace

- e2e/packages/contracts/test/Worldgen.t.sol
- packages/cli/contracts/test/Tablegen.t.sol
- packages/schema-type/test/solidity/SchemaType.t.sol
- packages/store/test/FieldLayout.t.sol
- packages/store/test/Schema.t.sol
- packages/store/test/StoreCoreDynamic.t.sol
- packages/store/test/StoreCoreGas.t.sol
- packages/world/test/AccessControl.t.sol
- packages/world/test/RevertWithBytes.t.sol
see notes here: https://github.com/foundry-rs/foundry/pull/9537#issuecomment-2619275096
> test: allow internal reverts where needed

- .changeset/fluffy-falcons-hide.md
> docs: changeset for #3394

- .changeset/three-seals-hear.md
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/TablesViewer.tsx
https://github.com/user-attachments/assets/b4a260ee-1952-4a09-ac1b-5ec4f197b298
> fix(explorer): show loader only on initial table data load

- .changeset/gold-baboons-buy.md
merged too quick and missed a changeset in #3538
> docs: changeset for #3538

- .changeset/orange-toes-cheer.md
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/SQLEditor.tsx
https://github.com/user-attachments/assets/376f6220-9b86-452d-91e2-0661464dafd9
> feat(explorer): loading indicator for refetched query

- packages/store/gas-report.json
- packages/world-modules/gas-report.json
- packages/world/gas-report.json
seems like an upstream foundry change impacted gas reports
> test: update gas reports

- packages/world-module-metadata/gas-report.json
not sure why this got missed in https://github.com/latticexyz/mud/pull/3603, maybe forge cache
> test: update metadata module gas report

- .changeset/famous-cows-join.md
- packages/entrykit/src/common.ts
- packages/entrykit/src/getSessionAccount.ts
- packages/entrykit/src/getSessionClient.ts
- packages/entrykit/src/onboarding/usePrerequisites.ts
- packages/entrykit/src/useSessionAccount.ts
- packages/entrykit/src/useSessionClient.ts
> feat(entrykit): expose session signer

- .changeset/famous-cows-join.md
- packages/entrykit/src/common.ts
- packages/entrykit/src/getSessionClient.ts
> feat(entrykit): expose world address on session client

- .changeset/thin-nails-shop.md
- packages/explorer/package.json
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/abi/AbiExplorer.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/abi/DecodeForm.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/abi/getErrorSelector.ts
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/abi/page.tsx
- packages/explorer/src/app/(explorer)/globals.css
- packages/explorer/src/components/Navigation.tsx
- pnpm-lock.yaml
> feat(explorer): abi explorer

- .changeset/big-feet-give.md
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/EditableTableCell.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/Explorer.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/TablesViewer.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/defaultColumn.tsx
Fixes https://github.com/latticexyz/mud/issues/3659
> fix(explorer): editable cells keep focus

- .changeset/nice-roses-fail.md
- packages/entrykit/src/onboarding/quarry/useAllowance.ts
- packages/entrykit/src/onboarding/quarry/useSpender.ts
- packages/entrykit/src/onboarding/useDelegation.ts
- packages/entrykit/src/onboarding/usePrerequisites.ts
- packages/entrykit/src/useCallWithSignatureNonce.ts
- packages/entrykit/src/useSessionAccount.ts
- packages/entrykit/src/useSessionClient.ts
fixes https://github.com/latticexyz/mud/issues/3677
> refactor(entrykit): use skipToken instead of enabled

- .changeset/polite-grapes-carry.md
- packages/entrykit/src/onboarding/GasBalance.tsx
> feat(entrykit): enable copying session wallet address

- .changeset/rude-zebras-laugh.md
- packages/explorer/package.json
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/TablesViewer.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/explore/utils/encodeFunctionArgs.ts
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/interact/FunctionField.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/interact/InteractForm.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/interact/content/FunctionField.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/interact/content/FunctionsContent.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/interact/content/SystemContent.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/interact/sidebar/FunctionSidebarItem.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/interact/sidebar/SidebarContent.tsx
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/interact/sidebar/SystemSidebarItem.tsx
- packages/explorer/src/app/(explorer)/components/ScrollIntoViewLink.tsx
- packages/explorer/src/app/(explorer)/hooks/useHashState.ts
- packages/explorer/src/components/ui/Collapsible.tsx
- pnpm-lock.yaml
> feat(explorer): interact system calls

- packages/store-sync/src/createPreconfirmedBlockStream.ts
> chore: fix type

- .changeset/lazy-rules-wink.md
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/decode/AbiExplorer.tsx
> feat(explorer): abi search and filter

- .changeset/fuzzy-pets-punch.md
- packages/store-sync/src/world/common.ts
- packages/store-sync/src/world/getSystemAbis.test.ts
- packages/store-sync/src/world/getSystemAbis.ts
- packages/store-sync/src/world/getWorldAbi.ts
- packages/store-sync/src/world/test/mocks.ts
fixes explorer not showing metadata system functions
> feat(store-sync): include registered system functions in ABI

- .changeset/green-experts-obey.md
- packages/explorer/src/app/(explorer)/[chainName]/worlds/[worldAddress]/interact/content/FunctionField.tsx
> chore(explorer): input parameter names
